PRAGMA enable_verification;
ATTACH DATABASE ':memory:' AS database;;
CREATE SCHEMA database.schema;;
CREATE TABLE database.schema.table(col ROW(field INTEGER));;
INSERT INTO database.schema.table VALUES ({'field': 42});;
USE database;
USE database.schema;
SELECT database.schema.table.col.field FROM database.schema.table;
SELECT database.schema.table.col FROM database.schema.table;
SELECT database.schema.table FROM database.schema.table;
SELECT schema.table FROM database.schema.table;
SELECT "table" FROM database.schema.table;
SELECT "table" FROM "table";
SELECT schema.table FROM "table";
SELECT database.table FROM "table";
SELECT database.schema.table FROM "table";
