PRAGMA enable_verification;
ATTACH ':memory:' AS db1 (READONLY 1);
ATTACH ':memory:' AS db1 (BLABLABLA 1);
ATTACH '__TEST_DIR__/attach_read_only.db' AS db1 (READONLY 1);
ATTACH '__TEST_DIR__/attach_read_only.db' AS db1;
CREATE TABLE db1.integers AS SELECT * FROM range(10) t(i);;
DETACH db1;
ATTACH '__TEST_DIR__/attach_read_only.db' AS db1 (READONLY 1);
CREATE TABLE db1.test AS SELECT * FROM range(10) t(i);;
ATTACH ':memory:' AS db2;
CREATE TABLE db2.integers AS SELECT * FROM db1.integers;
CREATE TABLE test AS SELECT * FROM range(10) t(i);;
ATTACH ':memory:' AS db1 (READ_WRITE);;
CREATE TABLE db1.test AS SELECT * FROM integers;
CREATE TABLE test AS SELECT * FROM db1.test;
SELECT SUM(i) FROM db1.integers;
SELECT SUM(i) FROM db2.integers;
SELECT SUM(i) FROM integers;
