PRAGMA enable_verification;
BEGIN TRANSACTION;
ATTACH '__TEST_DIR__/attach_transaction.db';
ROLLBACK;
BEGIN TRANSACTION;
ATTACH '__TEST_DIR__/attach_transaction.db';
INSERT INTO attach_transaction.integers VALUES (42);
ROLLBACK;
BEGIN TRANSACTION;
ATTACH '__TEST_DIR__/attach_transaction.db';
INSERT INTO attach_transaction.integers VALUES (42);
COMMIT;
BEGIN TRANSACTION;
DETACH attach_transaction;
ROLLBACK;
DETACH attach_transaction;
BEGIN TRANSACTION;
ATTACH '__TEST_DIR__/attach_transaction.db';
INSERT INTO attach_transaction.integers VALUES (84);
DETACH attach_transaction;
ROLLBACK;
BEGIN TRANSACTION;
ATTACH '__TEST_DIR__/attach_transaction.db';
INSERT INTO attach_transaction.integers VALUES (84);
DETACH attach_transaction;
COMMIT;
ATTACH '__TEST_DIR__/attach_transaction.db';
