PRAGMA enable_verification;
ATTACH '__TEST_DIR__/concurrent.db';;
DETACH concurrent;;
ATTACH '__TEST_DIR__/db1.db';;
DETACH db1;;
ATTACH '__TEST_DIR__/db1.db';;
ATTACH '__TEST_DIR__/con2_rollback_detach.db';;
START TRANSACTION;;
START TRANSACTION;;
ATTACH '__TEST_DIR__/con1.db';;
ATTACH '__TEST_DIR__/con1_commit.db';;
DETACH con2_rollback_detach;;
ATTACH '__TEST_DIR__/con2_rollback_detach.db';;
ATTACH '__TEST_DIR__/con1.db';;
DETACH con1;;
ATTACH '__TEST_DIR__/con1.db';;
COMMIT;;
ROLLBACK;
ATTACH '__TEST_DIR__/con1.db';;
ATTACH '__TEST_DIR__/con1.db';;
ATTACH '__TEST_DIR__/con1_commit.db';;
ATTACH '__TEST_DIR__/con2_rollback_detach.db';;
SELECT database_name FROM duckdb_databases() ORDER BY 1;;
