CREATE TABLE x1(a INTEGER PRIMARY KEY, b DOTS);
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
BEGIN;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA lock_status;
SELECT * FROM x1 WHERE a = 15;
PRAGMA lock_status;
INSERT INTO x1 VALUES(1, 'abc');
SELECT * FROM x1 WHERE a=1;
SELECT * FROM x1 WHERE a=-10;
BEGIN;
SELECT * FROM x1;
PRAGMA lock_status;
SELECT * FROM x1 WHERE a IN (1, -10);
