PRAGMA main.cache_size = 10;
PRAGMA main.cache_size;
PRAGMA main.cache_size;
PRAGMA main.cache_size;
PRAGMA main.cache_size;
select count(*) from sqlite_master;
select count(*) from sqlite_master;
select count(*) from sqlite_master;
SELECT count(*) FROM sqlite_master;
BEGIN;
PRAGMA incremental_vacuum;
SELECT count(*) FROM sqlite_master;
