SELECT 'Supercalifragilisticexpialidocious';
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 30);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 34);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 35);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 36);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -30);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -34);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -35);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -36);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 1, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 30, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 34, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 35, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 36, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -0, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -1, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -1, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -1, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -2, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -30, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -34, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -34, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -34, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -35, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -35, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -36, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -36, 1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -36, 2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', -36, 3);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 0, -2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 1, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 1, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 2, -2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 3, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 3, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 3, -2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 30, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 30, -2);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 34, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 35, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 36, 0);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 36, -1);
SELECT SUBSTR('Supercalifragilisticexpialidocious', 36, -2);
SELECT 'hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho';
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 0);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 1);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 2);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 3);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 4);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 5);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 0, 6);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 0);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 1);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 2);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 3);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 4);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 5);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 1, 6);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 3, 0);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 3, 1);
SELECT SUBSTR('hiÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ho', 3, 2);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 0, 0);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 0, 1);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 0, 2);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 0, 3);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 1, 0);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 1, 1);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 1, 2);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 1, 3);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 2, 0);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 2, 1);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', 2, 2);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', -1, 0);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', -1, 1);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', -1, 2);
SELECT SUBSTR('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´', -1, 3);
SELECT x'1234';
SELECT SUBSTR(x'1234', 0, 0);
SELECT SUBSTR(x'1234', 0, 1);
SELECT SUBSTR(x'1234', 0, 2);
SELECT SUBSTR(x'1234', 0, 3);
SELECT SUBSTR(x'1234', 1, 0);
SELECT SUBSTR(x'1234', 1, 1);
SELECT SUBSTR(x'1234', 1, 2);
SELECT SUBSTR(x'1234', 1, 3);
SELECT SUBSTR(x'1234', -1, 0);
SELECT SUBSTR(x'1234', -1, 1);
SELECT SUBSTR(x'1234', -1, 2);
SELECT SUBSTR(x'1234', -1, 3);
SELECT SUBSTR(x'1234', -2, 0);
SELECT SUBSTR(x'1234', -2, 1);
SELECT SUBSTR(x'1234', -2, 2);
SELECT SUBSTR(x'1234', -2, 3);
SELECT SUBSTR(x'1234', -1, 0);
SELECT SUBSTR(x'1234', -1, -1);
SELECT SUBSTR(x'1234', -1, -2);
SELECT SUBSTR(x'1234', -1, -3);
SELECT SUBSTR(x'1234', -2, 0);
SELECT SUBSTR(x'1234', -2, -1);
SELECT SUBSTR(x'1234', -2, -2);
SELECT SUBSTR(x'1234', 1, 0);
SELECT SUBSTR(x'1234', 1, -1);
SELECT SUBSTR(x'1234', 1, -2);
SELECT SUBSTR(x'1234', 2, 0);
SELECT SUBSTR(x'1234', 2, -1);
SELECT SUBSTR(x'1234', 2, -2);
