CREATE TABLE t1(a, b);
CREATE INDEX i1 ON t1(a, b);
CREATE INDEX i2 ON t1(b, a);
REINDEX;
REINDEX nocase;
REINDEX binary;
REINDEX t1;
REINDEX main.t1;
REINDEX i1;
REINDEX main.i1;
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
INSERT INTO t1 VALUES(5, 6);
CREATE TABLE saved(a,b,c,d,e);
INSERT INTO saved SELECT * FROM sqlite_master WHERE type = 'index';
PRAGMA writable_schema = 1;
DELETE FROM sqlite_master WHERE type = 'index';
DELETE FROM t1 WHERE a = 3;
INSERT INTO t1 VALUES(7, 8);
INSERT INTO t1 VALUES(9, 10);
PRAGMA writable_schema = 1;
INSERT INTO sqlite_master SELECT * FROM saved;
DROP TABLE saved;
PRAGMA integrity_check;
REINDEX;
PRAGMA integrity_check;
ATTACH 'test.db2' AS aux;
CREATE TABLE t2(x);
REINDEX;
REINDEX t1;
REINDEX aux.t1;
REINDEX t2;
CREATE TABLE collA(x);
REINDEX collA;
REINDEX main.collA;
REINDEX main.collA;
