PRAGMA auto_vacuum=0;
PRAGMA encoding;
CREATE TABLE t2(a,b);
INSERT INTO t2 VALUES(1,2);
SELECT * FROM t2;
CREATE TABLE t3(a,b);
INSERT INTO t3 VALUES(4,5);
SELECT * FROM t3;
CREATE TABLE t4(a,b);
INSERT INTO t4 VALUES('abc','xyz');
SELECT * FROM t4;
SELECT name FROM sqlite_master WHERE type='table' ORDER BY 1;
PRAGMA integrity_check;
PRAGMA auto_vacuum=1;
PRAGMA encoding;
INSERT INTO t2 VALUES(1,2);
SELECT * FROM t2;
INSERT INTO t3 VALUES(4,5);
SELECT * FROM t3;
INSERT INTO t4 VALUES('abc','xyz');
SELECT * FROM t4;
SELECT name FROM sqlite_master WHERE type='table' ORDER BY 1;
PRAGMA integrity_check;
PRAGMA auto_vacuum=2;
PRAGMA encoding;
INSERT INTO t2 VALUES(1,2);
SELECT * FROM t2;
INSERT INTO t3 VALUES(4,5);
SELECT * FROM t3;
INSERT INTO t4 VALUES('abc','xyz');
SELECT * FROM t4;
SELECT name FROM sqlite_master WHERE type='table' ORDER BY 1;
PRAGMA integrity_check;
