PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = wal;
PRAGMA synchronous = normal;
CREATE TABLE t1(i PRIMARY KEY, j);
INSERT INTO t1 VALUES(1, 'one');
INSERT INTO t1 VALUES(2, 'two');
CREATE TABLE t2(a, b);
PRAGMA wal_checkpoint;
CREATE TABLE t3(a PRIMARY KEY, b);
PRAGMA wal_checkpoint;
PRAGMA synchronous = NORMAL;
PRAGMA wal_autocheckpoint;
PRAGMA wal_autocheckpoint = 10;
PRAGMA wal_autocheckpoint;
CREATE TABLE t4(x PRIMARY KEY, y);
INSERT INTO t4 VALUES(1, 'one');
INSERT INTO t4 VALUES(2, 'two');
INSERT INTO t4 VALUES(3, 'three');
INSERT INTO t4 VALUES(4, 'four');
INSERT INTO t4 VALUES(5, 'five');
