PRAGMA foreign_keys = ON;
CREATE TABLE pp(x PRIMARY KEY);
CREATE TABLE cc(y REFERENCES pp DEFERRABLE INITIALLY DEFERRED);
INSERT INTO pp VALUES('abc');
INSERT INTO cc VALUES('abc');
BEGIN;
DROP TABLE cc;
CREATE TABLE cc(y REFERENCES pp DEFERRABLE INITIALLY DEFERRED);
INSERT INTO cc VALUES('abc');
BEGIN;
DROP TABLE cc;
DROP TABLE pp;
CREATE TABLE pp(x PRIMARY KEY);
CREATE TABLE cc(
    y INTEGER PRIMARY KEY REFERENCES pp DEFERRABLE INITIALLY DEFERRED
  );
INSERT INTO pp VALUES(5);
INSERT INTO cc VALUES(5);
BEGIN;
DROP TABLE cc;
CREATE TABLE cc(
    y INTEGER PRIMARY KEY REFERENCES pp DEFERRABLE INITIALLY DEFERRED
  );
INSERT INTO cc VALUES(5);
BEGIN;
DROP TABLE cc;
DROP TABLE pp;
CREATE TABLE pp1(x PRIMARY KEY);
CREATE TABLE cc1(y REFERENCES pp1 DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE pp2(x PRIMARY KEY);
CREATE TABLE cc2(y REFERENCES pp1 DEFERRABLE INITIALLY DEFERRED);
INSERT INTO pp1 VALUES(2200);
INSERT INTO cc1 VALUES(NULL);
INSERT INTO pp2 VALUES(2200);
INSERT INTO cc2 VALUES(2200);
BEGIN;
DELETE FROM pp2;
DROP TABLE cc1;
DROP TABLE cc2;
