CREATE TABLE t1(x, y);
INSERT INTO t1 VALUES(1, 2);
ATTACH 'test.db2' AS aux;
CREATE TABLE aux.t2(x, y);
INSERT INTO t2 VALUES(3, 4);
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = wal;
PRAGMA aux.journal_mode = wal;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
PRAGMA main.journal_mode = delete;
PRAGMA aux.journal_mode = delete;
BEGIN;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t2 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t2;
