CREATE TABLE t1(a,b);
INSERT INTO t1 VALUES(1,2);
INSERT INTO t1 VALUES(3,4);
CREATE INDEX i1 ON t1(a);
REINDEX;
PRAGMA integrity_check;
REINDEX t1;
PRAGMA integrity_check;
REINDEX i1;
PRAGMA integrity_check;
REINDEX main.t1;
REINDEX main.i1;
PRAGMA integrity_check;
REINDEX t1;
PRAGMA integrity_check;
REINDEX;
CREATE TABLE t0 (
        c0 INTEGER PRIMARY KEY DESC, 
        c1 UNIQUE DEFAULT NULL
      );
INSERT INTO t0(c0) VALUES (1), (2), (3), (4), (5);
SELECT c0 FROM t0 WHERE c1 IS NULL ORDER BY 1;
REINDEX;
SELECT c0 FROM t0 WHERE c1 IS NULL ORDER BY 1;
SELECT c0 FROM t0 WHERE c1 IS NULL AND c0 IN (1,2,3,4,5);
PRAGMA integrity_check;
SELECT c0 FROM t0 WHERE c1 IS NULL ORDER BY 1;
REINDEX;
SELECT c0 FROM t0 WHERE c1 IS NULL ORDER BY 1;
SELECT c0 FROM t0 WHERE c1 IS NULL AND c0 IN (1,2,3,4,5);
PRAGMA integrity_check;
