SELECT count(*) FROM sqlite_master;
PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 0;
CREATE TABLE t1(a);
CREATE INDEX i1 ON t1(a);
CREATE TABLE t2(a);
INSERT INTO t2 VALUES(1);
INSERT INTO t2 VALUES(2);
PRAGMA integrity_check;
PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 0;
INSERT INTO t2 VALUES(1);
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA auto_vacuum = 1;
DROP TABLE t1;
SELECT * FROM sqlite_master;
PRAGMA integrity_check;
