BEGIN;
CREATE TABLE numbers(a PRIMARY KEY, b);
INSERT INTO numbers(oid) VALUES(NULL);
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
INSERT INTO numbers(oid) SELECT NULL FROM numbers;
UPDATE numbers set a = oid, b = 'abcdefghijklmnopqrstuvwxyz0123456789';
pragma read_uncommitted = 1;
SELECT count(*) FROM numbers;
BEGIN;
DELETE FROM numbers;
DELETE FROM numbers;
CREATE TABLE t0(a, b);
CREATE TABLE t1(a, b DEFAULT 'hello world');
SELECT a, b FROM t0;
INSERT INTO t1(a) VALUES(1);
CREATE TABLE t2(a, b, c);
CREATE INDEX i1 ON t2(a);
