SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(arr, notEmpty(arr)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(str, notEmpty(str)) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
SELECT minIf(int, int != 0) FROM min_if;
DROP TABLE min_if;
