SELECT count() > 0 FROM parallel_replicas;
SET parallel_replica_offset = 1;
SELECT count() > 0 FROM parallel_replicas;
SET parallel_replicas_count = 0;
CREATE TABLE parallel_replicas_backup(d Date DEFAULT today(), x UInt32, u UInt64, s String) ENGINE = Memory;
SET parallel_replicas_count = 3;
SET parallel_replica_offset = 0;
INSERT INTO parallel_replicas_backup(d, x, u, s) SELECT d, x, u, s FROM parallel_replicas;
SELECT count() > 0 FROM parallel_replicas;
SET parallel_replica_offset = 1;
INSERT INTO parallel_replicas_backup(d, x, u, s) SELECT d, x, u, s FROM parallel_replicas;
SELECT count() > 0 FROM parallel_replicas;
SET parallel_replica_offset = 2;
INSERT INTO parallel_replicas_backup(d, x, u, s) SELECT d, x, u, s FROM parallel_replicas;
SELECT count() > 0 FROM parallel_replicas;
SET parallel_replicas_count = 0;
SELECT x, u, s FROM parallel_replicas_backup ORDER BY x, u, s ASC;
DROP TABLE parallel_replicas;
DROP TABLE parallel_replicas_backup;
