SELECT 'uniqHLL12';
SELECT Y, uniqHLL12(X) FROM (SELECT number AS X, (3*X*X - 7*X + 11) % 37 AS Y FROM system.numbers LIMIT 15) GROUP BY Y ORDER BY Y;
SELECT 'uniqHLL12 round(float)';
SELECT 'uniqHLL12 round(toFloat32())';
SELECT 'uniqHLL12 IPv4NumToString';
SELECT 'uniqCombined';
SELECT Y, uniqCombined(X) FROM (SELECT number AS X, (3*X*X - 7*X + 11) % 37 AS Y FROM system.numbers LIMIT 15) GROUP BY Y ORDER BY Y;
SELECT 'uniqCombined(12)';
SELECT 'uniqCombined(17)';
SELECT 'uniqCombined(20)';
SELECT 'uniqCombined(round(float))';
SELECT 'uniqCombined(12)(round(float))';
SELECT 'uniqCombined(17)(round(float))';
SELECT 'uniqCombined(20)(round(float))';
SELECT 'uniqCombined(X)(round(toFloat32()))';
SELECT 'uniqCombined(12)(round(toFloat32()))';
SELECT 'uniqCombined(17)(round(toFloat32()))';
SELECT 'uniqCombined(20)(round(toFloat32()))';
SELECT 'uniqCombined(Z)(IPv4NumToString)';
SELECT 'uniqCombined(12)(IPv4NumToString)';
SELECT 'uniqCombined(17)(IPv4NumToString)';
SELECT 'uniqCombined(20)(IPv4NumToString)';
