SET max_block_size = 1000;
DROP TABLE IF EXISTS numbers_10_00223;
CREATE TABLE numbers_10_00223 ENGINE = Log AS SELECT * FROM system.numbers LIMIT 10000;
SET distributed_aggregation_memory_efficient = 0;
SET group_by_two_level_threshold = 1000;
SET distributed_aggregation_memory_efficient = 0;
SET group_by_two_level_threshold = 7;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 1000;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 7;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 1;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 1000;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 1;
SET distributed_aggregation_memory_efficient = 1;
SET group_by_two_level_threshold = 7;
DROP TABLE numbers_10_00223;