SELECT count() FROM merge(currentDatabase(), '^numbers\\d+$');
SET optimize_aggregation_in_order = 0;
SET max_rows_to_read = 1000;
SET max_threads = 'auto';
SET max_threads = 1;
SET max_threads = 10;
SET max_rows_to_read = 1;
SET max_threads = 'auto';
SET max_threads = 1;
SET max_threads = 10;
DROP TABLE numbers1;
DROP TABLE numbers2;
DROP TABLE numbers3;
DROP TABLE numbers4;
DROP TABLE numbers5;
