select toValidUTF8('') from system.numbers limit 10;
select toValidUTF8('some text') from system.numbers limit 10;
select toValidUTF8('ÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂ¾ÃÂÃÂÃÂÃÂ¹-ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¾ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂµÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ') from system.numbers limit 10;
select toValidUTF8('\x00') from system.numbers limit 10;
select toValidUTF8('\x66') from system.numbers limit 10;
select toValidUTF8('\x7F') from system.numbers limit 10;
select toValidUTF8('\x00\x7F') from system.numbers limit 10;
select toValidUTF8('\x7F\x00') from system.numbers limit 10;
select toValidUTF8('\xC2\x80') from system.numbers limit 10;
select toValidUTF8('\xDF\xBF') from system.numbers limit 10;
select toValidUTF8('\xE0\xA0\x80') from system.numbers limit 10;
select toValidUTF8('\xE0\xA0\xBF') from system.numbers limit 10;
select toValidUTF8('\xED\x9F\x80') from system.numbers limit 10;
select toValidUTF8('\xEF\x80\xBF') from system.numbers limit 10;
select toValidUTF8('\xF0\x90\xBF\x80') from system.numbers limit 10;
select toValidUTF8('\xF2\x81\xBE\x99') from system.numbers limit 10;
select toValidUTF8('\xF4\x8F\x88\xAA') from system.numbers limit 10;
select toValidUTF8('a') from system.numbers limit 10;
select toValidUTF8('\xc3\xb1') from system.numbers limit 10;
select toValidUTF8('\xe2\x82\xa1') from system.numbers limit 10;
select toValidUTF8('\xf0\x90\x8c\xbc') from system.numbers limit 10;
select toValidUTF8('ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ, ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ') from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('some text')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('ÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂ¾ÃÂÃÂÃÂÃÂ¹-ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¾ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂµÃÂÃÂÃÂÃÂºÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\x00')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\x66')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\x7F')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\x00\x7F')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\x7F\x00')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xC2\x80')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xDF\xBF')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xE0\xA0\x80')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xE0\xA0\xBF')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xED\x9F\x80')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xEF\x80\xBF')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xF0\x90\xBF\x80')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xF2\x81\xBE\x99')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xF4\x8F\x88\xAA')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('a')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xc3\xb1')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xe2\x82\xa1')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('\xf0\x90\x8c\xbc')) from system.numbers limit 10;
select 1 = isValidUTF8(toValidUTF8('ÃÂÃÂ¬ÃÂÃÂÃÂÃÂÃÂÃÂ«ÃÂÃÂÃÂÃÂÃÂÃÂ­ÃÂÃÂÃÂÃÂÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ, ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ¬ÃÂÃÂÃÂÃÂ')) from system.numbers limit 10;
