select round(1000 * ngramSearchUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize(''), materialize('')))=round(1000 * ngramSearchUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), materialize('')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize(''), materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')))=round(1000 * ngramSearchUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('', materialize('')))=round(1000 * ngramSearchUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²', materialize('')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('', materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')))=round(1000 * ngramSearchUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')))=round(1000 * ngramSearchUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchUTF8('', ''));
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²', ''));
select round(1000 * ngramSearchUTF8('', 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'));
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'));
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶'));
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ·ÃÂÃÂ´'));
select round(1000 * ngramSearchUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'));
drop table if exists test_entry_distance;
create table test_entry_distance (Title String) engine = Memory;
insert into test_entry_distance values ('ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°?... ÃÂÃÂ¥ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ¾ÃÂÃÂ½'), ('ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ° ÃÂÃÂºÃÂÃÂ»ÃÂÃÂ¸ÃÂÃÂ¿ - TUT.BY'), ('ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ'), ('ÃÂÃÂ¿ÃÂÃÂ°ÃÂÃÂ¿ ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ° - TUT.BY'), ('ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂ±ÃÂÃÂÃÂÃÂ°ÃÂÃÂÃÂÃÂ°ÃÂÃÂ½ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ° - TUT.BY'), ('http://metric.ru/'), ('http://autometric.ru/'), ('http://top.bigmir.net/'), ('http://metris.ru/'), ('http://metrika.ru/'), ('');
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, Title) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, extract(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°')) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, extract(Title, 'metr')) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'metrica') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'metriks') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'metrics') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchUTF8(Title, 'bigmir') as distance, Title;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''),materialize(''))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'),materialize(''))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·'), materialize('ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), materialize('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('', materialize(''))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²',materialize(''))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('', materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize(''), 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·', materialize('ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', materialize('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'))) = round(1000 * ngramSearchCaseInsensitiveUTF8(materialize('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'), 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitiveUTF8('', ''));
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²', ''));
select round(1000 * ngramSearchCaseInsensitiveUTF8('', 'ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²'));
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·'));
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ·', 'ÃÂÃÂÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶'));
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂ°ÃÂÃÂ±ÃÂÃÂ²ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂ³ÃÂÃÂ´ÃÂÃÂµÃÂÃÂÃÂÃÂÃÂÃÂ'));
select round(1000 * ngramSearchCaseInsensitiveUTF8('ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂµÃÂÃÂÃÂÃÂ¶ÃÂÃÂ·', 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ'));
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, Title) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, extract(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°')) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, extract(Title, 'metr')) as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ²ÃÂÃÂÃÂÃÂ ÃÂÃÂºÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'Metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'mEtrica') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'metriKS') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'metrics') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'BigMIR') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitiveUTF8(Title, 'ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂÃÂÃÂÃÂÃÂ¢ ÃÂÃÂÃÂÃÂÃÂÃÂº ÃÂÃÂÃÂÃÂµÃÂÃÂÃÂÃÂ° ÃÂÃÂÃÂÃÂ»ÃÂÃÂÃÂÃÂ¿ - bigMir.Net') as distance, Title;
select round(1000 * ngramSearch(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefg')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize(''),materialize('')))=round(1000 * ngramSearch(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abc'),materialize('')))=round(1000 * ngramSearch(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize(''), materialize('abc')))=round(1000 * ngramSearch(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), materialize('abcdefgh')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), materialize('abcdefg')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefg')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), materialize('defgh')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearch(materialize('abcdefgh'), materialize('aaaaaaaa')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearch('',materialize('')))=round(1000 * ngramSearch(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearch('abc', materialize('')))=round(1000 * ngramSearch(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearch('', materialize('abc')))=round(1000 * ngramSearch(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearch('abcdefgh', materialize('abcdefgh')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearch('abcdefgh', materialize('abcdefg')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'abcdefg')) from system.numbers limit 5;
select round(1000 * ngramSearch('abcdefgh', materialize('defgh')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearch('abcdefgh', materialize('aaaaaaaa')))=round(1000 * ngramSearch(materialize('abcdefgh'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearch('', ''));
select round(1000 * ngramSearch('abc', ''));
select round(1000 * ngramSearch('', 'abc'));
select round(1000 * ngramSearch('abcdefgh', 'abcdefgh'));
select round(1000 * ngramSearch('abcdefgh', 'abcdefg'));
select round(1000 * ngramSearch('abcdefgh', 'defgh'));
select round(1000 * ngramSearch('abcdefghaaaaaaaaaa', 'aaaaaaaa'));
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂ¿ÃÂÃÂÃÂÃÂ¸ÃÂÃÂ²ÃÂÃÂµÃÂÃÂ ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'metrica') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'metriks') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'metrics') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearch(Title, 'bigmir') as distance, Title;
select round(1000 * ngramSearchCaseInsensitive(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abCdefgH'), 'Abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abcdefgh'), 'abcdeFG')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('AAAAbcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('ABCdefgH'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize(''), materialize('')))=round(1000 * ngramSearchCaseInsensitive(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abc'), materialize('')))=round(1000 * ngramSearchCaseInsensitive(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize(''), materialize('abc')))=round(1000 * ngramSearchCaseInsensitive(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abCdefgH'), materialize('Abcdefgh')))=round(1000 * ngramSearchCaseInsensitive(materialize('abCdefgH'), 'Abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('abcdefgh'), materialize('abcdeFG')))=round(1000 * ngramSearchCaseInsensitive(materialize('abcdefgh'), 'abcdeFG')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('AAAAbcdefgh'), materialize('defgh')))=round(1000 * ngramSearchCaseInsensitive(materialize('AAAAbcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive(materialize('ABCdefgH'), materialize('aaaaaaaa')))=round(1000 * ngramSearchCaseInsensitive(materialize('ABCdefgH'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('', materialize('')))=round(1000 * ngramSearchCaseInsensitive(materialize(''), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('abc', materialize('')))=round(1000 * ngramSearchCaseInsensitive(materialize('abc'), '')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('', materialize('abc')))=round(1000 * ngramSearchCaseInsensitive(materialize(''), 'abc')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('abCdefgH', materialize('Abcdefgh')))=round(1000 * ngramSearchCaseInsensitive(materialize('abCdefgH'), 'Abcdefgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('abcdefgh', materialize('abcdeFG')))=round(1000 * ngramSearchCaseInsensitive(materialize('abcdefgh'), 'abcdeFG')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('AAAAbcdefgh', materialize('defgh')))=round(1000 * ngramSearchCaseInsensitive(materialize('AAAAbcdefgh'), 'defgh')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('ABCdefgH', materialize('aaaaaaaa')))=round(1000 * ngramSearchCaseInsensitive(materialize('ABCdefgH'), 'aaaaaaaa')) from system.numbers limit 5;
select round(1000 * ngramSearchCaseInsensitive('', ''));
select round(1000 * ngramSearchCaseInsensitive('abc', ''));
select round(1000 * ngramSearchCaseInsensitive('', 'abc'));
select round(1000 * ngramSearchCaseInsensitive('abCdefgH', 'Abcdefgh'));
select round(1000 * ngramSearchCaseInsensitive('abcdefgh', 'abcdeFG'));
select round(1000 * ngramSearchCaseInsensitive('AAAAbcdefgh', 'defgh'));
select round(1000 * ngramSearchCaseInsensitive('ABCdefgHaAaaaAaaaAA', 'aaaaaaaa'));
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ²ÃÂÃÂÃÂÃÂ ÃÂÃÂºÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'ÃÂÃÂºÃÂÃÂ°ÃÂÃÂº ÃÂÃÂÃÂÃÂ ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢ ÃÂÃÂ´ÃÂÃÂµÃÂÃÂ»ÃÂÃÂ°') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'Metrika') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'mEtrica') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'metriKS') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'metrics') as distance, Title;
SELECT Title, round(1000 * distance) FROM test_entry_distance ORDER BY ngramSearchCaseInsensitive(Title, 'BigMIR') as distance, Title;
drop table if exists test_entry_distance;
