SELECT COUNT() FROM test;
ALTER TABLE test DETACH PARTITION tuple();
ALTER TABLE test ATTACH PARTITION tuple();
SELECT COUNT() FROM test;
DETACH TABLE test;
ATTACH TABLE test;
SELECT COUNT() FROM test;
DROP TABLE test;
