select * from mt_compact order by a limit 10;
select '=====================';
select distinct part_type from system.parts where database = currentDatabase() and table = 'mt_compact' and active;
insert into mt_compact (a, s, n.x, lc) select number % 3, toString((number * 75434535 + 645645) % 2133443), [1, 2], toString(number) from numbers(5);
optimize table mt_compact final;
select part_type, count() from system.parts where database = currentDatabase() and table = 'mt_compact' and active group by part_type order by part_type;
select * from mt_compact order by a, s limit 10;
select '=====================';
alter table mt_compact drop column n.y;
alter table mt_compact add column n.y Array(String) DEFAULT ['qwqw'] after n.x;
select * from mt_compact order by a, s limit 10;
select '=====================';
alter table mt_compact update b = 42 where 1;
select * from mt_compact where a > 1 order by a, s limit 10;
select '=====================';
drop table if exists mt_compact;
