SELECT 1, * FROM merge_tree ORDER BY d;
ALTER TABLE merge_tree DROP PARTITION 20200103;
SELECT 3, * FROM merge_tree ORDER BY d;
ALTER TABLE merge_tree DROP PARTITION '20200104';
SELECT 4, * FROM merge_tree ORDER BY d;
ALTER TABLE merge_tree DROP PARTITION '2020-01-05';
SELECT 5, * FROM merge_tree ORDER BY d;
SELECT 6, * FROM merge_tree ORDER BY d;
DROP TABLE merge_tree;
