drop user if exists "       ";
drop user if exists '   spaces';
drop user if exists 'spaces    ';
drop user if exists " spaces ";
drop user if exists "test 01119";
drop user if exists "ÐÐ°ÑÑ ÐÑÐ¿ÐºÐ¸Ð½";
drop user if exists "æ åæ° ";
drop user if exists "ð ð ð";
create user "       ";
create user '   spaces';
create user 'spaces    ';
create user ` INTERSERVER SECRET `;
create user '';
create user 'test 01119';
alter user `test 01119` rename to " spaces ";
alter user " spaces " rename to '';
alter user " spaces " rename to " INTERSERVER SECRET ";
create user "ÐÐ°ÑÑ ÐÑÐ¿ÐºÐ¸Ð½";
create user "æ åæ° ";
create user "ð ð ð";
select length(name), name, '.' from system.users where position(name, ' ')!=0 order by name;
drop user "       ";
drop user '   spaces';
drop user 'spaces    ';
drop user " spaces ";
drop user "ÐÐ°ÑÑ ÐÑÐ¿ÐºÐ¸Ð½";
drop user "æ åæ° ";
drop user "ð ð ð";