SELECT x, lc, r.lc, toTypeName(r.lc) FROM t AS l LEFT JOIN nr AS r USING (x) ORDER BY x;
SELECT '-';
SELECT '-';
SELECT '-';
SELECT '-';
SELECT '-';
SELECT x, lc FROM t AS l RIGHT JOIN nr AS r USING (lc) SETTINGS allow_experimental_analyzer = 1;
SELECT '-';
SELECT x, lc FROM t AS l RIGHT JOIN nr AS r USING (lc) SETTINGS allow_experimental_analyzer = 0;
SELECT '-';
SET join_use_nulls = 1;
SELECT '-';
SELECT '-';
SELECT '-';
SELECT x, lc FROM t AS l RIGHT JOIN nr AS r USING (lc);
SELECT '-';
DROP TABLE t;
DROP TABLE nr;
