SET send_logs_level = 'fatal';
DROP TABLE IF EXISTS rmt;
DROP TABLE IF EXISTS rmt1;
DROP TABLE IF EXISTS rmt2;
DROP TABLE IF EXISTS rmt3;
SET distributed_ddl_output_mode='none';
DROP DATABASE IF EXISTS test_01148_atomic;
CREATE DATABASE test_01148_atomic ENGINE=Atomic;
DROP DATABASE IF EXISTS test_01148_ordinary;
set allow_deprecated_database_ordinary=1;
CREATE DATABASE test_01148_ordinary ENGINE=Ordinary;
DROP DATABASE test_01148_ordinary;
DROP DATABASE test_01148_atomic;
DROP DATABASE IF EXISTS imdb_01148;
