SELECT x, lc, r.lc, toTypeName(r.lc) FROM t AS l LEFT JOIN nr AS r USING (x) ORDER BY x;
SELECT '-';
SELECT '-';
SELECT '-';
SELECT '-';
SELECT '-';
SET join_use_nulls = 1;
SELECT '-';
SELECT '-';
DROP TABLE nr;
DROP TABLE t;
