drop table if exists t;
drop table if exists dist;
drop table if exists buf;
drop table if exists join;
select 'test flush on replace';
create table t (n UInt64, s String default 's' || toString(n)) engine=Memory;
create table buf (n int) engine=Buffer(currentDatabase(), dist, 1, 10, 100, 10, 100, 1000, 1000);
system stop distributed sends dist;
insert into buf values (1);
system stop distributed sends buf;
insert into buf values (2);
replace table buf (n int) engine=Buffer(currentDatabase(), dist, 1, 10, 100, 10, 100, 1000, 1000);
system stop distributed sends dist;
insert into buf values (3);
replace table buf (n int) engine=Null;
select * from t order by n;
select 'exception on create and fill';
create or replace table join engine=Join(ANY, INNER, n) as select * from t where throwIf(n);
select count() from system.tables where database=currentDatabase() and name='join';
create or replace table join engine=Join(ANY, INNER, n) as select * from t;
select * from numbers(10) as t any join join on t.number=join.n order by n;
insert into t(n) values (4);
select * from numbers(10) as t any join join on t.number=join.n order by n;
replace table join engine=Join(ANY, INNER, n) as select * from t;
select * from numbers(10) as t any join join on t.number=join.n order by n;
select name from system.tables where database=currentDatabase() order by name;
drop table t;
drop table buf;
drop table join;
