select 'DISTINCT ORDER BY';
select 'GROUP BY ORDER BY';
select 'GROUP BY ORDER BY LIMIT';
select 'HAVING';
select 'GROUP BY HAVING';
select 'ORDER BY';
select 'ORDER BY LIMIT';
select 'ORDER BY LIMIT BY';
select 'cluster() ORDER BY';
select 'cluster() GROUP BY ORDER BY';
select 'LEFT JOIN';
select 'RIGHT JOIN';
insert into data_01223 select number%3 from numbers(30);
select 'GROUP BY ORDER BY group_by_two_level_threshold';
select 'GROUP BY ORDER BY distributed_aggregation_memory_efficient';
select 'GROUP BY ORDER BY distributed_aggregation_memory_efficient/group_by_two_level_threshold';
select 'COUNT';
select 'distributed_group_by_no_merge';
select 'only one shard in nested';
select 'distributed_group_by_no_merge';
select 'merge()';
select 'distributed_group_by_no_merge';
select 'GLOBAL IN';
drop table data_01223;
