describe table merge;
show create table merge;
insert into merge1 values (1, 'Hello, Alter Table!','2013-09-19', 1, 0, 2, '2013-09-19 12:43:06', 3);
select CounterID, dummy from merge where dummy <> '' limit 10;
alter table merge drop column dummy;
describe table merge;
show create table merge;
alter table merge add column dummy1 String after CounterID;
select CounterID, dummy1 from merge where dummy1 <> '' limit 10;
drop table merge;
drop table merge1;
drop table merge2;
