SELECT '-- default';
SELECT '-- same as default';
SELECT '-- rename';
SELECT '-- settings';
SELECT '-- to roles';
SELECT '-- complex';
SELECT '-- multiple profiles in one command';
SELECT '-- readonly ambiguity';
SELECT '-- system.settings_profiles';
SELECT name, storage, num_elements, apply_to_all, apply_to_list, apply_to_except FROM system.settings_profiles WHERE name LIKE 's%\_01294' ORDER BY name;
SELECT '-- system.settings_profile_elements';
SELECT * FROM system.settings_profile_elements WHERE profile_name LIKE 's%\_01294' ORDER BY profile_name, index;
