SHOW CREATE TABLE add_table;
ALTER TABLE add_table ADD COLUMN IF NOT EXISTS value1 UInt64;
SHOW CREATE TABLE add_table;
ALTER TABLE add_table ADD COLUMN IF NOT EXISTS key String, ADD COLUMN IF NOT EXISTS value1 UInt64;
SHOW CREATE TABLE add_table;
ALTER TABLE add_table ADD COLUMN IF NOT EXISTS value1 UInt64, ADD COLUMN IF NOT EXISTS value2 UInt64;
SHOW CREATE TABLE add_table;
DROP TABLE IF EXISTS add_table;
