select 'single argument';
select tuple(number) = tuple(number) from numbers(1);
select '- 1';
select '- 2';
select '- 3';
select '- 4';
select 'two arguments';
select '- 1';
select '- 2';
select '- 3';
select 'many arguments';
