SET log_queries=1;
SELECT 1;
SYSTEM FLUSH LOGS;
SELECT 1 /* QUERY_GROUP_ID:main_dashboard_top_query */;
SELECT 1 /* QUERY_GROUP_ID:main_dashboard_bottom_query */;
SELECT 1 WHERE not ignore(sleep(0.520)) /* QUERY_GROUP_ID:main_dashboard_top_query */;
SELECT 1 WHERE not ignore(sleep(0.520)) /* QUERY_GROUP_ID:main_dashboard_bottom_query */;
SET log_queries=0;
SYSTEM FLUSH LOGS;
SELECT '=== system.query_log ===';
SELECT '=== slowlog ===';
DROP TABLE expected_times;
