select '---Q1---';
select * from test_23634 where id !='';
select '---Q2---';
select * from test_23634 where id !='' and s != '';
select '---Q3---';
select * from test_23634 where id !='' and s != '' and s1 != '';
set force_primary_key=0;
select '---Q4---';
select * from test_23634 where (id, s, s1) != ('', '', '') order by id, s1, s1;
select '---Q5---';
select * from test_23634 where (id, s, s1) = ('', '', '') order by id, s1, s1;
select '---Q6---';
select * from test_23634 where (id, s, s1) = ('', '', 's2') order by id, s1, s1;
select '---Q7---';
select * from test_23634 where (id, s, s1) = ('', 's1', 's1') order by id, s1, s1;
select '---Q8---';
select * from test_23634 where (id, s, s1) = ('s', 's', 's') order by id, s1, s1;
select '---Q9---';
select * from test_23634 where (id, s, s1) = (null::Nullable(String), null::Nullable(String), null::Nullable(String)) order by id, s1, s1;
drop table test_23634;
