DROP TABLE IF EXISTS test_local;
DROP TABLE IF EXISTS test_distributed;
set allow_deprecated_syntax_for_merge_tree=1;
CREATE TABLE test_local (date Date, value UInt32) ENGINE = MergeTree(date, date, 8192);
INSERT INTO test_local SELECT '2000-08-01', number as value from numbers(50000);
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_rows_to_read_leaf = 40000;
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_bytes_to_read_leaf = 40000;
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_rows_to_read = 60000;
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_rows_to_read_leaf = 60000;
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_bytes_to_read = 100000;
SELECT count() FROM (SELECT * FROM test_distributed) SETTINGS max_bytes_to_read_leaf = 100000;
DROP TABLE IF EXISTS test_local;
DROP TABLE IF EXISTS test_distributed;