SELECT * FROM select_final FINAL ORDER BY x, t;
TRUNCATE TABLE select_final;
INSERT INTO select_final SELECT toDate('2000-01-01'), number, '' FROM numbers(2);
INSERT INTO select_final SELECT toDate('2000-01-01'), number, 'updated' FROM numbers(2);
OPTIMIZE TABLE select_final FINAL;
INSERT INTO select_final SELECT toDate('2020-01-01'), number, '' FROM numbers(2);
INSERT INTO select_final SELECT toDate('2020-01-01'), number, 'updated' FROM numbers(2);
SELECT max(x) FROM select_final FINAL where string = 'updated';
TRUNCATE TABLE select_final;
INSERT INTO select_final SELECT toDate('2000-01-01'), number, '' FROM numbers(500000);
OPTIMIZE TABLE select_final FINAL;
SET local_filesystem_read_method = 'pread';
set load_marks_asynchronously = 0;
SYSTEM FLUSH LOGS;
DROP TABLE select_final;
