SET allow_experimental_parallel_reading_from_replicas=0;
DROP TABLE IF EXISTS t;
CREATE TABLE t (x String) ENGINE = MergeTree ORDER BY x;
INSERT INTO t VALUES ('Hello');
SET max_parallel_replicas = 3;
DROP TABLE t;
CREATE TABLE t (x String) ENGINE = MergeTree ORDER BY cityHash64(x) SAMPLE BY cityHash64(x);
INSERT INTO t SELECT toString(number) FROM numbers(1000);
SET max_parallel_replicas = 1;
SET max_parallel_replicas = 2;
SET max_parallel_replicas = 3;
DROP TABLE t;
