optimize table xp final;
set max_rows_to_read = 2;
select * from xp where i in [0, 1];
select * from xp where i global in [0, 1];
set max_rows_to_read = 4;
select * from xp where i in (select * from numbers(2));
select * from xp where i global in (select * from numbers(2));
set max_rows_to_read = 6;
set transform_null_in = 1;
set max_rows_to_read = 4;
select * from xp where i in (select * from numbers(2));
select * from xp where i global in (select * from numbers(2));
set max_rows_to_read = 6;
set max_rows_to_read = 0;
select * from xp where i in (null);
select * from xp where i global in (null);
drop table if exists xp;
drop table if exists xp_d;
