SELECT accurateCast(5, 'UInt8');
SELECT accurateCast(5, 'UInt16');
SELECT accurateCast(5, 'UInt32');
SELECT accurateCast(5, 'UInt64');
SELECT accurateCast(5, 'UInt256');
SELECT accurateCast(5, 'Int8');
SELECT accurateCast(1, 'Decimal32(9)');
SELECT accurateCast('12', 'FixedString(2)');
SELECT accurateCast('2023-05-30 14:38:20', 'DateTime');
SELECT toString(accurateCast(19, 'DateTime'), 'UTC');
SELECT accurateCast('2023-05-30', 'Date');
SELECT accurateCast(19, 'Date');
select accurateCast('true', 'Bool');
select accurateCast('false', 'Bool');
select accurateCast('1', 'Bool');
select accurateCast('0', 'Bool');
select accurateCast(1, 'Bool');
select accurateCast(0, 'Bool');
select accurateCast('test', 'Nullable(IPv4)');
select accurateCast('192.0.2.1', 'IPv4');
select accurateCast('test', 'Nullable(IPv6)');
select accurateCast('192.0.2.1', 'IPv6');
select accurateCast('2001:db8::1', 'IPv6');
