select mapContains(a, 'name') from table_map;
select mapKeys(a) from table_map;
select mapFromArrays(c, d) from table_map;
drop table if exists table_map;
CREATE TABLE table_map (a Map(UInt8, Int), b UInt8, c UInt32, d Array(String), e Array(String)) engine = MergeTree order by tuple();
insert into table_map select map(number, number), number, number, [number, number, number], [number*2, number*3, number*4] from numbers(1000, 3);
select mapValues(a) from table_map;
drop table if exists table_map;
select map( 'aa', 4, 'bb' , 5) as m, mapKeys(m), mapValues(m);
select map(0, 0) as m, mapContains(m, number % 2) from numbers(2);
select mapFromArrays(['aa', 'bb'], materialize([4, 5])) from numbers(2);
