SELECT 'Tuple';
DROP TABLE IF EXISTS test_tuple;
CREATE TABLE test_tuple (value Tuple(UInt8, UInt8)) ENGINE=TinyLog;
INSERT INTO test_tuple VALUES ((NULL, 1));
SELECT * FROM test_tuple;
INSERT INTO test_tuple VALUES ((NULL, 2));
SELECT * FROM test_tuple;
DROP TABLE test_tuple;
SELECT 'Tuple nested in Array';
DROP TABLE IF EXISTS test_tuple_nested_in_array;
CREATE TABLE test_tuple_nested_in_array (value Array(Tuple(UInt8, UInt8))) ENGINE=TinyLog;
INSERT INTO test_tuple_nested_in_array VALUES ([(NULL, 2), (3, NULL), (NULL, 4)]);
SELECT * FROM test_tuple_nested_in_array;
INSERT INTO test_tuple_nested_in_array VALUES ([(NULL, 1)]);
SELECT * FROM test_tuple_nested_in_array;
DROP TABLE test_tuple_nested_in_array;
SELECT 'Tuple nested in Array nested in Tuple';
DROP TABLE IF EXISTS test_tuple_nested_in_array_nested_in_tuple;
CREATE TABLE test_tuple_nested_in_array_nested_in_tuple (value Tuple(UInt8, Array(Tuple(UInt8, UInt8)))) ENGINE=TinyLog;
INSERT INTO test_tuple_nested_in_array_nested_in_tuple VALUES ( (NULL, [(NULL, 2), (3, NULL), (NULL, 4)]) );
SELECT * FROM test_tuple_nested_in_array_nested_in_tuple;
INSERT INTO test_tuple_nested_in_array_nested_in_tuple VALUES ( (NULL, [(NULL, 1)]) );
SELECT * FROM test_tuple_nested_in_array_nested_in_tuple;
DROP TABLE test_tuple_nested_in_array_nested_in_tuple;
SELECT 'Tuple nested in Map';
SET allow_experimental_map_type = 1;
DROP TABLE IF EXISTS test_tuple_nested_in_map;
CREATE TABLE test_tuple_nested_in_map (value Map(String, Tuple(UInt8, UInt8))) ENGINE=TinyLog;
INSERT INTO test_tuple_nested_in_map VALUES (map('test', (NULL, 1)));
SELECT * FROM test_tuple_nested_in_map;
INSERT INTO test_tuple_nested_in_map VALUES (map('test', (NULL, 1)));
SELECT * FROM test_tuple_nested_in_map;
DROP TABLE test_tuple_nested_in_map;
SELECT 'Tuple nested in Map nested in Tuple';
DROP TABLE IF EXISTS test_tuple_nested_in_map_nested_in_tuple;
CREATE TABLE test_tuple_nested_in_map_nested_in_tuple (value Tuple(UInt8, Map(String, Tuple(UInt8, UInt8)))) ENGINE=TinyLog;
INSERT INTO test_tuple_nested_in_map_nested_in_tuple VALUES ( (NULL, map('test', (NULL, 1))) );
SELECT * FROM test_tuple_nested_in_map_nested_in_tuple;
INSERT INTO test_tuple_nested_in_map_nested_in_tuple VALUES ( (NULL, map('test', (NULL, 1))) );
SELECT * FROM test_tuple_nested_in_map_nested_in_tuple;
DROP TABLE test_tuple_nested_in_map_nested_in_tuple;