select * from x where _partition_id = partitionId(1);
set max_rows_to_read = 5;
select * from x where _partition_id in (select partitionId(number + 1) from numbers(1));
set max_rows_to_read = 2;
set max_rows_to_read = 3;
select count() from x where _partition_id in (select partitionId(number + 1) from numbers(1));
drop table x;
drop table if exists mt;
create table mt (n UInt64) engine=MergeTree order by n partition by n % 10;
set max_rows_to_read = 200;
insert into mt select * from numbers(100);
select * from mt where toUInt64(substr(_part, 1, position(_part, '_') - 1)) = 1;
drop table mt;
