SELECT * FROM foo_merge WHERE Val = 3 AND Id = 3;
SELECT count(), X FROM foo_merge JOIN t2 USING Val WHERE Val = 3 AND Id = 3 AND t2.X == 4 GROUP BY X;
DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS foo_merge;
DROP TABLE IF EXISTS t2;
