SELECT count() FROM join_table_mutation;
SELECT name FROM join_table_mutation WHERE id = 10;
ALTER TABLE join_table_mutation DELETE WHERE id = 10;
SELECT count() FROM join_table_mutation;
SELECT name FROM join_table_mutation WHERE id = 10;
INSERT INTO join_table_mutation VALUES (10, 'm10');
SELECT name FROM join_table_mutation WHERE id = 10;
ALTER TABLE join_table_mutation DELETE WHERE id % 2 = 0;
SELECT count() FROM join_table_mutation;
ALTER TABLE join_table_mutation DELETE WHERE name IN ('1', '2', '3', '4');
SELECT count() FROM join_table_mutation;
ALTER TABLE join_table_mutation DELETE WHERE 1;
SELECT count() FROM join_table_mutation;
DROP TABLE join_table_mutation;
