SELECT 'leftPad';
SELECT leftPad('abc', 0), leftPad('abc', 0::Int32);
SELECT leftPad('abc', 1), leftPad('abc', 1::Int32);
SELECT leftPad('abc', 2), leftPad('abc', 2::Int32);
SELECT leftPad('abc', 3), leftPad('abc', 3::Int32);
SELECT leftPad('abc', 4), leftPad('abc', 4::Int32);
SELECT leftPad('abc', 5), leftPad('abc', 5::Int32);
SELECT leftPad('abc', 10), leftPad('abc', 10::Int32);
SELECT leftPad('abc', 2, '*'),  leftPad('abc', 2::Int32, '*');
SELECT leftPad('abc', 4, '*'),  leftPad('abc', 4::Int32, '*');
SELECT leftPad('abc', 5, '*'),  leftPad('abc', 5::Int32, '*');
SELECT leftPad('abc', 10, '*'), leftPad('abc', 10::Int32, '*');
SELECT leftPad('abc', 2, '*.'), leftPad('abc', 2::Int32, '*.');
SELECT leftPad('abc', 4, '*.'), leftPad('abc', 4::Int32, '*.');
SELECT leftPad('abc', 5, '*.'), leftPad('abc', 5::Int32, '*.');
SELECT leftPad('abc', 10, '*.'),leftPad('abc', 10::Int32, '*.');
SELECT 'leftPadUTF8';
SELECT leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2), leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2::Int32);
SELECT leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2), leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2::Int32);
SELECT leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4), leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4::Int32);
SELECT leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4), leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4::Int32);
SELECT leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12, 'ÃÂ§ÃÂÃÂ¡'), leftPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12::Int32, 'ÃÂ§ÃÂÃÂ¡');
SELECT leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12, 'ÃÂ§ÃÂÃÂ¡'), leftPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12::Int32, 'ÃÂ§ÃÂÃÂ¡');
SELECT 'rightPad';
SELECT rightPad('abc', 0), rightPad('abc', 0::Int32);
SELECT rightPad('abc', 1), rightPad('abc', 1::Int32);
SELECT rightPad('abc', 2), rightPad('abc', 2::Int32);
SELECT rightPad('abc', 3), rightPad('abc', 3::Int32);
SELECT rightPad('abc', 4), rightPad('abc', 4::Int32);
SELECT rightPad('abc', 5), rightPad('abc', 5::Int32);
SELECT rightPad('abc', 10), rightPad('abc', 10::Int32);
SELECT rightPad('abc', 2, '*'), rightPad('abc', 2::Int32, '*');
SELECT rightPad('abc', 4, '*'), rightPad('abc', 4::Int32, '*');
SELECT rightPad('abc', 5, '*'), rightPad('abc', 5::Int32, '*');
SELECT rightPad('abc', 10, '*'), rightPad('abc', 10::Int32, '*');
SELECT rightPad('abc', 2, '*.'), rightPad('abc', 2::Int32, '*.');
SELECT rightPad('abc', 4, '*.'), rightPad('abc', 4::Int32, '*.');
SELECT rightPad('abc', 5, '*.'), rightPad('abc', 5::Int32, '*.');
SELECT rightPad('abc', 10, '*.'), rightPad('abc', 10::Int32, '*.');
SELECT 'rightPadUTF8';
SELECT rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2), rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2::Int32);
SELECT rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2), rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 2::Int32);
SELECT rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4), rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4::Int32);
SELECT rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4), rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 4::Int32);
SELECT rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12, 'ÃÂ§ÃÂÃÂ¡'), rightPad('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12::Int32, 'ÃÂ§ÃÂÃÂ¡');
SELECT rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12, 'ÃÂ§ÃÂÃÂ¡'), rightPadUTF8('ÃÂ°ÃÂ±ÃÂ²ÃÂ³', 12::Int32, 'ÃÂ§ÃÂÃÂ¡');
SELECT 'numbers';
SELECT rightPad(leftPad(toString(number), number, '_'), number*2, '^') FROM numbers(7);
SELECT rightPad(leftPad(toString(number), number::Int64, '_'), number::Int64*2, '^') FROM numbers(7);
