SELECT tokens('test');
SELECT tokens('test1, test2, test3');
SELECT tokens('test1, test2,     test3, test4');
SELECT tokens('test1,;
\ test2,;
\ test3,;
\   test4');
SELECT tokens('ÐµÌ Ñ à°à±à°âà°¾ æ¬æ°ã§ãã ï·º á¾ Î ×©Ö¼');
SELECT tokens('ÐµÌ, Ñ, à°à±à°âà°¾, æ¬æ°ã§ãã, ï·º, á¾, Î, ×©Ö¼');
SELECT tokens('ÐµÌ, Ñ, à°à±à°âà°¾, æ¬æ°ã§ãã, ï·º, á¾, Î,    ×©Ö¼');
SELECT tokens('ÐµÌ;
\ Ñ;
\ à°à±à°âà°¾;
\ æ¬æ°ã§ãã;
\ ï·º;
\ á¾;
\ Î;
\    ×©Ö¼');
SELECT tokens(materialize('test'));
SELECT tokens(materialize('test1, test2, test3'));
SELECT tokens(materialize('test1, test2,    test3, test4'));
SELECT tokens(materialize('test1,;
\ test2,;
\ test3,;
\    test4'));
SELECT tokens(materialize('ÐµÌ Ñ à°à±à°âà°¾ æ¬æ°ã§ãã ï·º á¾ Î ×©Ö¼'));
SELECT tokens(materialize('ÐµÌ, Ñ, à°à±à°âà°¾, æ¬æ°ã§ãã, ï·º, á¾, Î, ×©Ö¼'));
SELECT tokens(materialize('ÐµÌ, Ñ, à°à±à°âà°¾, æ¬æ°ã§ãã, ï·º, á¾, Î,    ×©Ö¼'));
SELECT tokens(materialize('ÐµÌ;
\ Ñ;
\ à°à±à°âà°¾;
\ æ¬æ°ã§ãã;
\ ï·º;
\ á¾;
\ Î;
\    ×©Ö¼'));