select toDate(0);
select toDateTime(0, 'Asia/Istanbul');
select toMonday(toDate(0));
select toStartOfWeek(toDate(0));
select toStartOfMonth(toDate(0));
select toStartOfQuarter(toDate(0));
select toStartOfYear(toDate(0));
select toTime(toDateTime(0, 'Asia/Istanbul'));
select toStartOfMinute(toDateTime(0, 'Asia/Istanbul'));
select toStartOfFiveMinutes(toDateTime(0, 'Asia/Istanbul'));
select toStartOfTenMinutes(toDateTime(0, 'Asia/Istanbul'));
select toStartOfFifteenMinutes(toDateTime(0, 'Asia/Istanbul'));
select toStartOfHour(toDateTime(0, 'Asia/Istanbul'));
