SELECT 'The data of table:';
SELECT * FROM map_extractKeyLike_test ORDER BY id;
SELECT '';
SELECT id, mapExtractKeyLike(map, 'P1%') FROM map_extractKeyLike_test ORDER BY id;
SELECT '';
SELECT id, mapExtractKeyLike(map, '5-K1') FROM map_extractKeyLike_test ORDER BY id;
DROP TABLE map_extractKeyLike_test;
SELECT mapExtractKeyLike(map('aa', 1, 'bb', 2), 'a%');
SELECT mapExtractKeyLike(map('aa', 1, 'bb', 2), materialize('a%'));
SELECT mapExtractKeyLike(materialize(map('aa', 1, 'bb', 2)), 'a%');
SELECT mapExtractKeyLike(materialize(map('aa', 1, 'bb', 2)), materialize('a%'));
