Select '-- #1 --';
select * from kql($$Customers | where FirstName !in ('Peter', 'Latoya')$$);
Select '-- #2 --';
select * from kql($$Customers | where FirstName !in ("test", "test2")$$);
Select '-- #3 --';
select * from kql($$Customers | where FirstName !contains 'Pet'$$);
Select '-- #4 --';
select * from kql($$Customers | where FirstName !contains_cs 'Pet'$$);
Select '-- #5 --';
select * from kql($$Customers | where FirstName !endswith 'ter'$$);
Select '-- #6 --';
select * from kql($$Customers | where FirstName !endswith_cs 'ter'$$);
Select '-- #7 --';
select * from kql($$Customers | where FirstName != 'Peter'$$);
Select '-- #8 --';
select * from kql($$Customers | where FirstName !has 'Peter'$$);
Select '-- #9 --';
select * from kql($$Customers | where FirstName !has_cs 'peter'$$);
Select '-- #10 --';
Select '-- #11 --';
Select '-- #12 --';
Select '-- #13 --';
Select '-- #14 --';
select * from kql($$Customers | where FirstName !startswith 'Peter'$$);
Select '-- #15 --';
select * from kql($$Customers | where FirstName !startswith_cs 'Peter'$$);
DROP TABLE IF EXISTS Customers;
