set dialect = 'kusto';
print '--  distinct * --';
Customers | distinct *;
print '--  distinct one column --';
Customers | distinct Occupation;
print '--  distinct two column --';
Customers | distinct Occupation, Education;
print '--  distinct with where --';
Customers where Age <30 | distinct Occupation, Education;
print '--  distinct with where, order --';
Customers |where Age <30 | order by Age| distinct Occupation, Education;
