SELECT 'Ok';
DROP TABLE IF EXISTS store_returns;
DROP TABLE IF EXISTS catalog_sales;
DROP TABLE IF EXISTS catalog_returns;
DROP TABLE IF EXISTS date_dim;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS customer_demographics;
DROP TABLE IF EXISTS promotion;
DROP TABLE IF EXISTS household_demographics;
DROP TABLE IF EXISTS customer_address;
DROP TABLE IF EXISTS income_band;
DROP TABLE IF EXISTS item;
