set use_structure_from_insertion_table_in_table_functions=2;
insert into test select * from file(02458_data.jsonl);
insert into test select x, 1 from file(02458_data.jsonl);
insert into test select x, y from file(02458_data.jsonl);
insert into test select x, z from file(02458_data.jsonl);
insert into test select * from file(02458_data.jsoncompacteachrow);
drop table test;
create table test (x Nullable(UInt32)) engine=Memory();
insert into test select * from file(02458_data.jsonl);
insert into test select x from file(02458_data.jsonl);
insert into test select y from file(02458_data.jsonl);
insert into test select y as x from file(02458_data.jsonl);
drop table test;
