OPTIMIZE TABLE testing FINAL;
SELECT c FROM testing ORDER BY d;
SELECT c FROM testing ORDER BY e, d;
ALTER TABLE testing UPDATE c = c+1, d = d+2 WHERE True SETTINGS mutations_sync=2;
SELECT * FROM system.mutations WHERE database = currentDatabase() AND table = 'testing' AND not is_done;
SELECT c FROM testing ORDER BY d;
SELECT c FROM testing ORDER BY e, d;
ALTER TABLE testing UPDATE d = d-1 WHERE True SETTINGS mutations_sync=2;
SELECT * FROM system.mutations WHERE database = currentDatabase() AND table = 'testing' AND not is_done;
SELECT c FROM testing ORDER BY d;
SELECT c FROM testing ORDER BY e, d;
ALTER TABLE testing UPDATE c = c-1 WHERE True SETTINGS mutations_sync=2;
SELECT * FROM system.mutations WHERE database = currentDatabase() AND table = 'testing' AND not is_done;
SELECT c FROM testing ORDER BY d;
SELECT c FROM testing ORDER BY e, d;
DROP TABLE testing;
