CHECK TABLE t_source_part_is_intact SETTINGS max_threads = 1;
SELECT 1, count() FROM t_source_part_is_intact;
ALTER TABLE t_source_part_is_intact update u = 0 where u != 0;
CHECK TABLE t_source_part_is_intact SETTINGS max_threads = 1;
ALTER TABLE t_source_part_is_intact update u = 1 WHERE 1;
CHECK TABLE t_source_part_is_intact SETTINGS max_threads = 1;
DETACH TABLE t_source_part_is_intact;
ATTACH TABLE t_source_part_is_intact;
CHECK TABLE t_source_part_is_intact SETTINGS max_threads = 1;
DROP TABLE t_source_part_is_intact;
