select 'JSONEachRow';
set schema_inference_make_columns_nullable=1;
set schema_inference_make_columns_nullable=0;
select 'JSONCompactEachRow';
set schema_inference_make_columns_nullable=1;
set schema_inference_make_columns_nullable=0;
select 'CSV';
set schema_inference_make_columns_nullable=1;
set schema_inference_make_columns_nullable=0;
