select transform(2, [1,2], [9,1], materialize(null));
select 'sep1';
SELECT transform(number, [2], [toDecimal32(1, 1)], materialize(80000)) as x FROM numbers(2);
select 'sep2';
select 'sep3';
select 'sep4';
select 'sep5';
select 'sep6';
SELECT 'issue #53187';
SELECT '-';
