SELECT count() from 02581_trips WHERE description = '';
SELECT name FROM system.parts WHERE database=currentDatabase() AND table = '02581_trips' AND active ORDER BY name;
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
SELECT count() from 02581_trips WHERE description = '';
DROP TABLE 02581_trips;
