SET keeper_map_strict_mode = 1;
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
SELECT '-----------';
DROP TABLE IF EXISTS 02707_keepermap_delete_update;
