SELECT * FROM t1 JOIN t2 ON t1.id = t2.id AND t1.attr != 0;
INSERT INTO t1 VALUES (0, 1);
SELECT * FROM t1 JOIN t2 ON t1.id = t2.id AND t1.attr != 0;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
