SELECT '--- YYYYMMDDToDate';
SELECT 'Invalid input types are rejected';
SELECT 'Result type is Date';
SELECT toTypeName(YYYYMMDDToDate(19910824));
SELECT 'Check correctness, integer arguments';
SELECT YYYYMMDDToDate(19691231);
SELECT 'Check correctness, float arguments';
SELECT 'Check correctness, decimal arguments';
SELECT 'Special cases';
SELECT '--- YYYYMMDDToDate32';
SELECT 'Invalid input types are rejected';
SELECT 'Result type is Date32';
SELECT 'Check correctness, integer arguments';
SELECT YYYYMMDDToDate32(18991231);
SELECT 'Check correctness, float arguments';
SELECT 'Check correctness, decimal arguments';
SELECT 'Special cases';
