SET allow_experimental_parallel_reading_from_replicas=1, max_parallel_replicas=3, parallel_replicas_for_non_replicated_merge_tree=1;
SYSTEM FLUSH LOGS;
SET allow_experimental_parallel_reading_from_replicas=0;
DROP TABLE tt;
