DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 0, describe_include_virtual_columns = 0, describe_include_subcolumns = 1;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 0, describe_include_virtual_columns = 1, describe_include_subcolumns = 0;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 0, describe_include_virtual_columns = 1, describe_include_subcolumns = 1;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 1, describe_include_virtual_columns = 0, describe_include_subcolumns = 0;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 1, describe_include_virtual_columns = 0, describe_include_subcolumns = 1;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 1, describe_include_virtual_columns = 1, describe_include_subcolumns = 0;
DESCRIBE TABLE t_describe_options;
SET describe_compact_output = 1, describe_include_virtual_columns = 1, describe_include_subcolumns = 1;
DESCRIBE TABLE t_describe_options;
DROP TABLE t_describe_options;
