SELECT '-- negative tests';
SELECT '-- UInt32 and Int32 arguments, both const and non-const';
SELECT 719527 AS u, toInt32(u) AS s, fromDaysSinceYearZero(u), fromDaysSinceYearZero(materialize(u)), fromDaysSinceYearZero(s), fromDaysSinceYearZero(materialize(s));
SELECT 693961 AS u, toInt32(u) AS s, fromDaysSinceYearZero32(u), fromDaysSinceYearZero32(materialize(u)), fromDaysSinceYearZero32(s), fromDaysSinceYearZero32(materialize(s));
SELECT '-- integer types != (U)Int32';
SELECT toUInt64(719529) AS u, toInt64(719529) AS s, fromDaysSinceYearZero(u), fromDaysSinceYearZero32(u), fromDaysSinceYearZero(s), fromDaysSinceYearZero32(s);
SELECT '-- NULL handling';
SELECT '-- ubsan bugs';
SELECT '-- Alias';
SELECT FROM_DAYS(1);
