SELECT INTERVAL 1 SECOND = INTERVAL 1 SECOND;
SELECT INTERVAL 30 DAY < INTERVAL 1 MONTH;
-- This we could change in the future:
SELECT INTERVAL 1 SECOND = INTERVAL 1 YEAR;
SELECT INTERVAL 1 SECOND <= INTERVAL 1 YEAR;