SELECT 'Inserted';
SELECT count(), sum(v) FROM t_materialize_delete;
SELECT 'Lighweight deleted';
DELETE FROM t_materialize_delete WHERE id % 7 = 3;
SELECT 'Mask applied';
ALTER TABLE t_materialize_delete APPLY DELETED MASK;
SELECT 'Lighweight deleted';
DELETE FROM t_materialize_delete WHERE id % 7 = 4;
SELECT 'Mask applied in partition';
ALTER TABLE t_materialize_delete APPLY DELETED MASK IN PARTITION 5;
DROP TABLE t_materialize_delete;
