set allow_experimental_variant_type = 1;
set allow_suspicious_variant_types = 1;
set session_timezone = 'UTC';
select 'JSON';
select 'String';
select 'FixedString';
select 'Bool';
select 'Integers';
select 'Floats';
select 'Decimals';
select 'Dates and DateTimes';
select 'UUID';
select 'IPv4';
select 'IPv6';
select 'Enum';
select 'Map';
select 'Tuple';
select 'Array';
select 'LowCardinality';
select 'Nullable';
select 'CSV';
select 'String';
select 'FixedString';
select 'Bool';
select 'Integers';
select 'Floats';
select 'Decimals';
select 'Dates and DateTimes';
select 'UUID';
select 'IPv4';
select 'IPv6';
select 'Enum';
select 'Map';
select 'Array';
select 'LowCardinality';
select 'Nullable';
select 'TSV';
select 'String';
select 'FixedString';
select 'Bool';
select 'Integers';
select 'Floats';
select 'Decimals';
select 'Dates and DateTimes';
select 'UUID';
select 'IPv4';
select 'IPv6';
select 'Enum';
select 'Map';
select 'Array';
select 'LowCardinality';
select 'Nullable';
select 'Values';
select 'String';
select 'FixedString';
select 'Bool';
select 'Integers';
select 'Floats';
select 'Decimals';
select 'Dates and DateTimes';
select 'UUID';
select 'IPv4';
select 'IPv6';
select 'Enum';
select 'Map';
select 'Array';
select 'LowCardinality';
select 'Nullable';
select '';