select i from a where _part_offset >= 5 order by i settings max_bytes_to_read = 1;
select i from a where _part_offset = 0 order by i settings max_rows_to_read = 2;
select i from a where _part_offset = 1 order by i settings max_rows_to_read = 2;
select i from a where _part_offset = 2 order by i settings max_rows_to_read = 2;
select i from a where _part_offset = 3 order by i settings max_rows_to_read = 2;
select i from a where _part_offset = 4 order by i settings max_rows_to_read = 1;
select i from a where _part_offset in (1, 4) order by i settings max_rows_to_read = 3;
select i from a where _part_offset not in (1, 4) order by i settings max_rows_to_read = 4;
drop table a;
drop table if exists b;
create table b (i int) engine MergeTree order by tuple() settings index_granularity = 2;
insert into b select number * 10 from numbers(5);
insert into b select number * 100 from numbers(5);
select i from b where (_part = 'all_1_1_0' and _part_offset in (1, 4)) or (_part = 'all_2_2_0' and _part_offset in (0, 4)) order by i settings max_rows_to_read = 6;
drop table b;
