SELECT '-- Custom settings from system.settings';
SELECT name, value, type FROM system.settings WHERE startsWith(name, 'custom_') ORDER BY name;
SELECT '-- Custom settings via getSetting()';
SELECT '-- Built-in settings';
SET async_insert = false;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = False;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = FALSE;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = 0;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = 1;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = true;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = True;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
SET async_insert = TRUE;
SELECT name, value, type FROM system.settings WHERE name = 'async_insert';
SELECT 'async_insert' AS name, getSetting(name) AS value, toTypeName(value);
