SELECT a, nest.* FROM test1 ARRAY JOIN nest;
SELECT a, n.* FROM test1 ARRAY JOIN nest AS n;
CREATE TEMPORARY TABLE test2 (a String, nest Array(Tuple(x String, y String)));
SELECT a, nest.* FROM test2 ARRAY JOIN nest;
SELECT a, n.* FROM test2 ARRAY JOIN nest AS n;
SELECT 1 AS x, x, x + 1;
SELECT x, x + 1, 1 AS x;
SELECT x, 1 + (2 + (3 AS x));
SELECT '---';
SELECT 123 AS x FROM (SELECT a, x FROM (SELECT 1 AS a, 2 AS b));
SELECT '---';
SELECT 123 AS x, (SELECT x) AS y;
SELECT 123 AS x, 123 IN (SELECT x);
SELECT '---';
WITH 123 AS x SELECT 555 FROM (SELECT a, x FROM (SELECT 1 AS a, 2 AS b));
SELECT '---';
SELECT x FROM (SELECT * FROM (SELECT 99 AS x) AS t);
SELECT '---';
SELECT t.x FROM (SELECT 1 AS x) AS t;
SELECT '---';
SELECT x IN (SELECT 1 AS x) FROM (SELECT 1 AS x);
SELECT '---';
SELECT x + 1 AS x, x FROM (SELECT 1 AS x);
SELECT x, x + 1 AS x FROM (SELECT 1 AS x);
SELECT '---';
SELECT arrayMap(x -> x + 1, [1, 2]);
