PRAGMA enable_verification;
CREATE TABLE test (a INTEGER, b INTEGER);
INSERT INTO test VALUES (11, 22), (12, 21), (13, 22);
CREATE TABLE test2 (a STRING);
INSERT INTO test2 VALUES ('Hello World');
PREPARE v1 AS SELECT * FROM test2 LIMIT 3;
CREATE TABLE integers(i INTEGER);
INSERT INTO integers VALUES (1), (2), (3), (4), (5);
CREATE SEQUENCE seq START 3;
PRAGMA disable_verification;
CREATE SEQUENCE of_seq START 1;
CREATE OR REPLACE TABLE t AS SELECT range x FROM range(10);
PRAGMA enable_verification;
create table t0(c0 int);
insert into t0 values (1), (2), (3), (4), (5), (6), (7);
SELECT a FROM test LIMIT 1;
SELECT a FROM test LIMIT 1.25;
SELECT a FROM test LIMIT 2-1;
EXECUTE v1;
SELECT * FROM integers LIMIT nextval('seq');
SELECT * FROM integers LIMIT nextval('seq');
SELECT * FROM integers as int LIMIT (SELECT MIN(integers.i) FROM integers);
SELECT * FROM integers OFFSET nextval('of_seq');
SELECT * FROM integers OFFSET nextval('of_seq');
SELECT * FROM integers as int OFFSET (SELECT MIN(integers.i) FROM integers);
SELECT * FROM integers as int LIMIT (SELECT MAX(integers.i) FROM integers) OFFSET (SELECT MIN(integers.i) FROM integers);
SELECT * FROM integers as int LIMIT (SELECT max(integers.i) FROM integers where i > 5);
SELECT * FROM integers as int LIMIT (SELECT max(integers.i) FROM integers where i > 5);
SELECT * FROM integers as int LIMIT (SELECT NULL);
SELECT * FROM t ORDER BY x;
SELECT * FROM t ORDER BY x OFFSET 5;
SELECT * FROM t ORDER BY x OFFSET (SELECT 5);
SELECT * FROM t ORDER BY x LIMIT (SELECT 5);
SELECT * FROM t ORDER BY x LIMIT (SELECT 3) OFFSET (SELECT 3);
SELECT * FROM t ORDER BY x LIMIT 3 OFFSET (SELECT 3);
SELECT * FROM t ORDER BY x LIMIT (SELECT 3) OFFSET 3;
SELECT * FROM t0 ORDER BY ALL OFFSET (SELECT DISTINCT 6.5 FROM (SELECT 1) t1(c0) UNION ALL SELECT 3);
