CREATE TABLE sequence_test_table (a int);
DROP TABLE sequence_test_table;
CREATE SEQUENCE sequence_test5 AS integer;
CREATE SEQUENCE sequence_test6 AS smallint;
CREATE SEQUENCE sequence_test7 AS bigint;
CREATE SEQUENCE sequence_test8 AS integer MAXVALUE 100000;
CREATE SEQUENCE sequence_test9 AS integer INCREMENT BY -1;
CREATE SEQUENCE sequence_test10 AS integer MINVALUE -100000 START 1;
CREATE SEQUENCE sequence_test11 AS smallint;
CREATE SEQUENCE sequence_test12 AS smallint INCREMENT -1;
CREATE SEQUENCE sequence_test13 AS smallint MINVALUE -32768;
CREATE SEQUENCE sequence_test14 AS smallint MAXVALUE 32767 INCREMENT -1;
ALTER SEQUENCE sequence_test5 AS smallint;
ALTER SEQUENCE sequence_test8 AS smallint MAXVALUE 20000;
ALTER SEQUENCE sequence_test9 AS smallint;
ALTER SEQUENCE sequence_test10 AS smallint MINVALUE -20000;
ALTER SEQUENCE sequence_test11 AS int;
ALTER SEQUENCE sequence_test12 AS int;
ALTER SEQUENCE sequence_test13 AS int;
ALTER SEQUENCE sequence_test14 AS int;
CREATE TABLE serialTest1 (f1 text, f2 serial);
INSERT INTO serialTest1 VALUES ('foo');
INSERT INTO serialTest1 VALUES ('bar');
INSERT INTO serialTest1 VALUES ('force', 100);
