SET extra_float_digits = 0;
CREATE TABLE base_tbl (a int PRIMARY KEY, b text DEFAULT 'Unspecified');
INSERT INTO base_tbl SELECT i, 'Row ' || i FROM generate_series(-2, 2) g(i);
CREATE VIEW ro_view1 AS SELECT DISTINCT a, b FROM base_tbl;
CREATE VIEW ro_view2 AS SELECT a, b FROM base_tbl GROUP BY a, b;
CREATE VIEW ro_view3 AS SELECT 1 FROM base_tbl HAVING max(a) > 0;
CREATE VIEW ro_view4 AS SELECT count(*) FROM base_tbl;
CREATE VIEW ro_view5 AS SELECT a, rank() OVER() FROM base_tbl;
CREATE VIEW ro_view6 AS SELECT a, b FROM base_tbl UNION SELECT -a, b FROM base_tbl;
CREATE VIEW ro_view7 AS WITH t AS (SELECT a, b FROM base_tbl) SELECT * FROM t;
CREATE VIEW ro_view8 AS SELECT a, b FROM base_tbl ORDER BY a OFFSET 1;
CREATE VIEW ro_view9 AS SELECT a, b FROM base_tbl ORDER BY a LIMIT 1;
CREATE VIEW ro_view10 AS SELECT 1 AS a;
CREATE VIEW ro_view11 AS SELECT b1.a, b2.b FROM base_tbl b1, base_tbl b2;
CREATE VIEW ro_view12 AS SELECT * FROM generate_series(1, 10) AS g(a);
CREATE VIEW ro_view13 AS SELECT a, b FROM (SELECT * FROM base_tbl) AS t;
CREATE VIEW rw_view14 AS SELECT ctid, a, b FROM base_tbl;
CREATE VIEW rw_view15 AS SELECT a, upper(b) FROM base_tbl;
CREATE VIEW rw_view16 AS SELECT a, b, a AS aa FROM base_tbl;
CREATE VIEW ro_view17 AS SELECT * FROM ro_view1;
CREATE VIEW ro_view18 AS SELECT * FROM (VALUES(1)) AS tmp(a);
CREATE SEQUENCE uv_seq;
CREATE VIEW ro_view19 AS SELECT * FROM uv_seq;
CREATE VIEW ro_view20 AS SELECT a, b, generate_series(1, a) g FROM base_tbl;
