SELECT CURRENT_SETTING('search_path');
SELECT CURRENT_SETTING('schema');
SET SEARCH_PATH = 'test';
SET SEARCH_PATH = 'test,test2';
SET SEARCH_PATH = '"test","test2"';
SET SEARCH_PATH = '"test","test2"';
SET SCHEMA = 'test';
SET SEARCH_PATH = 'test,test2';
SET SCHEMA = 'test';
SET schema = 'test2';
SET search_path = 'test3';
SET SEARCH_PATH = 'test,test2';
SELECT i FROM test_table;
SELECT i FROM test2_table;
SELECT i FROM main_table;
CREATE TABLE main.table_with_same_name(in_main INTEGER);
CREATE TABLE test.table_with_same_name(in_test INTEGER);
CREATE TABLE test2.table_with_same_name(in_test2 INTEGER);
SELECT in_test FROM table_with_same_name;
SET SEARCH_PATH = 'test,test2,test3,test4,test5';
SELECT i FROM test5_table;
SELECT i FROM test_table;
SELECT i FROM test2_table;
SELECT i FROM main_table;
SET SEARCH_PATH = 'test,test,test2';
SELECT i FROM test_table;
SELECT i FROM test2_table;
SELECT i FROM main_table;
SET schema = 'test';
SET schema = 'test2';
SELECT i FROM test2_table;
SELECT i FROM test2_table;
SELECT MAIN.CURRENT_SETTING('search_path');
SELECT MAIN.CURRENT_SCHEMAS(false);
SELECT pg_catalog.CURRENT_SCHEMAS(false);
SELECT MAIN.CURRENT_SETTING('search_path');
SELECT MAIN.CURRENT_SCHEMA();
SELECT pg_catalog.CURRENT_SCHEMA();
SELECT current_schema();
SELECT current_schemas(true);
SELECT current_schemas(false);
SELECT CURRENT_SETTING('search_path');
SELECT CURRENT_SETTING('search_path');
