PRAGMA enable_verification;
SELECT * FROM duckdb_databases();;
ATTACH '__TEST_DIR__/duckdb_databases.db' AS new_duckdb_database;
DETACH new_duckdb_database;;
ATTACH '__TEST_DIR__/duckdb_databases.db' AS readonly_duckdb_database (READONLY 1);;
SELECT database_name, internal, readonly, path, type FROM duckdb_databases() ORDER BY database_name;;
SELECT database_name, internal, split(replace(path, '\', '/'), '/')[-1], type FROM duckdb_databases() WHERE path IS NOT NULL;;
SELECT readonly FROM duckdb_databases WHERE database_name='new_duckdb_database';;
SELECT database_name FROM duckdb_databases ORDER BY database_name;
SHOW databases;
SELECT datname FROM pg_catalog.pg_database ORDER BY 1;
SELECT readonly FROM duckdb_databases WHERE database_name='readonly_duckdb_database';;
