PRAGMA enable_verification;
CREATE TABLE integers AS SELECT 42 i, 84 j UNION ALL SELECT 13, 14;
CREATE TABLE grouped_table AS SELECT  1 id, 42 index1, 84 index2 UNION ALL SELECT 2, 13, 14;
SELECT id, MIN(COLUMNS('xxx')) FROM grouped_table GROUP BY all;
SELECT MIN(COLUMNS('xxx')) FROM grouped_table;
SELECT MIN(COLUMNS('[asdadd')) FROM grouped_table;
SELECT COLUMNS(*) + COLUMNS(* EXCLUDE(j)) FROM integers;
SELECT (SELECT COLUMNS(*)) FROM integers;
SELECT COLUMNS(*) FROM integers;
SELECT MIN(COLUMNS(*)), MAX(COLUMNS(*)) FROM integers;
SELECT MIN(COLUMNS(* EXCLUDE (j))), MAX(COLUMNS(* EXCLUDE (i))) FROM integers;
SELECT MIN(COLUMNS(* REPLACE (i+j AS i))) FROM integers;
SELECT COLUMNS(*) + 1 FROM integers;
SELECT COLUMNS(*) + COLUMNS(*) FROM integers;
SELECT id, MIN(COLUMNS('index[0-9]')) FROM grouped_table GROUP BY all ORDER BY ALL;
SELECT id, MIN(COLUMNS('[0-9]')) FROM grouped_table GROUP BY all ORDER BY ALL;
SELECT * FROM grouped_table ORDER BY COLUMNS('index[0-9]');;
SELECT * FROM grouped_table ORDER BY COLUMNS(*);;
