PRAGMA enable_verification;
CREATE TABLE tbl(col1 INTEGER, col2 INTEGER, col3 INTEGER);
INSERT INTO tbl VALUES (1, 200, 10), (2, 100, 20), (3, 200, 0);
SELECT * FROM tbl WHERE COLUMNS(*) >= 2 ORDER BY ALL;
SELECT * FROM tbl WHERE COLUMNS(['col1', 'col2']) >= 2 ORDER BY ALL;
SELECT * FROM tbl WHERE COLUMNS(['col1', 'col2']) >= 2 AND COLUMNS(*) IS NOT NULL ORDER BY ALL;
SELECT * FROM tbl WHERE COLUMNS(['col1', 'col2']) >= 2 AND COLUMNS(['col1', 'col3']) < 10 ORDER BY ALL;
