CREATE TABLE integers(i INTEGER);
CREATE TABLE pk(i INTEGER PRIMARY KEY, j VARCHAR, CHECK(i<100));
CREATE SCHEMA myschema;
CREATE TABLE myschema.mytable(k DOUBLE);
CREATE TEMPORARY TABLE mytemp(i INTEGER);
CREATE VIEW v1 AS SELECT 42;
