SELECT COUNT(*) FROM integers_empty JOIN integers2 USING (i);
SELECT COUNT(*) FROM integers_empty JOIN integers2 ON (integers_empty.i>integers2.i);
SELECT COUNT(*) FROM integers_empty JOIN integers2 ON (integers_empty.i<>integers2.i);
SELECT COUNT(*) FROM integers_empty JOIN integers2 ON (integers_empty.i<>integers2.i OR integers_empty.i+1<>integers2.i);
SELECT * FROM integers_empty JOIN integers2 USING (i);
SELECT COUNT(*) FROM integers_empty LEFT JOIN integers2 USING (i);
SELECT * FROM integers_empty LEFT JOIN integers2 USING (i);
SELECT COUNT(*) FROM integers_empty RIGHT JOIN integers2 USING (i);
SELECT COUNT(*) FROM integers_empty FULL OUTER JOIN integers2 USING (i);
SELECT COUNT(*) FROM integers JOIN integers2_empty USING (i);
SELECT * FROM integers JOIN integers2_empty USING (i);
SELECT COUNT(*) FROM integers LEFT JOIN integers2_empty USING (i);
SELECT COUNT(*) FROM integers RIGHT JOIN integers2_empty USING (i);
SELECT * FROM integers RIGHT JOIN integers2_empty USING (i);
SELECT COUNT(*) FROM integers FULL OUTER JOIN integers2_empty USING (i);
SELECT integers.*, integers2_empty.* FROM integers FULL OUTER JOIN integers2_empty USING (i);
SELECT COUNT(*) FROM integers JOIN empty_join USING (i);
SELECT COUNT(*) FROM integers LEFT JOIN empty_join USING (i);
SELECT COUNT(*) FROM integers RIGHT JOIN empty_join USING (i);
SELECT COUNT(*) FROM integers FULL OUTER JOIN empty_join USING (i);
