PRAGMA enable_verification;
CREATE TABLE integers(i INTEGER PRIMARY KEY);
INSERT INTO integers VALUES (1);
BEGIN TRANSACTION;
INSERT INTO integers SELECT i FROM range(2, 131068, 1) t1(i);
ROLLBACK;
INSERT INTO integers VALUES (2);
INSERT INTO integers VALUES (3);
INSERT INTO integers VALUES (4);
