PRAGMA enable_verification;
CREATE TABLE integers(i integer);
INSERT INTO integers VALUES (1), (2), (3), (NULL);
SET default_null_order='nulls_first';
SET default_null_order='sqlite';
SET default_null_order='postgres';
SELECT * FROM integers ORDER BY i;
SELECT * FROM integers ORDER BY i DESC;
SELECT FIRST(i ORDER BY i), LAST(i ORDER BY i) FROM integers;
SELECT FIRST(i ORDER BY i DESC), LAST(i ORDER BY i DESC) FROM integers;
SELECT list_sort(LIST(i)), list_reverse_sort(LIST(i)) FROM integers;
SELECT * FROM integers ORDER BY i;
SELECT * FROM integers ORDER BY i DESC;
SELECT FIRST(i ORDER BY i), LAST(i ORDER BY i) FROM integers;
SELECT FIRST(i ORDER BY i DESC), LAST(i ORDER BY i DESC) FROM integers;
SELECT list_sort(LIST(i)), list_reverse_sort(LIST(i)) FROM integers;
SELECT * FROM integers ORDER BY i;
SELECT * FROM integers ORDER BY i DESC;
SELECT FIRST(i ORDER BY i), LAST(i ORDER BY i) FROM integers;
SELECT FIRST(i ORDER BY i DESC), LAST(i ORDER BY i DESC) FROM integers;
SELECT list_sort(LIST(i)), list_reverse_sort(LIST(i)) FROM integers;
