CREATE TABLE "MyTable"(i integer, "BigColumn" integer);
ALTER TABLE MyTable ALTER BIGCOLUMN SET DATA TYPE VARCHAR;
ALTER TABLE MyTable DROP COLUMN BIGCOLUMN;
ALTER TABLE MyTable ADD COLUMN "BIGCOLUMN" VARCHAR;
ALTER TABLE MyTable ALTER COLUMN BIGCOLUMN SET DEFAULT 3;
INSERT INTO MyTable(BIGCOLUMN) VALUES (DEFAULT);
ALTER TABLE MyTable ALTER COLUMN BIGCOLUMN DROP DEFAULT;
