PRAGMA enable_verification;
CREATE TABLE test (a INTEGER PRIMARY KEY, b INTEGER, c VARCHAR);;
INSERT INTO test VALUES (11, 22, 'hello'), (13, 22, 'world'), (12, 21, 'test'), (10, NULL, NULL);;
BEGIN TRANSACTION;
BEGIN TRANSACTION;
INSERT INTO test VALUES (14, 10, 'con');
INSERT INTO test SELECT i, NULL, NULL FROM range(15, 10000) tbl(i);;
INSERT INTO test VALUES (14, 10, 'con2');
COMMIT;
COMMIT;
INSERT INTO test VALUES (15, NULL, NULL);
INSERT INTO test VALUES (16, 24, 'blabla');
PRAGMA enable_verification;
SELECT * FROM test ORDER BY a, b, c;
SELECT * FROM test ORDER BY a, b, c;
SELECT * FROM test ORDER BY a, b, c;
SELECT * FROM test ORDER BY a, b, c;
