CREATE TABLE TBL (id INT NOT NULL, age INT NOT NULL, PRIMARY KEY ( id ));
INSERT INTO TBL VALUES (1, 1);
DELETE FROM TBL WHERE id = 1;
INSERT INTO TBL VALUES (1, 1);
SELECT * FROM TBL;
SELECT * FROM TBL WHERE id=1;
SELECT * FROM TBL;
SELECT * FROM TBL WHERE id=1;
