SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers WHERE i=1;
SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers WHERE i=1;
SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers WHERE i=1;
SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers;
SELECT COUNT(*) FROM integers;
SELECT * FROM integers;
