PRAGMA synchronous = NORMAL;
PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = wal;
BEGIN;
CREATE TABLE t1(a PRIMARY KEY, b);
INSERT INTO t1 VALUES('I', 'one');
SELECT * FROM t1;
PRAGMA main.journal_mode;
PRAGMA integrity_check;
VACUUM;
PRAGMA main.journal_mode;
PRAGMA wal_checkpoint;
CREATE TABLE t2(a, b);
INSERT INTO t2 SELECT * FROM t1;
DROP TABLE t1;
VACUUM;
PRAGMA wal_checkpoint;
PRAGMA journal_mode = WAL;
PRAGMA cache_size = 10;
PRAGMA cache_size = 10;
CREATE TABLE t1(a, b);
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t1 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t1 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t1 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
INSERT INTO t1 VALUES(1, 2);
INSERT INTO t1 VALUES(3, 4);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t1 VALUES(5, 6);
INSERT INTO t1 VALUES(7, 8);
SELECT * FROM t1;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
PRAGMA journal_mode;
PRAGMA wal_checkpoint;
PRAGMA journal_mode;
PRAGMA journal_mode;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
PRAGMA journal_mode;
SELECT * FROM t1;
PRAGMA journal_mode;
PRAGMA journal_mode;
