BEGIN;
CREATE TABLE t1(w int, x int, y int, z int);
CREATE UNIQUE INDEX i1w ON t1(w);
CREATE INDEX i1xy ON t1(x,y);
CREATE INDEX i1zyx ON t1(z,y,x);
SELECT * FROM t1 WHERE w BETWEEN 5 AND 6 ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE w BETWEEN 5 AND 6 ORDER BY +w;
SELECT * FROM t1 WHERE +w BETWEEN 5 AND 6 ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE +w BETWEEN 5 AND 6 ORDER BY +w;
SELECT * FROM t1 WHERE w BETWEEN 5 AND 65-y ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE w BETWEEN 5 AND 65-y ORDER BY +w;
SELECT * FROM t1 WHERE +w BETWEEN 5 AND 65-y ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE +w BETWEEN 5 AND 65-y ORDER BY +w;
SELECT * FROM t1 WHERE w BETWEEN 41-y AND 6 ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE w BETWEEN 41-y AND 6 ORDER BY +w;
SELECT * FROM t1 WHERE +w BETWEEN 41-y AND 6 ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE +w BETWEEN 41-y AND 6 ORDER BY +w;
SELECT * FROM t1 WHERE w BETWEEN 41-y AND 65-y ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE w BETWEEN 41-y AND 65-y ORDER BY +w;
SELECT * FROM t1 WHERE 26 BETWEEN y AND z ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE 26 BETWEEN y AND z ORDER BY +w;
SELECT * FROM t1 WHERE 26 BETWEEN +y AND z ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE 26 BETWEEN +y AND z ORDER BY +w;
SELECT * FROM t1 WHERE 26 BETWEEN y AND +z ORDER BY +w;
EXPLAIN QUERY PLAN 
    SELECT * FROM t1 WHERE 26 BETWEEN y AND +z ORDER BY +w;
SELECT x                BETWEEN 1 AND '5' FROM t1;
SELECT x COLLATE binary BETWEEN 1 AND '5' FROM t1;
SELECT x COLLATE nocase BETWEEN 1 AND '5' FROM t1;
SELECT y                  BETWEEN 'A' AND 'B' FROM t1;
SELECT y COLLATE nocase   BETWEEN 'A' AND 'B' FROM t1;
SELECT y COLLATE binary   BETWEEN 'A' AND 'B' FROM t1;
SELECT (y COLLATE binary) BETWEEN 'A' AND 'B' FROM t1;
