PRAGMA main.synchronous = NORMAL;
PRAGMA main.synchronous;
INSERT INTO t1 VALUES(5, 6);
PRAGMA main.synchronous = OFF;
PRAGMA main.synchronous;
INSERT INTO t1 VALUES(7, 8);
PRAGMA main.synchronous = FULL;
PRAGMA main.synchronous;
INSERT INTO t1 VALUES(9, 10);
PRAGMA journal_mode = wal;
INSERT INTO t1 VALUES(11, 12);
INSERT INTO t1 VALUES(13, 14);
PRAGMA main.synchronous = NORMAL;
PRAGMA main.synchronous;
INSERT INTO t1 VALUES(15, 16);
PRAGMA wal_checkpoint;
PRAGMA main.synchronous = OFF;
PRAGMA main.synchronous;
INSERT INTO t1 VALUES(17, 18);
