CREATE TABLE t1(a,b);
INSERT INTO t1 VALUES(1,2);
CREATE TABLE [t1'x1](c UNIQUE, b PRIMARY KEY);
INSERT INTO [t1'x1] VALUES(3,4);
CREATE INDEX t1i1 ON T1(B);
CREATE INDEX t1i2 ON t1(a,b);
CREATE INDEX i3 ON [t1'x1](b,c);
CREATE TEMP TABLE "temp table"(e,f,g UNIQUE);
CREATE INDEX i2 ON [temp table](f);
INSERT INTO [temp table] VALUES(5,6,7);
SELECT 't1', * FROM t1;
SELECT 't1''x1', * FROM "t1'x1";
SELECT * FROM [temp table];
CREATE TEMP TABLE objlist(type, name, tbl_name);
INSERT INTO objlist SELECT type, name, tbl_name 
        FROM sqlite_master WHERE NAME!='objlist';
INSERT INTO objlist SELECT type, name, tbl_name 
          FROM temp.sqlite_master WHERE NAME!='objlist';
SELECT type, name, tbl_name FROM objlist ORDER BY tbl_name, type desc, name;
PRAGMA integrity_check;
ALTER TABLE [T1] RENAME to [-t1-];
ALTER TABLE "t1'x1" RENAME TO T2;
ALTER TABLE [temp table] RENAME to TempTab;
PRAGMA integrity_check;
SELECT 't1', * FROM [-t1-];
SELECT 't2', * FROM t2;
SELECT * FROM temptab;
DELETE FROM objlist;
INSERT INTO objlist SELECT type, name, tbl_name
        FROM sqlite_master WHERE NAME!='objlist';
INSERT INTO objlist SELECT type, name, tbl_name 
        FROM sqlite_temp_master WHERE NAME!='objlist';
SELECT type, name, tbl_name FROM objlist ORDER BY tbl_name, type desc, name;
INSERT INTO objlist SELECT type, name, tbl_name FROM sqlite_master;
INSERT INTO objlist 
          SELECT type, name, tbl_name FROM temp.sqlite_master 
          WHERE NAME!='objlist';
SELECT type, name, tbl_name FROM objlist 
          ORDER BY tbl_name, type desc, name;
SELECT substr(name,1,3) FROM sqlite_master;
DELETE FROM objlist;
INSERT INTO objlist SELECT type, name, tbl_name
        FROM sqlite_master WHERE NAME!='objlist';
INSERT INTO objlist SELECT type, name, tbl_name 
        FROM sqlite_temp_master WHERE NAME!='objlist';
SELECT type, name, tbl_name FROM objlist ORDER BY tbl_name, type desc, name;
ATTACH 'test2.db' AS aux;
CREATE TABLE t4(a PRIMARY KEY, b, c);
CREATE INDEX i4 ON t4(b);
CREATE INDEX aux.i4 ON t4(b);
INSERT INTO t4 VALUES('main', 'main', 'main');
INSERT INTO aux.t4 VALUES('aux', 'aux', 'aux');
SELECT * FROM t4 WHERE a = 'main';
ALTER TABLE t4 RENAME TO t5;
SELECT * FROM t4 WHERE a = 'aux';
SELECT * FROM t5;
SELECT * FROM t5 WHERE b = 'main';
ALTER TABLE aux.t4 RENAME TO t5;
SELECT * FROM aux.t5 WHERE b = 'aux';
CREATE TABLE tbl1   (a, b, c);
INSERT INTO tbl1 VALUES(1, 2, 3);
SELECT * FROM tbl1;
ALTER TABLE tbl1 RENAME TO tbl2;
SELECT * FROM tbl2;
DROP TABLE tbl2;
CREATE TABLE t3(p,q,r);
CREATE TABLE t6(a, b, c);
INSERT INTO t6 VALUES(1, 2, 3);
ALTER TABLE t6 RENAME TO t7;
INSERT INTO t7 VALUES(4, 5, 6);
INSERT INTO t7 VALUES(1, 2, 3);
ALTER TABLE t7 RENAME TO t8;
INSERT INTO t8 VALUES(4, 5, 6);
INSERT INTO t8 VALUES(1, 2, 3);
ALTER TABLE t8 RENAME TO t9;
INSERT INTO t9 VALUES(4, 5, 6);
ATTACH 'test3.db' AS 'ON';
CREATE TABLE 'ON'.t1(a, b, c);
CREATE TABLE 'ON'.'ON'(a, b, c);
CREATE TABLE t10(a, 'ON', c);
DROP TABLE t10;
CREATE TABLE tbl1(a, b, c);
INSERT INTO tbl1 VALUES('a', 'b', 'c');
ALTER TABLE tbl1 RENAME TO tbl2;
INSERT INTO tbl2 VALUES('d', 'e', 'f');
ALTER TABLE tbl2 RENAME TO tbl3;
INSERT INTO tbl3 VALUES('g', 'h', 'i');
UPDATE tbl3 SET a = 'G' where a = 'g';
DROP TABLE tbl3;
SELECT * FROM temp.sqlite_master WHERE type = 'trigger';
CREATE TABLE tbl1(a INTEGER PRIMARY KEY AUTOINCREMENT);
INSERT INTO tbl1 VALUES(10);
INSERT INTO tbl1 VALUES(NULL);
SELECT a FROM tbl1;
ALTER TABLE tbl1 RENAME TO tbl2;
DELETE FROM tbl2;
INSERT INTO tbl2 VALUES(NULL);
SELECT a FROM tbl2;
DROP TABLE tbl2;
CREATE TABLE tbl1(a, b, c);
INSERT INTO tbl1 VALUES('x', 'y', 'z');
ALTER TABLE tbl1 RENAME TO tbl2;
SELECT * FROM tbl2;
SELECT name FROM sqlite_master
   WHERE type='table' AND name NOT GLOB 'sqlite*';
DROP TABLE "t5";
DROP TABLE "t3";
DROP TABLE "t9";
DROP TABLE "tbl2";
CREATE TABLE abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef(a, b, c);
SELECT max(oid) FROM sqlite_master;
SELECT sql FROM sqlite_master WHERE oid = 16;
SELECT * FROM abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef;
ALTER TABLE abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef RENAME TO abcXdef;
SELECT sql FROM sqlite_master WHERE oid = 16;
ALTER TABLE abcXdef RENAME TO abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef;
SELECT sql FROM sqlite_master WHERE oid = 16;
ALTER TABLE abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef ADD COLUMN ghiS4jkl VARCHAR;
SELECT sql FROM sqlite_master WHERE oid = 16;
ALTER TABLE abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef ADD COLUMN BÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢1A;
SELECT sql FROM sqlite_master WHERE oid = 16;
INSERT INTO abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef VALUES(1, 2, 3, 4, 5);
SELECT ghiS4jkl, BÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ¢1A FROM abcÃÂÃÂÃÂÃÂªÃÂÃÂÃÂÃÂ¯ÃÂÃÂÃÂÃÂdef;
CREATE TABLE t1(a TEXT COLLATE BINARY);
ALTER TABLE t1 ADD COLUMN b INTEGER COLLATE NOCASE;
INSERT INTO t1 VALUES(1,'-2');
INSERT INTO t1 VALUES(5.4e-08,'5.4e-08');
SELECT typeof(a), a, typeof(b), b FROM t1;
SELECT sum(b) FROM t2;
CREATE TABLE xyz(x UNIQUE);
ALTER TABLE xyz RENAME TO xyzÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´abc;
SELECT name FROM sqlite_master WHERE name GLOB 'xyz*';
SELECT name FROM sqlite_master WHERE name GLOB 'sqlite_autoindex*';
ALTER TABLE xyzÃÂÃÂÃÂÃÂ¡ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ´abc RENAME TO xyzabc;
SELECT name FROM sqlite_master WHERE name GLOB 'xyz*';
SELECT name FROM sqlite_master WHERE name GLOB 'sqlite_autoindex*';
CREATE TABLE t12(a, b, c);
CREATE VIEW v1 AS SELECT * FROM t12;
SELECT * FROM v1;
SELECT * FROM v1;
CREATE TABLE /* hi */ t3102a(x);
CREATE TABLE t3102b -- comment
    (y);
CREATE INDEX t3102c ON t3102a(x);
SELECT name FROM sqlite_master WHERE name GLOB 't3102*' ORDER BY 1;
ALTER TABLE t3102a RENAME TO t3102a_rename;
SELECT name FROM sqlite_master WHERE name GLOB 't3102*' ORDER BY 1;
ALTER TABLE t3102b RENAME TO t3102b_rename;
SELECT name FROM sqlite_master WHERE name GLOB 't3102*' ORDER BY 1;
CREATE TABLE t3651(a UNIQUE);
INSERT INTO t3651 VALUES(5);
ANALYZE;
CREATE TABLE t16a(a TEXT, b REAL, c INT, PRIMARY KEY(a,b)) WITHOUT rowid;
INSERT INTO t16a VALUES('abc',1.25,99);
ALTER TABLE t16a ADD COLUMN d TEXT DEFAULT 'xyzzy';
INSERT INTO t16a VALUES('cba',5.5,98,'fizzle');
SELECT * FROM t16a ORDER BY a;
ALTER TABLE t16a RENAME TO t16a_rn;
SELECT * FROM t16a_rn ORDER BY a;
CREATE TABLE log(a INTEGER PRIMARY KEY,b,c);
ALTER TABLE log RENAME COLUMN a TO x;
ALTER TABLE t2 RENAME TO t3;
SELECT name FROM sqlite_schema WHERE sql LIKE '%t2%';
SELECT name FROM sqlite_schema WHERE sql LIKE '%t3%' ORDER BY name;
INSERT INTO t1(a) VALUES(45);
DELETE FROM t1;
INSERT INTO t1(a) VALUES(45);
CREATE TABLE t2(a,b,c,d,x);
ALTER TABLE t2 RENAME TO e;
SELECT name, type FROM sqlite_schema ORDER BY name;
ALTER TABLE e RENAME TO t99;
SELECT name, type FROM sqlite_schema ORDER BY name;
