PRAGMA freelist_count;
CREATE TABLE abc(a, b, c);
PRAGMA freelist_count;
DROP TABLE abc;
PRAGMA freelist_count;
PRAGMA main.freelist_count;
ATTACH 'test2.db' AS aux;
PRAGMA aux.auto_vacuum=OFF;
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
PRAGMA main.freelist_count;
PRAGMA freelist_count;
PRAGMA freelist_count = 500;
PRAGMA freelist_count;
PRAGMA aux.freelist_count = 500;
PRAGMA aux.freelist_count;
PRAGMA main.cache_size=2000;
PRAGMA temp.cache_size=2000;
PRAGMA cache_spill;
PRAGMA main.cache_spill;
PRAGMA temp.cache_spill;
PRAGMA cache_spill=OFF;
PRAGMA cache_spill;
PRAGMA main.cache_spill;
PRAGMA temp.cache_spill;
PRAGMA page_size=1024;
PRAGMA cache_size=50;
BEGIN;
CREATE TABLE t1(a INTEGER PRIMARY KEY, b, c, d);
INSERT INTO t1 VALUES(1, randomblob(400), 1, randomblob(400));
INSERT INTO t1 SELECT a+1, randomblob(400), a+1, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+2, randomblob(400), a+2, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+4, randomblob(400), a+4, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+8, randomblob(400), a+8, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+16, randomblob(400), a+16, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+32, randomblob(400), a+32, randomblob(400) FROM t1;
INSERT INTO t1 SELECT a+64, randomblob(400), a+64, randomblob(400) FROM t1;
ATTACH 'test2.db' AS aux1;
DETACH aux1;
PRAGMA cache_spill=ON;
PRAGMA cache_spill=OFF;
ATTACH 'test2.db' AS aux1;
PRAGMA aux1.cache_size=50;
BEGIN;
PRAGMA lock_status;
PRAGMA cache_spill=ON;
-- Applies to all databases
  BEGIN;
PRAGMA lock_status;
PRAGMA page_size=16384;
PRAGMA cache_size=2;
PRAGMA cache_spill=YES;
PRAGMA cache_spill;
PRAGMA cache_spill=NO;
PRAGMA cache_spill;
PRAGMA cache_spill(-51);
PRAGMA cache_spill;
