PRAGMA auto_vacuum = 0;
PRAGMA page_size=4096;
CREATE TABLE t1(a,b);
WITH RECURSIVE c(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM c WHERE x<20)
    INSERT INTO t1(a,b) SELECT x, randomblob(300) FROM c;
CREATE INDEX t1a ON t1(a);
CREATE INDEX t1b ON t1(b);
SELECT sum(a), sum(length(b)) FROM t1;
PRAGMA integrity_check;
PRAGMA journal_mode;
PRAGMA page_count;
SELECT sum(a), sum(length(b)) FROM t1;
PRAGMA integrity_check;
PRAGMA journal_mode;
PRAGMA page_count;
PRAGMA quick_check;
PRAGMA quick_check;
PRAGMA page_count;
PRAGMA page_size;
PRAGMA quick_check;
PRAGMA journal_mode;
PRAGMA auto_vacuum = 0;
PRAGMA page_size=8192;
PRAGMA journal_mode=WAL;
WITH RECURSIVE c(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM c WHERE x<20)
    INSERT INTO t1(a,b) SELECT x, randomblob(1300) FROM c;
SELECT sum(a), sum(length(b)) FROM t1;
PRAGMA integrity_check;
PRAGMA journal_mode;
PRAGMA page_size;
PRAGMA page_count;
SELECT sum(a), sum(length(b)) FROM t1;
PRAGMA integrity_check;
PRAGMA journal_mode;
PRAGMA page_size;
PRAGMA page_count;
PRAGMA quick_check;
PRAGMA quick_check;
PRAGMA page_count;
PRAGMA page_size;
PRAGMA journal_mode;
PRAGMA quick_check;
PRAGMA page_count;
PRAGMA page_size;
PRAGMA journal_mode;
PRAGMA quick_check;
PRAGMA journal_mode = wal;
SELECT * FROM t1;
SELECT * FROM sqlite_master;
PRAGMA page_size=512;
PRAGMA auto_vacuum = 0;
PRAGMA page_count;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA page_count;
PRAGMA integrity_check;
PRAGMA encoding = 'utf8';
PRAGMA encoding;
CREATE TEMP TABLE t2(x);
INSERT INTO t2 VALUES('hello world');
SELECT name FROM sqlite_schema;
SELECT * FROM t1;
SELECT * FROM t2;
