VACUUM;
CREATE TABLE t1(x);
CREATE TABLE t2(y);
INSERT INTO t1 VALUES(1);
VACUUM;
INSERT INTO t1 VALUES('hello');
INSERT INTO t2 VALUES('out there');
PRAGMA auto_vacuum=FULL;
VACUUM;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA auto_vacuum=NONE;
VACUUM;
PRAGMA integrity_check;
PRAGMA integrity_check;
pragma auto_vacuum=1;
create table t(a, b);
insert into t values(1, 2);
insert into t values(1, 2);
pragma auto_vacuum=0;
vacuum;
pragma auto_vacuum;
pragma auto_vacuum=1;
vacuum;
pragma auto_vacuum;
pragma integrity_check;
pragma auto_vacuum;
pragma auto_vacuum=2;
vacuum;
pragma auto_vacuum;
pragma integrity_check;
pragma auto_vacuum;
VACUUM;
VACUUM;
VACUUM;
PRAGMA integrity_check;
VACUUM;
PRAGMA integrity_check;
