PRAGMA table_info(dbstat);
PRAGMA table_info=dbstat;
PRAGMA auto_vacuum = OFF;
PRAGMA journal_mode = WAL;
PRAGMA journal_mode = delete;
CREATE TABLE t1(a, b);
CREATE INDEX i1 ON t1(b);
INSERT INTO t1(rowid, a, b) VALUES(2, 2, 3);
INSERT INTO t1(rowid, a, b) VALUES(3, 4, 5);
DROP TABLE t1;
CREATE TABLE t3(a PRIMARY KEY, b);
UPDATE t3 SET a=a||hex(randomblob(700));
VACUUM;
DROP TABLE t3;
VACUUM;
CREATE TABLE t4(x);
CREATE INDEX i4 ON t4(x);
CREATE TABLE t5(x);
CREATE INDEX i5 ON t5(x);
PRAGMA auto_vacuum = OFF;
CREATE TABLE tx(y);
ATTACH ':memory:' AS aux1;
CREATE TABLE aux1.t1(x);
INSERT INTO t1 VALUES(zeroblob(1513));
INSERT INTO t1 VALUES(zeroblob(1514));
ATTACH 'test.db2' AS '123';
PRAGMA "123".auto_vacuum = OFF;
CREATE TABLE "123".x1(a, b);
INSERT INTO x1 VALUES(1, 2);
DETACH 123;
ATTACH 'test.db2' AS '123corp';
CREATE TABLE dbstat(x, y);
