CREATE TABLE t2(e INT UNIQUE, f TEXT);
CREATE TABLE t1(a);
INSERT INTO t1 VALUES(0);
CREATE TABLE v0(v1);
CREATE TABLE v3(v5, v4);
INSERT INTO v0 VALUES(0);
CREATE INDEX v9 ON v3(v4, v4, v5);
SELECT quote(v5) FROM v0 LEFT JOIN v3 ON v4 = NULL AND v5 IN(0);
