SELECT * FROM collate6log;
INSERT INTO collate6tab VALUES('A', 'B');
SELECT * FROM collate6log;
DELETE FROM collate6log;
INSERT INTO collate6tab VALUES('a', 'b');
SELECT * FROM collate6log;
INSERT INTO collate6tab VALUES('A', 'B');
SELECT * FROM collate6log;
DELETE FROM collate6log;
DROP TABLE collate6tab;
CREATE TABLE abc(a COLLATE binary, b, c);
CREATE TABLE def(a, b, c);
INSERT INTO abc VALUES('One', 'Two', 'Three');
INSERT INTO abc VALUES('one', 'two', 'three');
SELECT * FROM def;
UPDATE abc SET a = 'four' WHERE a = 'one';
SELECT * FROM def;
SELECT 1 FROM sqlite_master WHERE name COLLATE nocase = 'hello';
SELECT 1 FROM sqlite_master WHERE 'hello' = name COLLATE nocase;
