CREATE TABLE t1(x INTEGER PRIMARY KEY, y);
INSERT INTO t1 VALUES(1, 1);
VACUUM;
CREATE INDEX x1 ON t1(x);
CREATE INDEX x2 ON t1(x);
CREATE INDEX x3 ON t1(x);
INSERT INTO t1 SELECT 2,'';
VACUUM;
vacuum;
PRAGMA integrity_check;
vacuum;
PRAGMA integrity_check;
vacuum;
PRAGMA integrity_check;
PRAGMA page_size = 1024;
PRAGMA page_size = 512;
VACUUM;
PRAGMA integrity_check;
CREATE TABLE tx(a, b);
CREATE INDEX i1 ON tx(b);
WITH s(i) AS (
      SELECT 8000 UNION ALL SELECT i+1 FROM s WHERE i<10000
  )
  INSERT INTO tx SELECT i, randomblob(i) FROM s;
SELECT sum(length(b)) FROM tx;
PRAGMA page_size = 2048;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 65536;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 8192;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 512;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 4096;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
