PRAGMA auto_vacuum=0;
PRAGMA page_size=1024;
CREATE TABLE abc(a, b, c);
SELECT * FROM sqlite_master;
SELECT * FROM sqlite_master;
PRAGMA quick_check;
PRAGMA quick_check;
CREATE INDEX a1 ON abc(a);
CREATE INDEX a2 ON abc(b);
PRAGMA writable_schema = 1;
UPDATE sqlite_master 
      SET name = 'a3', sql = 'CREATE INDEX a3' || substr(sql, 16, 10000)
      WHERE type = 'index';
PRAGMA writable_schema = 0;
SELECT * FROM sqlite_master;
PRAGMA auto_vacuum = 1;
PRAGMA page_size = 1024;
CREATE TABLE t1(a, b, c);
CREATE TABLE t2(a, b, c);
INSERT INTO t2 VALUES(randomblob(100), randomblob(100), randomblob(100));
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
DROP TABLE t1;
SELECT * FROM t2;
PRAGMA auto_vacuum = 0;
PRAGMA page_size = 1024;
CREATE TABLE t1(a, b, c);
INSERT INTO t2 VALUES(randomblob(100), randomblob(100), randomblob(100));
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t2 SELECT * FROM t2;
INSERT INTO t1 SELECT * FROM t2;
pragma incremental_vacuum = 1;
pragma incremental_vacuum = 1;
pragma incremental_vacuum = 1;
BEGIN EXCLUSIVE;
SELECT b FROM t1 ORDER BY b ASC;
SELECT b FROM t1 ORDER BY b DESC;
SELECT * FROM t1 WHERE rowid=1000;
SELECT sql FROM sqlite_master;
SELECT * FROM t2;
PRAGMA incremental_vacuum;
PRAGMA incremental_vacuum;
DELETE FROM t1 WHERE rowid < 30;
PRAGMA auto_vacuum = 0;
DELETE FROM t1;
PRAGMA integrity_check;
PRAGMA freelist_count;
PRAGMA freelist_count;
PRAGMA integrity_check;
PRAGMA freelist_count;
PRAGMA integrity_check;
