SELECT a, b+c FROM t1
  UNION ALL
  SELECT x, 5 FROM t2 JOIN t3 ON z=x WHERE x=2
  ORDER BY a;
SELECT a, b+c+d FROM t1
  UNION ALL
  SELECT x, 5 FROM t2 JOIN t3 ON z=x WHERE x=2
  ORDER BY a;
SELECT a, b+c+d+e FROM t1
  UNION ALL
  SELECT x, 5 FROM t2 JOIN t3 ON z=x WHERE x=2
  ORDER BY a;
