CREATE TABLE blobs(id INTEGER PRIMARY KEY, data BLOB);
INSERT INTO blobs VALUES(NULL, zeroblob(5000));
INSERT INTO blobs VALUES(NULL, zeroblob(5000));
INSERT INTO blobs VALUES(NULL, zeroblob(5000));
INSERT INTO blobs VALUES(NULL, zeroblob(5000));
INSERT INTO blobs VALUES(5, zeroblob(10240));
BEGIN;
PRAGMA read_uncommitted=1;
BEGIN;
CREATE TABLE t3(a INTEGER UNIQUE, b TEXT);
INSERT INTO t3 VALUES(1, 'aaaaaaaaaaaaaaaaaaaa');
INSERT INTO t3 VALUES(2, 'bbbbbbbbbbbbbbbbbbbb');
INSERT INTO t3 VALUES(3, 'cccccccccccccccccccc');
INSERT INTO t3 VALUES(4, 'dddddddddddddddddddd');
INSERT INTO t3 VALUES(5, 'eeeeeeeeeeeeeeeeeeee');
BEGIN;
