CREATE TABLE t1(a PRIMARY KEY, b, c);
INSERT INTO t1 VALUES('one', 'I', 1);
SELECT * FROM t1;
INSERT INTO t1 VALUES('two', 'II', 2);
SELECT * FROM t1;
INSERT INTO t1 VALUES('three','III',3);
INSERT INTO t1 VALUES('four','IV',4);
INSERT INTO t1 VALUES('five','V',5);
SELECT * FROM t1;
SELECT * FROM t1 WHERE a = 'one';
SELECT * FROM t1 WHERE a = 'four';
SELECT * FROM t1 WHERE a IN ('one', 'two');
VACUUM;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1 WHERE a = 'one';
SELECT * FROM t1 WHERE a = 'four';
SELECT * FROM t1 WHERE a IN ('one', 'two');
VACUUM;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1 WHERE a = 'one';
SELECT * FROM t1 WHERE a = 'four';
SELECT * FROM t1 WHERE a IN ('one', 'two');
VACUUM;
ATTACH 'test2.db' as aux;
CREATE TABLE t5(a);
INSERT INTO t5 VALUES('one');
INSERT INTO t5 VALUES('two');
INSERT INTO t5 VALUES('five');
INSERT INTO t5 VALUES('three');
INSERT INTO t5 VALUES('four');
pragma encoding = 'UTF-16LE';
INSERT INTO t5 VALUES('one');
INSERT INTO t5 VALUES('two');
INSERT INTO t5 VALUES('five');
INSERT INTO t5 VALUES('three');
INSERT INTO t5 VALUES('four');
pragma encoding = 'UTF-16BE';
INSERT INTO t5 VALUES('one');
INSERT INTO t5 VALUES('two');
INSERT INTO t5 VALUES('five');
INSERT INTO t5 VALUES('three');
INSERT INTO t5 VALUES('four');
pragma encoding = 'UTF-8';
INSERT INTO t5 VALUES('one');
pragma encoding = 'UTF-16LE';
INSERT INTO t5 VALUES('sqlite');
pragma encoding = 'UTF-16BE';
INSERT INTO t5 VALUES('sqlite');
PRAGMA encoding = 'UTF-16';
SELECT * FROM sqlite_master;
PRAGMA encoding;
PRAGMA encoding = 'UTF-8';
CREATE TABLE abc(a, b, c);
SELECT * FROM sqlite_master;
PRAGMA encoding;
PRAGMA encoding = 'UTF-8';
PRAGMA encoding;
PRAGMA encoding = 'UTF-16le';
PRAGMA encoding;
SELECT * FROM sqlite_master;
PRAGMA encoding = 'UTF-8';
PRAGMA encoding;
PRAGMA encoding = 'UTF-16le';
PRAGMA encoding;
PRAGMA encoding = 'UTF-8';
PRAGMA encoding;
PRAGMA encoding=UTF8;
CREATE TEMP TABLE t1(x);
INSERT INTO t1 VALUES('this is a test');
PRAGMA encoding=UTF16;
SELECT * FROM t1;
