PRAGMA encoding = 'utf-8';
CREATE TABLE t1(a, b, c);
INSERT INTO t1 VALUES('a', 'b', 'c');
ATTACH 'test.db3' AS aux;
PRAGMA encoding;
PRAGMA encoding = 'UTF-16le';
PRAGMA encoding = 'UTF-16le';
PRAGMA encoding;
PRAGMA encoding = 'UTF-8';
CREATE TEMP TABLE t1(a, b, c);
INSERT INTO t1 VALUES('xxx', 'yyy', 'zzz');
SELECT * FROM t1;
INSERT INTO t1 VALUES('xxx', 'yyy', 'zzz');
SELECT * FROM t1;
