SELECT v FROM blobs WHERE rowid = 1;
PRAGMA mmap_size = 0;
PRAGMA auto_vacuum = 0;
BEGIN;
DELETE FROM blobs;
PRAGMA auto_vacuum;
PRAGMA mmap_size = 0;
PRAGMA mmap_size = 0;
PRAGMA mmap_size = 0;
PRAGMA mmap_size = 0;
PRAGMA auto_vacuum = 1;
BEGIN;
DELETE FROM blobs;
PRAGMA auto_vacuum;
PRAGMA mmap_size = 0;
PRAGMA mmap_size = 0;
PRAGMA mmap_size = 0;
CREATE TABLE t3(a INTEGER PRIMARY KEY, b);
INSERT INTO t3 VALUES(1, 2);
CREATE VIEW blobs_view AS SELECT k, v, i FROM blobs;
ATTACH 'test2.db' AS aux;
CREATE TABLE aux.files(name, text);
SELECT rowid FROM blobs ORDER BY rowid;
SELECT * FROM blobs WHERE rowid = 4;
SELECT * FROM blobs WHERE rowid = 4;
BEGIN;
DROP TABLE blobs;
CREATE TABLE t1 (a, b, c, d BLOB);
INSERT INTO t1(a, b, c, d) VALUES(1, 2, 3, 4);
UPDATE t1 SET d = zeroblob(10000);
UPDATE t1 SET d = 15;
SELECT d FROM t1;
SELECT d FROM t1;
UPDATE t1 SET d = zeroblob(10000);
UPDATE t1 SET d = 15;
SELECT d FROM t1;
SELECT d FROM t1;
PRAGMA auto_vacuum = "incremental";
CREATE TABLE t2(a INTEGER PRIMARY KEY, b);
SELECT rootpage FROM sqlite_master;
DELETE FROM t1 WHERE a = 123;
PRAGMA INCREMENTAL_VACUUM(0);
SELECT b FROM t1 WHERE a = 314159;
SELECT b FROM t1 WHERE a = 314159;
