SELECT count(*) FROM numbers;
BEGIN;
DELETE FROM numbers;
DELETE FROM numbers;
CREATE TABLE t0(a, b);
CREATE TABLE t1(a, b DEFAULT 'hello world');
SELECT a, b FROM t0;
INSERT INTO t1(a) VALUES(1);
CREATE TABLE t2(a, b, c);
CREATE INDEX i1 ON t2(a);
