EXPLAIN QUERY PLAN 
  SELECT node FROM listhash WHERE id='5000' LIMIT 1;
EXPLAIN QUERY PLAN 
  SELECT node FROM listhash WHERE id="5000" LIMIT 1;
EXPLAIN QUERY PLAN 
  SELECT node FROM listhash WHERE id=5000 LIMIT 1;
