VACUUM;
CREATE INDEX x1 ON t1(x);
CREATE INDEX x2 ON t1(x);
CREATE INDEX x3 ON t1(x);
INSERT INTO t1 SELECT 2,'';
VACUUM;
vacuum;
PRAGMA integrity_check;
vacuum;
PRAGMA integrity_check;
vacuum;
PRAGMA integrity_check;
PRAGMA page_size = 512;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 2048;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 1024;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 65536;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 8192;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 512;
PRAGMA auto_vacuum = 0;
VACUUM;
PRAGMA integrity_check;
PRAGMA page_size = 4096;
PRAGMA auto_vacuum = 1;
VACUUM;
PRAGMA integrity_check;
