VACUUM;
VACUUM;
PRAGMA page_count;
PRAGMA integrity_check;
CREATE TABLE t4(a,b);
INSERT INTO t4 VALUES('hello','world!');
PRAGMA integrity_check;
SELECT * FROM t4;
PRAGMA journal_mode=TRUNCATE;
PRAGMA journal_mode=OFF;
PRAGMA journal_mode=DELETE;
PRAGMA journal_mode=WAL;
PRAGMA journal_mode=PERSIST;
PRAGMA journal_mode=MEMORY;
PRAGMA journal_mode=OFF;
PRAGMA journal_mode=DELETE;
PRAGMA integrity_check;
CREATE TABLE t1(a, b);
PRAGMA schema_version = 0;
PRAGMA auto_vacuum = 0;
PRAGMA page_size = 8192;
PRAGMA journal_mode = wal;
INSERT INTO t1 VALUES(1, 2);
CREATE TABLE t2(x, y);
PRAGMA locking_mode = exclusive;
SELECT * FROM t1;
INSERT INTO t1 VALUES(3, 4);
SELECT * FROM t1;
PRAGMA wal_checkpoint;
