CREATE INDEX vocab2w ON vocab2(w COLLATE nocase);
INSERT INTO vocab2 VALUES('abc'), ('ABD'), ('aBe'), ('AbF');
CREATE TABLE costs(iLang, cFrom, cTo, iCost);
INSERT INTO costs VALUES(0, 'a', 'e', 1);
INSERT INTO costs VALUES(0, 'e', 'i', 1);
INSERT INTO costs VALUES(0, 'i', 'o', 1);
INSERT INTO costs VALUES(0, 'o', 'u', 1);
INSERT INTO costs VALUES(0, 'u', 'a', 1);
CREATE TABLE costs2(iLang, cFrom, cTo, iCost);
INSERT INTO costs2 VALUES(0, 'a', 'o', 1);
INSERT INTO costs2 VALUES(0, 'e', 'o', 4);
INSERT INTO costs2 VALUES(0, 'i', 'o', 8);
INSERT INTO costs2 VALUES(0, 'u', 'o', 16);
PRAGMA table_info = t4;
CREATE TABLE t5(i, w);
INSERT INTO t5 VALUES(5,  'Poseidon');
INSERT INTO t5 VALUES(20, 'Chronos');
INSERT INTO t5 VALUES(30, 'Hera');
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
