SELECT * FROM "", t2;
PRAGMA table_info("");
CREATE INDEX i1 ON ""("" COLLATE nocase);
DROP TABLE "";
SELECT name FROM sqlite_master;
CREATE INDEX "" ON t2(x);
EXPLAIN QUERY PLAN SELECT * FROM t2 WHERE x=5;
DROP INDEX "";
EXPLAIN QUERY PLAN SELECT * FROM t2 WHERE x=2;
