SELECT * FROM t1;
SELECT * FROM sqlite_master;
PRAGMA integrity_check;
PRAGMA page_count;
PRAGMA integrity_check;
PRAGMA encoding = 'utf8';
PRAGMA encoding;
CREATE TEMP TABLE t2(x);
INSERT INTO t2 VALUES('hello world');
SELECT name FROM sqlite_schema;
SELECT * FROM t1;
SELECT * FROM t2;
