SELECT * FROM c1;
PRAGMA main.journal_mode;
PRAGMA main.journal_mode = delete;
PRAGMA auto_vacuum=OFF;
PRAGMA journal_mode = wal;
CREATE TABLE y1(a PRIMARY KEY, b UNIQUE, c);
INSERT INTO y1 VALUES('a', 'b', 'c');
INSERT INTO y1 VALUES('d', 'e', 'f');
BEGIN;
SELECT * FROM y1;
UPDATE y1 SET c='g' WHERE a='d';
PRAGMA wal_checkpoint;
PRAGMA integrity_check;
SELECT * FROM y1;
