PRAGMA journal_mode = WAL;
CREATE TABLE t1(a);
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
INSERT INTO t1 VALUES(3);
INSERT INTO t1 VALUES(4);
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
PRAGMA journal_mode = WAL;
INSERT INTO t1 VALUES(1);
INSERT INTO t1 VALUES(2);
INSERT INTO t1 VALUES(3);
INSERT INTO t1 VALUES(4);
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
SELECT count(a), sum(a) FROM t1;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = WAL;
CREATE TABLE data(x);
INSERT INTO data VALUES('need xShmOpen to see this');
PRAGMA wal_checkpoint;
SELECT * FROM data;
SELECT * FROM data;
PRAGMA journal_mode = WAL;
CREATE TABLE x(y);
INSERT INTO x VALUES(1);
PRAGMA wal_checkpoint;
Pragma Journal_Mode = Wal;
PRAGMA lock_status;
SELECT * FROM sqlite_master;
Pragma Locking_Mode = Exclusive;
BEGIN;
PRAGMA lock_status;
PRAGMA locking_mode = normal;
PRAGMA lock_status;
SELECT * FROM t1;
PRAGMA lock_status;
PRAGMA lock_status;
Pragma Locking_Mode = Exclusive;
Pragma Journal_Mode = Wal;
Pragma Lock_Status;
BEGIN;
Pragma loCK_STATus;
SELECT * FROM sqlite_master;
PRAGMA LOCKING_MODE = EXCLUSIVE;
SELECT * FROM t1;
pragma lock_status;
pragma lock_status;
PRAGMA locking_mode = NORMAL;
pragma lock_status;
BEGIN IMMEDIATE;
pragma lock_status;
PRAGMA locking_mode = EXCLUSIVE;
BEGIN IMMEDIATE;
PRAGMA locking_mode = NORMAL;
SELECT * FROM t1;
pragma lock_status;
SELECT * FROM t1;
pragma lock_status;
PRAGMA journal_mode = WAL;
PRAGMA locking_mode = exclusive;
BEGIN;
INSERT INTO t1 VALUES('Chico');
INSERT INTO t1 VALUES('Harpo');
PRAGMA journal_mode = DELETE;
PRAGMA lock_status;
BEGIN;
INSERT INTO t1 VALUES('Groucho');
PRAGMA lock_status;
PRAGMA lock_status;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = WAL;
BEGIN;
INSERT INTO t1 VALUES('Leonard');
INSERT INTO t1 VALUES('Arthur');
SELECT * FROM t1;
PRAGMA locking_mode = exclusive;
INSERT INTO t1 VALUES('Julius Henry');
SELECT * FROM t1;
INSERT INTO t1 VALUES('Karl');
SELECT * FROM t1;
PRAGMA locking_mode = normal;
DELETE FROM t1;
SELECT * FROM t1;
PRAGMA auto_vacuum = 0;
PRAGMA journal_mode = wal;
PRAGMA locking_mode = exclusive;
CREATE TABLE t2(a, b);
PRAGMA wal_checkpoint;
INSERT INTO t2 VALUES('I', 'II');
PRAGMA journal_mode;
PRAGMA locking_mode = normal;
INSERT INTO t2 VALUES('III', 'IV');
PRAGMA locking_mode = exclusive;
SELECT * FROM t2;
PRAGMA wal_checkpoint;
SELECT * FROM sqlite_master;
PRAGMA locking_mode = exclusive;
INSERT INTO t2 VALUES('V', 'VI');
PRAGMA locking_mode = normal;
INSERT INTO t2 VALUES('VII', 'VIII');
SELECT * FROM t2;
INSERT INTO t2 VALUES('IX', 'X');
SELECT * FROM t2;
PRAGMA page_size = 4096;
PRAGMA journal_mode = WAL;
PRAGMA wal_checkpoint;
SELECT * FROM sqlite_master;
PRAGMA auto_vacuum=OFF;
PRAGMA page_size = 1024;
PRAGMA journal_mode = WAL;
INSERT INTO t1 VALUES(zeroblob(8188*1020));
PRAGMA wal_checkpoint;
SELECT rootpage>=8192 FROM sqlite_master WHERE tbl_name = 't2';
SELECT * FROM t2;
PRAGMA journal_mode = WAL;
INSERT INTO x VALUES('Barton');
INSERT INTO x VALUES('Deakin');
INSERT INTO x VALUES('Watson');
SELECT * FROM x;
SELECT * FROM x;
SELECT * FROM x;
SELECT * FROM x;
SELECT * FROM x;
SELECT * FROM x;
SELECT * FROM x;
PRAGMA journal_mode = WAL;
PRAGMA wal_checkpoint;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1;
PRAGMA journal_mode = WAL;
SELECT * FROM t1;
SELECT name FROM sqlite_master;
SELECT * FROM t1;
CREATE TABLE tx(y, z);
PRAGMA journal_mode = WAL;
INSERT INTO tx DEFAULT VALUES;
INSERT INTO tx DEFAULT VALUES;
INSERT INTO tx DEFAULT VALUES;
INSERT INTO tx DEFAULT VALUES;
PRAGMA journal_mode = WAL;
PRAGMA wal_checkpoint;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
SELECT * FROM t1;
INSERT INTO t1 DEFAULT VALUES;
PRAGMA auto_vacuum = 0;
PRAGMA synchronous = FULL;
PRAGMA page_size = 4096;
PRAGMA journal_mode = WAL;
PRAGMA wal_autocheckpoint = 10;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync
    BEGIN;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync;
PRAGMA wal_autocheckpoint = 1000;
PRAGMA auto_vacuum = 0;
PRAGMA synchronous = FULL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA page_size = 4096;
PRAGMA journal_mode = WAL;
PRAGMA wal_autocheckpoint = 10;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync
    BEGIN;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync;
PRAGMA wal_autocheckpoint = 1000;
PRAGMA auto_vacuum = 0;
PRAGMA synchronous = FULL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA page_size = 4096;
PRAGMA journal_mode = WAL;
PRAGMA wal_autocheckpoint = 10;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync
    BEGIN;
-- 2 wal sync
    PRAGMA wal_checkpoint;
-- 1 wal sync, 1 db sync;
PRAGMA wal_autocheckpoint = 1000;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 0;
PRAGMA synchronous = off;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 0;
PRAGMA synchronous = normal;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 0;
PRAGMA synchronous = full;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 1;
PRAGMA synchronous = off;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 1;
PRAGMA synchronous = normal;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 0;
PRAGMA fullfsync = 1;
PRAGMA synchronous = full;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 0;
PRAGMA synchronous = off;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 0;
PRAGMA synchronous = normal;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 0;
PRAGMA synchronous = full;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 1;
PRAGMA synchronous = off;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 1;
PRAGMA synchronous = normal;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
PRAGMA page_size = 4096;
PRAGMA wal_autocheckpoint = OFF;
PRAGMA journal_mode = WAL;
PRAGMA checkpoint_fullfsync = 1;
PRAGMA fullfsync = 1;
PRAGMA synchronous = full;
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('abc');
INSERT INTO t1 VALUES('def');
PRAGMA wal_checkpoint;
