SELECT * FROM log ORDER BY x;
INSERT INTO t1 SELECT a, b+10 FROM t1;
SELECT * FROM log ORDER BY x;
CREATE TABLE log2(x PRIMARY KEY,y);
INSERT INTO t1 VALUES(453,'hi');
SELECT * FROM log ORDER BY x;
SELECT * FROM log2 ORDER BY x;
INSERT INTO t1 SELECT * FROM t1;
SELECT 'a:', x, y FROM log UNION ALL 
          SELECT 'b:', x, y FROM log2 ORDER BY x;
SELECT 'a:', x, y FROM log UNION ALL 
          SELECT 'b:', x, y FROM log2 ORDER BY x, y;
INSERT INTO t1(a) VALUES('xyz');
SELECT * FROM log ORDER BY x;
CREATE TABLE t2(
      a INTEGER PRIMARY KEY,
      b DEFAULT 'b',
      c DEFAULT 'c'
    );
CREATE TABLE t2dup(a,b,c);
INSERT INTO t2(a) VALUES(123);
INSERT INTO t2(b) VALUES(234);
INSERT INTO t2(c) VALUES(345);
SELECT * FROM t2dup;
DELETE FROM t2dup;
INSERT INTO t2(a) SELECT 1 FROM t1 LIMIT 1;
INSERT INTO t2(b) SELECT 987 FROM t1 LIMIT 1;
INSERT INTO t2(c) SELECT 876 FROM t1 LIMIT 1;
SELECT * FROM t2dup;
CREATE TABLE t3(a,b,c);
INSERT INTO t3 VALUES(1,2,3);
CREATE TABLE t4(a,b,c);
INSERT INTO t4 VALUES(1,2,3);
CREATE TABLE t5(
      a INTEGER PRIMARY KEY,
      b DEFAULT 'xyz'
    );
INSERT INTO t5 DEFAULT VALUES;
SELECT * FROM t5;
INSERT INTO t5 DEFAULT VALUES;
SELECT * FROM t5;
CREATE TABLE t6(x,y DEFAULT 4.3, z DEFAULT x'6869');
INSERT INTO t6 DEFAULT VALUES;
SELECT * FROM t6;
CREATE INDEX i1 ON t1(a, b);
BEGIN;
PRAGMA cache_size = 10;
BEGIN;
DELETE FROM t1 WHERE rowid%2;
