SELECT count(*) FROM t1;
SELECT x FROM t1 WHERE x LIKE 'abc' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abc' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'ABC' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'aBc' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abc' ORDER BY 1;
PRAGMA case_sensitive_like;
SELECT x FROM t1 WHERE x GLOB 'abc' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'ABC' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'aBc' ORDER BY 1;
PRAGMA case_sensitive_like=off;
SELECT x FROM t1 WHERE x LIKE 'abc' ORDER BY 1;
PRAGMA case_sensitive_like;
SELECT x FROM t1 WHERE x LIKE 'abc' ORDER BY 1;
SELECT x FROM t1 WHERE x MATCH '*abc*' ORDER BY 1;
SELECT x FROM t1 WHERE x MATCH 'abc*' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
PRAGMA case_sensitive_like=on;
CREATE INDEX i1 ON t1(x);
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'a' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'a' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'ab' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'ab' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abcd' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abcd' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abcde' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abcde' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'a_c' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'a_c' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'ab%d' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'ab%d' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'a_c%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'a_c%' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE '%bcd' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE '%bcd' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'abc*' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'a[bc]d' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'a[bc]d' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'a' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'a' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abcd' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'abcd' ORDER BY 1;
SELECT x FROM t1 WHERE x GLOB 'abcde' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x GLOB 'abcde' ORDER BY 1;
PRAGMA case_sensitive_like=on;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE +x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE +x LIKE 'abc%' ORDER BY 1;
SELECT x FROM t1 WHERE x LIKE ('ab' || 'c%') ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE ('ab' || 'c%') ORDER BY 1;
PRAGMA case_sensitive_like=off;
SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'abc%' ORDER BY 1;
CREATE TABLE t2(x TEXT COLLATE NOCASE);
INSERT INTO t2 SELECT * FROM t1 ORDER BY rowid;
CREATE INDEX i2 ON t2(x COLLATE NOCASE);
SELECT x FROM t2 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'abc%' ORDER BY 1;
PRAGMA case_sensitive_like=on;
SELECT x FROM t2 WHERE x LIKE 'abc%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'abc%' ORDER BY 1;
PRAGMA case_sensitive_like=off;
SELECT x FROM t2 WHERE x GLOB 'abc*' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x GLOB 'abc*' ORDER BY 1;
PRAGMA case_sensitive_like=off;
SELECT x FROM t1 WHERE x LIKE 'ABC%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t1 WHERE x LIKE 'ABC%' ORDER BY 1;
SELECT x FROM t2 WHERE x LIKE 'ABC%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'ABC%' ORDER BY 1;
PRAGMA case_sensitive_like=on;
SELECT x FROM t2 WHERE x LIKE 'ABC%' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'ABC%' ORDER BY 1;
PRAGMA case_sensitive_like=off;
SELECT x FROM t2 WHERE x GLOB 'ABC*' ORDER BY 1;
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x GLOB 'ABC*' ORDER BY 1;
PRAGMA case_sensitive_like=off;
INSERT INTO t2 VALUES('ZZ-upper-upper');
INSERT INTO t2 VALUES('zZ-lower-upper');
INSERT INTO t2 VALUES('Zz-upper-lower');
INSERT INTO t2 VALUES('zz-lower-lower');
SELECT x FROM t2 WHERE x LIKE 'zz%';
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'zz%';
SELECT x FROM t2 WHERE x LIKE 'zZ%';
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'zZ%';
SELECT x FROM t2 WHERE x LIKE 'Zz%';
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'Zz%';
SELECT x FROM t2 WHERE x LIKE 'ZZ%';
EXPLAIN QUERY PLAN 
    SELECT x FROM t2 WHERE x LIKE 'ZZ%';
SELECT * FROM t2 WHERE x LIKE '''a%';
SELECT rowid, * FROM t1 WHERE rowid GLOB '1*' ORDER BY rowid;
CREATE TABLE t10(
        a INTEGER PRIMARY KEY,
        b INTEGER COLLATE nocase UNIQUE,
        c NUMBER COLLATE nocase UNIQUE,
        d BLOB COLLATE nocase UNIQUE,
        e COLLATE nocase UNIQUE,
        f TEXT COLLATE nocase UNIQUE
      );
INSERT INTO t10 VALUES(1,1,1,1,1,1);
INSERT INTO t10 VALUES(12,12,12,12,12,12);
INSERT INTO t10 VALUES(123,123,123,123,123,123);
INSERT INTO t10 VALUES(234,234,234,234,234,234);
INSERT INTO t10 VALUES(345,345,345,345,345,345);
INSERT INTO t10 VALUES(45,45,45,45,45,45);
SELECT a FROM t10 WHERE b LIKE '12%' ORDER BY +a;
SELECT a FROM t10 WHERE c LIKE '12%' ORDER BY +a;
SELECT a FROM t10 WHERE d LIKE '12%' ORDER BY +a;
SELECT a FROM t10 WHERE e LIKE '12%' ORDER BY +a;
SELECT a FROM t10 WHERE f LIKE '12%' ORDER BY +a;
SELECT a FROM t10 WHERE a LIKE '12%' ORDER BY +a;
CREATE TABLE t10b(
        a INTEGER PRIMARY KEY,
        b INTEGER UNIQUE,
        c NUMBER UNIQUE,
        d BLOB UNIQUE,
        e UNIQUE,
        f TEXT UNIQUE
      );
INSERT INTO t10b SELECT * FROM t10;
SELECT a FROM t10b WHERE b GLOB '12*' ORDER BY +a;
SELECT a FROM t10b WHERE c GLOB '12*' ORDER BY +a;
SELECT a FROM t10b WHERE d GLOB '12*' ORDER BY +a;
SELECT a FROM t10b WHERE e GLOB '12*' ORDER BY +a;
SELECT a FROM t10b WHERE f GLOB '12*' ORDER BY +a;
SELECT a FROM t10b WHERE a GLOB '12*' ORDER BY +a;
CREATE TABLE t11(
      a INTEGER PRIMARY KEY,
      b TEXT COLLATE nocase,
      c TEXT COLLATE binary
    );
INSERT INTO t11 VALUES(1, 'a','a');
INSERT INTO t11 VALUES(2, 'ab','ab');
INSERT INTO t11 VALUES(3, 'abc','abc');
INSERT INTO t11 VALUES(4, 'abcd','abcd');
INSERT INTO t11 VALUES(5, 'A','A');
INSERT INTO t11 VALUES(6, 'AB','AB');
INSERT INTO t11 VALUES(7, 'ABC','ABC');
INSERT INTO t11 VALUES(8, 'ABCD','ABCD');
INSERT INTO t11 VALUES(9, 'x','x');
INSERT INTO t11 VALUES(10, 'yz','yz');
INSERT INTO t11 VALUES(11, 'X','X');
INSERT INTO t11 VALUES(12, 'YZ','YZ');
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b LIKE 'abc%' ORDER BY +a;
SELECT b FROM t11 WHERE b GLOB 'abc*' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT b FROM t11 WHERE b GLOB 'abc*' ORDER BY +a;
SELECT c FROM t11 WHERE c LIKE 'abc%' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT c FROM t11 WHERE c LIKE 'abc%' ORDER BY +a;
SELECT c FROM t11 WHERE c GLOB 'abc*' ORDER BY +a;
EXPLAIN QUERY PLAN 
    SELECT c FROM t11 WHERE c GLOB 'abc*' ORDER BY +a;
CREATE TABLE t12nc(id INTEGER, x TEXT UNIQUE COLLATE nocase);
INSERT INTO t12nc VALUES(1,'abcde'),(2,'uvwxy'),(3,'ABCDEF');
CREATE TABLE t12b(id INTEGER, x TEXT UNIQUE COLLATE binary);
INSERT INTO t12b VALUES(1,'abcde'),(2,'uvwxy'),(3,'ABCDEF');
SELECT id FROM t12nc WHERE x LIKE 'abc%' ORDER BY +id;
SELECT id FROM t12b WHERE x LIKE 'abc%' ORDER BY +id;
SELECT id FROM t12nc WHERE x LIKE 'abc%' COLLATE binary ORDER BY +id;
SELECT id FROM t12b WHERE x LIKE 'abc%' COLLATE binary ORDER BY +id;
SELECT id FROM t12nc WHERE x LIKE 'abc%' COLLATE nocase ORDER BY +id;
SELECT id FROM t12b WHERE x LIKE 'abc%' COLLATE nocase ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12nc WHERE x LIKE 'abc%' ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12b WHERE x LIKE 'abc%' ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12nc WHERE x LIKE 'abc%' COLLATE nocase ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12b WHERE x LIKE 'abc%' COLLATE nocase ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12nc WHERE x LIKE 'abc%' COLLATE binary ORDER BY +id;
EXPLAIN QUERY PLAN
  SELECT id FROM t12b WHERE x LIKE 'abc%' COLLATE binary ORDER BY +id;
SELECT char(0x304d) LIKE char(0x306d);
SELECT char(0x4d) LIKE char(0x306d);
SELECT char(0x304d) LIKE char(0x6d);
SELECT char(0x4d) LIKE char(0x6d);
CREATE TABLE t15(x TEXT COLLATE nocase, y, PRIMARY KEY(x));
INSERT INTO t15(x,y) VALUES
    ('abcde',1), ('ab%de',2), ('a_cde',3),
    ('uvwxy',11),('uvwx%',12),('uvwx_',13),
    ('_bcde',21),('%bcde',22),
    ('abcd_',31),('abcd%',32),
    ('ab%xy',41);
SELECT y FROM t15 WHERE x LIKE 'ab/%d%' ESCAPE '/';
EXPLAIN QUERY PLAN
  SELECT y FROM t15 WHERE x LIKE 'ab/%d%' ESCAPE '/';
EXPLAIN QUERY PLAN
  SELECT y FROM t15 WHERE x LIKE 'ab/%d%' ESCAPE '//';
EXPLAIN QUERY PLAN
  SELECT y FROM t15 WHERE x LIKE 'ab/%d%' ESCAPE '';
SELECT y FROM t15 WHERE x LIKE 'abcdx%%' ESCAPE 'x';
SELECT y FROM t15 WHERE x LIKE 'abx%%' ESCAPE 'x' ORDER BY +y;
EXPLAIN QUERY PLAN
  SELECT y FROM t15 WHERE x LIKE 'abx%%' ESCAPE 'x' ORDER BY +y;
SELECT y FROM t15 WHERE x LIKE '/%bc%' ESCAPE '/';
EXPLAIN QUERY PLAN
  SELECT y FROM t15 WHERE x LIKE '/%bc%' ESCAPE '/';
INSERT INTO t1 VALUES(' 1x');
INSERT INTO t1 VALUES(' 1-');
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(id INTEGER PRIMARY KEY, x TEXT);
INSERT INTO t1 VALUES
    (1,'abcde'),
    (2,'abc_'),
    (3,'abc__'),
    (4,'abc%'),
    (5,'abc%%');
SELECT id FROM t1 WHERE x LIKE 'abc%%' ESCAPE '%';
SELECT id FROM t1 WHERE x LIKE 'abc__' ESCAPE '_';
SELECT 'x' LIKE '%' ESCAPE '_';
SELECT * FROM t2;
PRAGMA case_sensitive_like=OFF;
SELECT * FROM t2;
PRAGMA case_sensitive_like=ON;
SELECT * FROM t2;
