SELECT name FROM sqlite_master ORDER BY 1;
SELECT name FROM sqlite_master ORDER BY 1;
SELECT name FROM sqlite_master ORDER BY 1;
CREATE TABLE treal(a, b, c);
CREATE VIRTUAL TABLE IF NOT EXISTS treal USING echo(treal);
DROP TABLE treal;
SELECT name FROM sqlite_master ORDER BY 1;
CREATE TABLE treal(a, b, c);
PRAGMA table_info(techo);
CREATE TABLE logmsg(log);
DROP TABLE treal;
DROP TABLE logmsg;
SELECT sql FROM sqlite_master;
CREATE TABLE template(a, b, c);
PRAGMA table_info(template);
PRAGMA table_info(t1);
PRAGMA table_info(t1);
PRAGMA table_info(t1);
PRAGMA table_info(t1);
SELECT sql FROM sqlite_master;
DROP TABLE template;
SELECT sql FROM sqlite_master;
CREATE TABLE treal(a INTEGER, b INTEGER, c);
CREATE INDEX treal_idx ON treal(b);
INSERT INTO treal VALUES(1, 2, 3);
INSERT INTO treal VALUES(4, 5, 6);
DROP TABLE treal;
CREATE TABLE t1(a, b, c);
CREATE TABLE t2(d, e, f);
INSERT INTO t1 VALUES(1, 'red', 'green');
INSERT INTO t1 VALUES(2, 'blue', 'black');
INSERT INTO t2 VALUES(1, 'spades', 'clubs');
INSERT INTO t2 VALUES(2, 'hearts', 'diamonds');
CREATE INDEX i1 ON t2(d);
DROP TABLE t1;
DROP TABLE t2;
SELECT sql FROM sqlite_master;
CREATE TABLE treal(a PRIMARY KEY, b, c);
SELECT name FROM sqlite_master WHERE type = 'table';
PRAGMA count_changes=ON;
PRAGMA count_changes=OFF;
CREATE TABLE techo(a PRIMARY KEY, b, c);
INSERT INTO techo VALUES('abc', 'def', 'ghi');
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
INSERT INTO techo SELECT a||'.'||rowid, b, c FROM techo;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
INSERT INTO techo SELECT a||'x'||rowid, b, c FROM techo;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
INSERT INTO techo SELECT a||'y'||rowid, b, c FROM techo;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
DELETE FROM techo WHERE (oid % 3) = 0;
DELETE FROM techo WHERE (oid % 3) = 0;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
UPDATE techo set rowid = 100 WHERE rowid = 1;
UPDATE techo set rowid = 100 WHERE rowid = 1;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
INSERT INTO techo(a, b) VALUES('hello', 'world');
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
DELETE FROM techo;
DELETE FROM techo;
SELECT rowid, * FROM techo;
SELECT rowid, * FROM techo;
CREATE TABLE real_abc(a PRIMARY KEY, b, c);
SELECT last_insert_rowid();
SELECT rowid, a, b, c FROM real_abc;
SELECT rowid, a, b, c FROM real_abc;
PRAGMA index_info('echo_abc');
PRAGMA index_xinfo('echo_abc');
ATTACH 'test2.db' AS aux;
DROP TABLE treal;
DROP TABLE techo;
DROP TABLE real_abc;
CREATE TABLE r(a, b, c);
SELECT name FROM sqlite_master;
SELECT name FROM sqlite_master;
CREATE TABLE del(d);
DROP TABLE del;
INSERT INTO r(a,b,c) VALUES(1,'?',99);
INSERT INTO r(a,b,c) VALUES(2,3,99);
CREATE TABLE b(a, b, c);
CREATE TABLE c(a UNIQUE, b, c);
INSERT INTO b VALUES(1, 'A', 'B');
INSERT INTO b VALUES(2, 'C', 'D');
INSERT INTO b VALUES(3, 'E', 'F');
INSERT INTO c VALUES(3, 'G', 'H');
SELECT * FROM c;
BEGIN;
SELECT * FROM c;
SELECT * FROM c;
INSERT INTO c VALUES(NULL, 15, 16);
INSERT INTO c VALUES(15, NULL, 16);
CREATE TABLE t1(a, b, c);
CREATE TABLE t2(a PRIMARY KEY, b, c);
INSERT INTO t2 VALUES(1, 2, 3);
INSERT INTO t2 VALUES(4, 5, 6);
PRAGMA writable_schema = 1;
INSERT INTO sqlite_master VALUES(
      'table', 't3', 't3', 0, 'INSERT INTO "%s%s" VALUES(1)'
    );
DELETE FROM sqlite_master WHERE sql LIKE 'insert%';
CREATE TABLE t6(a, b TEXT);
CREATE INDEX i6 ON t6(b, a);
INSERT INTO t6 VALUES(1, 'Peter');
INSERT INTO t6 VALUES(2, 'Andrew');
INSERT INTO t6 VALUES(3, '8James');
INSERT INTO t6 VALUES(4, '8John');
INSERT INTO t6 VALUES(5, 'Phillip');
INSERT INTO t6 VALUES(6, 'Bartholomew');
PRAGMA case_sensitive_like = ON;
PRAGMA case_sensitive_like = OFF;
CREATE TABLE t7 (a, b);
CREATE TABLE t8 (c, d);
CREATE INDEX i2 ON t7(a);
CREATE INDEX i3 ON t7(b);
CREATE INDEX i4 ON t8(c);
CREATE INDEX i5 ON t8(d);
SELECT a, b FROM (
      SELECT a, b FROM t7 WHERE a=11 OR b=12
      UNION ALL
      SELECT c, d FROM t8 WHERE c=5 OR d=6
  )
  ORDER BY 1, 2;
CREATE TABLE t9(a,b,c);
INSERT INTO t9 VALUES(1,2,3);
INSERT INTO t9 VALUES(3,2,1);
INSERT INTO t9 VALUES(2,2,2);
DROP TABLE t1;
CREATE TABLE t0(a);
CREATE TABLE tx(a, b, c);
