ANALYZE;
EXPLAIN QUERY PLAN SELECT * FROM t1 ORDER BY a;
EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a > 100;
EXPLAIN QUERY PLAN SELECT max(a) FROM t1;
EXPLAIN QUERY PLAN SELECT group_concat(b) FROM t1 GROUP BY a;
EXPLAIN QUERY PLAN SELECT count(*) FROM t1;
UPDATE sqlite_stat1 SET stat = stat || ' unordered';
EXPLAIN QUERY PLAN SELECT * FROM t1 ORDER BY a;
EXPLAIN QUERY PLAN SELECT * FROM t1 WHERE a > 100;
