SELECT name FROM sqlite_master;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA encoding = 'UTF-8';
PRAGMA page_size = '1024';
PRAGMA auto_vacuum = '0';
PRAGMA user_version = '0';
PRAGMA application_id = '0';
CREATE TABLE lost_and_found_0(rootpgno INTEGER, pgno INTEGER, nfield INTEGER, id INTEGER, c0, c1, c2);
INSERT INTO lost_and_found_0 VALUES(2, 2, 3, NULL, 2, 3, 1);
INSERT INTO lost_and_found_0 VALUES(2, 2, 3, NULL, 5, 6, 4);
INSERT INTO lost_and_found_0 VALUES(2, 2, 3, NULL, 8, 9, 7);
PRAGMA writable_schema = off;
SELECT name FROM sqlite_master;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA encoding = 'UTF-8';
PRAGMA page_size = '1024';
PRAGMA auto_vacuum = '0';
PRAGMA user_version = '0';
PRAGMA application_id = '0';
CREATE TABLE lost_and_found_1(rootpgno INTEGER, pgno INTEGER, nfield INTEGER, id INTEGER, c0, c1, c2);
INSERT INTO lost_and_found_1 VALUES(2, 2, 3, NULL, 2, 3, 1);
INSERT INTO lost_and_found_1 VALUES(2, 2, 3, NULL, 5, 6, 4);
INSERT INTO lost_and_found_1 VALUES(2, 2, 3, NULL, 8, 9, 7);
PRAGMA writable_schema = off;
SELECT name FROM sqlite_master;
SELECT * FROM lost_and_found_1;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA encoding = 'UTF-8';
PRAGMA page_size = '4096';
PRAGMA auto_vacuum = '0';
PRAGMA user_version = '0';
PRAGMA application_id = '0';
PRAGMA writable_schema = off;
PRAGMA secure_delete = 0;
PRAGMA auto_vacuum = 0;
INSERT INTO t2 VALUES(1, 2, 3);
DROP TABLE t1;
DROP TABLE t2;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA encoding = 'UTF-8';
PRAGMA page_size = '1024';
PRAGMA auto_vacuum = '0';
PRAGMA user_version = '0';
PRAGMA application_id = '0';
INSERT INTO lost_and_found VALUES(3, 3, 3, 1, 1, 2, 3);
INSERT INTO lost_and_found VALUES(3, 3, 3, 2, 'a', 'b', 'c');
PRAGMA writable_schema = off;
SELECT name FROM sqlite_schema;
SELECT id, c0, c1, c2 FROM lost_and_found;
BEGIN;
PRAGMA writable_schema = on;
PRAGMA encoding = 'UTF-8';
PRAGMA page_size = '1024';
PRAGMA auto_vacuum = '0';
PRAGMA user_version = '0';
PRAGMA application_id = '0';
PRAGMA writable_schema = off;
SELECT name FROM sqlite_schema;
SELECT * FROM t3;
