SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
DELETE FROM t1;
SELECT id FROM t1 WHERE a = 'a' OR b = 'b' OR c = 'c';
