SELECT * FROM B;
EXPLAIN  INSERT INTO b SELECT * FROM main;
EXPLAIN  INSERT INTO b SELECT * FROM b;
EXPLAIN  INSERT INTO b SELECT (SELECT id FROM b), id1 FROM main;
EXPLAIN  INSERT INTO b SELECT id1, (SELECT id FROM b) FROM main;
EXPLAIN  
    INSERT INTO b 
      SELECT * FROM main WHERE id = (SELECT id1 FROM b WHERE main.id = b.id);
EXPLAIN  INSERT INTO b SELECT * FROM v1;
EXPLAIN  INSERT INTO b SELECT * FROM v2;
EXPLAIN  
    INSERT INTO b 
    SELECT * FROM main WHERE id > 10 AND max(id1, (SELECT id FROM b)) > 10;
