SELECT sql FROM sqlite_master;
CREATE TABLE t3(g, h, i);
INSERT INTO t3 VALUES('III', 'IV', 'V');
SELECT * FROM t3;
SELECT * FROM t3;
SELECT sql FROM sqlite_master;
SELECT * FROM t3;
SELECT * FROM t3;
CREATE TABLE blobs(x);
INSERT INTO blobs VALUES('a twentyeight character blob');
BEGIN;
SELECT count(*) FROM blobs;
SELECT x FROM blobs WHERE rowid = 2;
PRAGMA auto_vacuum = incremental;
CREATE TABLE t1(a, b, c);
CREATE INDEX i1 ON t1(a, b);
BEGIN;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA auto_vacuum = incremental;
PRAGMA cache_size = 10;
BEGIN;
INSERT INTO t1(a) VALUES('alligator');
INSERT INTO t1(a) VALUES('angelfish');
INSERT INTO t1(a) VALUES('ant');
INSERT INTO t1(a) VALUES('antelope');
INSERT INTO t1(a) VALUES('ape');
INSERT INTO t1(a) VALUES('baboon');
INSERT INTO t1(a) VALUES('badger');
INSERT INTO t1(a) VALUES('bear');
INSERT INTO t1(a) VALUES('beetle');
INSERT INTO t1(a) VALUES('bird');
INSERT INTO t1(a) VALUES('bison');
PRAGMA page_count;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA auto_vacuum = incremental;
PRAGMA integrity_check;
ATTACH 'test2.db' AS aux;
DETACH aux;
ATTACH 'test2.db' AS aux1;
ATTACH 'test3.db' AS aux2;
DROP TABLE t1;
CREATE TABLE main.t1(x, y);
CREATE TABLE aux1.t2(x, y);
CREATE TABLE aux2.t3(x, y);
SELECT name FROM sqlite_master;
SELECT name FROM aux1.sqlite_master;
SELECT name FROM aux2.sqlite_master;
PRAGMA lock_status;
PRAGMA lock_status;
SELECT * FROM t2;
SELECT * FROM t2;
PRAGMA lock_status;
SELECT 'a', * FROM t1;
SELECT 'b', * FROM t3;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
PRAGMA lock_status;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
PRAGMA lock_status;
PRAGMA auto_vacuum = full;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA integrity_check;
PRAGMA wal_checkpoint;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;
SELECT * FROM t2;
SELECT * FROM t2;
CREATE TABLE t4(a PRIMARY KEY, b);
INSERT INTO t4 VALUES(1, 'one');
BEGIN;
CREATE TABLE t1(a PRIMARY KEY, b);
INSERT INTO t1 VALUES(1, 2);
PRAGMA journal_mode = off;
BEGIN;
INSERT INTO t1 VALUES(3, 4);
INSERT INTO t1 SELECT a+4,b+4  FROM t1;
CREATE TABLE t6(a, b);
