ATTACH 'test2.db' AS aux;
PRAGMA aux.auto_vacuum=OFF;
PRAGMA aux.freelist_count;
CREATE TABLE aux.abc(a, b, c);
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
DELETE FROM aux.abc;
PRAGMA aux.freelist_count;
PRAGMA aux.freelist_count;
PRAGMA main.freelist_count;
PRAGMA freelist_count;
PRAGMA freelist_count = 500;
PRAGMA freelist_count;
PRAGMA aux.freelist_count = 500;
PRAGMA aux.freelist_count;
PRAGMA main.cache_size=2000;
PRAGMA temp.cache_size=2000;
PRAGMA cache_spill;
PRAGMA main.cache_spill;
PRAGMA temp.cache_spill;
PRAGMA cache_spill=OFF;
PRAGMA cache_spill;
PRAGMA main.cache_spill;
PRAGMA temp.cache_spill;
PRAGMA cache_spill=OFF;
ATTACH 'test2.db' AS aux1;
PRAGMA aux1.cache_size=50;
BEGIN;
PRAGMA lock_status;
PRAGMA cache_spill=ON;
BEGIN;
PRAGMA lock_status;
PRAGMA page_size=16384;
CREATE TABLE t1(x);
PRAGMA cache_size=2;
PRAGMA cache_spill=YES;
PRAGMA cache_spill;
PRAGMA cache_spill=NO;
PRAGMA cache_spill;
PRAGMA cache_spill(-51);
PRAGMA cache_spill;
