PRAGMA enable_verification;
SELECT '{a=1, b=2, a=3}'::MAP(VARCHAR, INT);
CREATE TABLE stringMap (col1 VARCHAR);
INSERT INTO stringMap VALUES ('{1=Duck, 2=DB}'), ('{999=🦆}'), ('{7=Hello, 8=World, 2=!}');;
CREATE TABLE null_tbl(col1 VARCHAR);;
INSERT INTO null_tbl VALUES(NULL), ('{key=NULL}'), ('{zero=0, key=NULL}');;
SELECT CAST('{NULL=5}' AS MAP(INT, INT));;
CREATE TABLE try_cast_tbl (col1 VARCHAR);;
INSERT INTO try_cast_tbl VALUES ('{1=2, XXX=2}'), ('{NULL=DuckDB}'), ('{3=oops, 5=5 44=4.0}'), ('{12345678901=0}'), ('{5=6!, 7=7000}'), ('{3 0, 1=1}');;
SELECT CAST('{3==3}' AS MAP(INT, INT));;
SELECT CAST('{[5]=5}' AS MAP(INT, INT));;
SELECT CAST('{3=three}}' AS MAP(INT, VARCHAR));;
SELECT CAST('{Ducky=, DB=ok}' AS MAP(VARCHAR, INT));;
SELECT CAST('{5=5,, 3=3}' AS MAP(INT, INT));;
SELECT CAST('{3=3, 4=4' AS MAP(INT, INT));;
SELECT CAST('{3=3, 4=4} bla' AS MAP(INT, INT));;
SELECT CAST('{                                                                      ' AS MAP(INT, INT));;
CREATE TABLE Duck_tbl (col1 VARCHAR);;
INSERT INTO Duck_tbl VALUES ('{1=Duck, 3=DB}'), ('{12=DuckDB}'), ('{3=DB, 5=🦆 4=Ducky, 7=Duckster}'), ('{0=DuckParty}'), ('{5=DBDuck, 7=Duckster, 1=🦆}'), ('{1="final Quack"}');;
CREATE TYPE mood AS ENUM('ok', 'sad', 'happy');;
SELECT '{sadDucky: nothappy}'::MAP(VARCHAR, MOOD);
CREATE TABLE intMap AS SELECT map([i], [i+1])::VARCHAR::MAP(INT, INT) col FROM range(0, 10000) tbl(i);;
CREATE TABLE assembled_maps(col1 MAP(INT, VARCHAR));;
COPY (SELECT '{8="hello, DuckDB"}') TO '__TEST_DIR__/assembled_maps.csv';;
COPY assembled_maps FROM '__TEST_DIR__/assembled_maps.csv';;
SELECT '{a=1, b=2, c=3}'::MAP(VARCHAR, INT);
SELECT '{key_A=Duck, key_B="hello world"}'::MAP(VARCHAR, VARCHAR);
SELECT '{1=Duck, 2=hello world, 3=!}'::MAP(INT, VARCHAR);
SELECT '{greetings=[Hello World!, Hello DuckDB, Howdy], farewells=[Bye World, Bye DuckDB]}'::MAP(VARCHAR, VARCHAR[]);;
SELECT '{"key=A"=Duck, "key=B"="hello=world"}'::MAP(VARCHAR, VARCHAR);
SELECT '{{1=100, 2=200}=value}'::MAP(MAP(INT, INT), VARCHAR);;
SELECT '{{1=100, 2=200}={3=c, 5=e, 7=g}}'::MAP(MAP(INT, INT), MAP(INT, VARCHAR));;
SELECT col1::MAP(INT, VARCHAR) FROM stringMap;;
SELECT CAST('{''hello''=2, ''world''=50, ''!''=12}' AS MAP(VARCHAR, INT));;
SELECT CAST('{''''hello''''=hello, ''''world''''=world, ''''!''''=!}' AS MAP(VARCHAR, VARCHAR));;
SELECT CAST('{[[''🦆, 🦆, 🦆'']]=100, [[duck, db, ''🦆'']]=101}' AS MAP(VARCHAR[][], INT));;
SELECT CAST('{"can''t"="you''re", "i''m"="q''u''o''t''e"}' AS MAP(VARCHAR, VARCHAR));;
SELECT CAST('{"{"="}", "["="]"}' AS MAP(VARCHAR, VARCHAR));;
SELECT CAST('{''}''="{", '']''="["}' AS MAP(VARCHAR, VARCHAR));;
SELECT ' {greetings    =[    Hello World  !, Hello     DuckDB  , Howdy ]  ,      farewells=  [Bye World, Bye DuckDB  ] }    '::MAP(VARCHAR, VARCHAR[]);;
SELECT CAST('{ [12,     13,14]=val, [       8, 9         ]      =val, [ 4    ]=val   }' AS MAP(INT[], VARCHAR));;
SELECT CAST('   { { a:[2,    3], b:  Duckster      }=         {50.0        =50}, {a    : [9,1,4], b:Duck          }
                ={  1      =    0}  }' AS MAP(STRUCT(a INT[], b VARCHAR), MAP(INT, DOUBLE)));;
SELECT col1::MAP(VARCHAR, VARCHAR) FROM null_tbl;;
SELECT CAST(NULL AS MAP(INT, VARCHAR));;
SELECT CAST('{12=34, 56=NULL, 910=1112, 1314=NULL}' AS MAP(INT, INT));;
SELECT CAST('{}' AS MAP(INT, INT));;
SELECT TRY_CAST('Hello World' AS MAP(VARCHAR, VARCHAR));;
SELECT TRY_CAST(col1 AS MAP(INT, INT)) FROM try_cast_tbl;;
SELECT * FROM Duck_tbl WHERE list_contains(cast(col1 as MAP(INT, VARCHAR))[7], 'Duckster') ;;
SELECT col1::MAP(INT, VARCHAR) FROM Duck_tbl WHERE cardinality(cast(col1 as MAP(INT, VARCHAR))) < 3;;
SELECT CAST('{A={a:[12,13,14], b:"🦆", c:0.12}, B={a:[12,13,14], b:DuckDuck, c:9.03}}' AS MAP(VARCHAR, STRUCT(a INT[], b VARCHAR, c FLOAT)));;
SELECT CAST('{{a:Meow=Meow}={a:12, b:0.8, c:MeowMeow}, {a:Quack}={a:13, b:3.2, c:QuackQuack}}' AS MAP(STRUCT(a VARCHAR), STRUCT(a INT, b DOUBLE, c VARCHAR)));;
SELECT CAST('{{A:AAA}={a:[12,13,14], b:"🦆", c:{a:[[a], [b, c]], b:[123]}}}' AS MAP(STRUCT(A VARCHAR), STRUCT(a INT[], b VARCHAR, c STRUCT(a VARCHAR[][], b INT[]))));;
SELECT '{[[a, b], [c, d], [e]]= {a:2000}, [[aaa]]={a:100}, [[z],[y], [x]]={}}'::MAP(VARCHAR[][], STRUCT(a INT));;
SELECT CAST('{a=True, b=False, z=true, X=FALSE}' AS MAP(VARCHAR, BOOL));;
SELECT CAST('{True=[true, FALSE, true], False=[false, false, false]}' AS MAP(BOOL, BOOL[]));;
SELECT CAST('{0={a:1, b: 8.3}, 5.7={a:2, b: 3}}' AS MAP(${type}, STRUCT(a ${type}, b ${type})));;
SELECT CAST('{-9.01=9.13 ,3=0.00002}' AS MAP(${type}, ${type}));;
SELECT '{🦆=ok, duck=happy}'::MAP(VARCHAR, MOOD);
SELECT '{ok=happy, sad=ok}'::MAP(MOOD, MOOD);
SELECT MAX(CAST(col AS MAP(INT, INT))) FROM intMap;;
SELECT * FROM assembled_maps;;
