SET enable_seqscan = ON;
SET enable_indexscan = OFF;
SET enable_bitmapscan = OFF;
SET enable_seqscan = OFF;
SET enable_indexscan = ON;
SET enable_bitmapscan = OFF;
SET extra_float_digits = 0;
RESET extra_float_digits;
SET enable_seqscan = OFF;
SET enable_indexscan = OFF;
SET enable_bitmapscan = ON;
RESET enable_seqscan;
RESET enable_indexscan;
RESET enable_bitmapscan;
