PRAGMA enable_verification;
CREATE TABLE test (a INTEGER, b INTEGER);
INSERT INTO test VALUES (11, 22), (12, 21), (14, 22);
CREATE TABLE test2 (a INTEGER, b TINYINT);
INSERT INTO test2 VALUES (200, 60), (12, 60), (14, 60);
SELECT ALL CAST ( - SUM ( DISTINCT - CAST ( NULL AS INTEGER ) ) AS INTEGER ) FROM test;
SELECT b, AVG(a) FROM test GROUP BY b ORDER BY b;
SELECT SUM(b) FROM test2;
