SELECT * FROM vals;
SELECT * FROM vunion ORDER BY i;
SELECT * FROM vunion ORDER BY i LIMIT 1;
SELECT * FROM (SELECT * FROM vunion ORDER BY i LIMIT 4) tbl ORDER BY j LIMIT 2;
SELECT * FROM vunion WHERE i=1;
SELECT DISTINCT * FROM (SELECT * FROM vunion UNION ALL SELECT * FROM vunion) tbl ORDER BY 1;
SELECT * FROM (SELECT * FROM vunion INTERSECT SELECT * FROM vunion) tbl ORDER BY 1;
SELECT * FROM (SELECT * FROM vunion EXCEPT SELECT * FROM vunion) tbl;
