SELECT t, FIRST_VALUE(t) OVER w AS fv 
FROM t_time 
WINDOW w AS (ORDER BY t RANGE INTERVAL 2 HOUR PRECEDING);
SELECT sum(a) OVER (
    PARTITION BY (
SELECT t FROM map WHERE v=a
    ) ORDER BY a
  ) FROM tx ORDER BY ALL;
SELECT sum(a) OVER win FROM tx
  WINDOW win AS (
    PARTITION BY (
SELECT t FROM map WHERE v=a
    ) ORDER BY a
  ) ORDER BY ALL;
WITH map2 AS (
SELECT * FROM map
  )
SELECT sum(a) OVER (
    PARTITION BY (
SELECT t FROM map2 WHERE v=a
    ) ORDER BY a
  ) FROM tx ORDER BY ALL;
WITH map2 AS (
SELECT * FROM map
  )
SELECT sum(a) OVER win FROM tx
  WINDOW win AS (
    PARTITION BY (
SELECT t FROM map2 WHERE v=a
    ) ORDER BY a
  ) ORDER BY ALL;
SELECT b, sum(b) OVER (
    ORDER BY a NULLS LAST RANGE BETWEEN UNBOUNDED PRECEDING AND 10 FOLLOWING
  )
FROM (
	SELECT CASE WHEN b < 70 THEN NULL ELSE 10 END AS a, b
	FROM range(1, 129) tbl(b)
	) t1
ORDER BY 1;
