create table t1 (d date);
insert into t1 values (date_add(NULL, INTERVAL 1 DAY));
insert into t1 values (date_add('2000-01-04', INTERVAL NULL DAY));
insert into t1 values (date_add(NULL, INTERVAL 1 DAY));
insert into t1 values (date_add('2000-01-04', INTERVAL NULL DAY));
select * from t1;
drop table t1;
SELECT CAST('2006-09-26' AS DATE) + INTERVAL 1 DAY;
create table t1 (a int, b varchar(10));
insert into t1 values (1, '2001-01-01'),(2, '2002-02-02');
select '2007-01-01' + interval a day from t1;
select b + interval a day from t1;
drop table t1;
SELECT ADDDATE('8112-06-20', REPEAT('1', 32));
SELECT DATE(ts) = CURRENT_DATE + INTERVAL '1' DAY AS is_tomorrow, TIME(ts)
FROM (SELECT ADDDATE(TIME'00:00:00', INTERVAL 1 DAY) AS ts) AS dt;
prepare sd from "SELECT ADDDATE(?, INTERVAL 1 DAY)";
prepare st from "SELECT ADDDATE(?, INTERVAL 1 HOUR)";
prepare sd from "SELECT ADDDATE(?, INTERVAL 1 DAY)";
prepare st from "SELECT ADDDATE(?, INTERVAL 1 HOUR)";
prepare sd from "SELECT ADDDATE(?, INTERVAL 1 DAY)";
prepare st from "SELECT ADDDATE(?, INTERVAL 1 HOUR)";
SELECT ADDTIME(DATE'2021-01-01', '01:01:01');
prepare s from "SELECT ADDTIME(?, TIME'01:01:01')";
prepare s from "SELECT ADDTIME(?, TIME'01:01:01')";
prepare s from "SELECT ADDTIME(?, TIME'01:01:01')";
