CREATE TABLE t1 (i int) ENGINE=MYISAM;
INSERT INTO t1 VALUES (1), (3), (5);
SELECT * FROM t1;
CREATE TABLE t2 (i int) ENGINE=MYISAM;
INSERT INTO t2 VALUES (2), (4), (6);
SELECT * FROM t2;
UNLOCK TABLES;
DROP TABLE t1;
DROP TABLE t2;
