select @@global.concurrent_insert;
drop table if exists t0, t1, t2, t3, t4, t5;
drop view if exists v1, v2;
drop procedure if exists p1;
drop procedure if exists p2;
drop procedure if exists p3;
drop function if exists f1;
drop function if exists f2;
drop function if exists f3;
drop function if exists f4;
drop function if exists f5;
drop function if exists f6;
drop function if exists f7;
drop function if exists f8;
drop function if exists f9;
drop function if exists f10;
drop function if exists f11;
drop function if exists f12;
drop function if exists f13;
drop function if exists f14;
drop function if exists f15;
drop function if exists f16;
drop function if exists f17;
create table t1 (i int primary key);
insert into t1 values (1), (2), (3), (4), (5);
create table t2 (j int primary key);
insert into t2 values (1), (2), (3), (4), (5);
create table t3 (k int primary key);
insert into t3 values (1), (2), (3);
create table t4 (l int primary key);
insert into t4 values (1);
create table t5 (l int primary key);
insert into t5 values (1);
create view v1 as select i from t1;
create view v2 as select j from t2 where j in (select i from t1);
create procedure p1(k int) insert into t2 values (k);
lock table t1 write;
unlock tables;
lock table t1 write;
unlock tables;
drop view v1, v2;
drop procedure p1;
drop table t1, t2, t3, t4, t5;
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1(id INT);
CREATE TABLE t2(id INT);
SELECT * FROM t1;
SELECT COUNT(*) = 1 FROM information_schema.processlist
  WHERE state = "Waiting for table metadata lock" 
  AND info = "ALTER TABLE t1 ADD COLUMN j INT";
INSERT INTO t2 SELECT * FROM t1;
DROP TABLE t1, t2;
CREATE EVENT e1 ON SCHEDULE EVERY 5 HOUR DO SELECT 1;
CREATE EVENT e2 ON SCHEDULE EVERY 5 HOUR DO SELECT 2;
SELECT event_name FROM information_schema.events, performance_schema.global_variables
  WHERE definer = VARIABLE_VALUE;
DROP EVENT e2;
DROP TABLE IF EXISTS t1;
DROP VIEW IF EXISTS v1;
DROP FUNCTION IF EXISTS f1;
CREATE TABLE t1(a INT);
DROP TABLE t1;
drop table if exists t1;
drop table if exists t2;
create table t1 (a int, b int, unique key t1$a (a));
create table t2 (j int, k int);
select * from t1, t2;
select * from t1;
drop tables t1, t2;
CREATE TABLE t1 (i INT) ENGINE=InnoDB;
CREATE TABLE t2 (j INT) ENGINE=InnoDB;
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table metadata lock" and
        info = "RENAME TABLE t1 TO t3, t2 TO t1, t3 TO t2";
SELECT * FROM t1;
UNLOCK TABLES;
DROP TABLES t1, t2;
CREATE TABLE t1 (fld1 INT) ENGINE=InnoDB;
DROP TABLE t1;
