drop table if exists t1,t2,t3,t4;
drop table if exists t0,t5,t6,t7,t8,t9;
drop database if exists mysqltest;
drop view if exists v0, v1, v2, v3, v4;
create table T1 (id int primary key, Word varchar(40) not null, Index(Word));
create table t4 (id int primary key, Word varchar(40) not null);
INSERT INTO T1 VALUES (1, 'a'), (2, 'b'), (3, 'c');
INSERT INTO T4 VALUES(1,'match');
SELECT * FROM t1;
SELECT T1.id from T1 LIMIT 1;
SELECT T2.id from t1 as T2 LIMIT 1;
SELECT T2.id from t1 as t2 LIMIT 1;
select count(*) from T1;
select count(*) from t1;
drop table t1;
create database mysqltest;
create table t1 (a int);
alter table t1 rename to T1;
drop database mysqltest;
create table t2 (a int);
delete p1.*,P2.* from t1 as p1, t2 as p2 where p1.a=P2.a;
delete P1.*,p2.* from t1 as P1, t2 as P2 where P1.a=p2.a;
update t1 as p1, t2 as p2 SET p1.a=1,P2.a=1 where p1.a=P2.a;
update t1 as P1, t2 as P2 SET P1.a=1,p2.a=1 where P1.a=p2.a;
drop table t1,t2;
create table t1 (a int);
create table t2 (a int);
drop table t1, t2;
create table t1 (a int);
create table t2 like T1;
drop table t1, t2;
drop table if exists ÃÂÃÂ°,ÃÂÃÂ°ÃÂÃÂ°;
create table ÃÂÃÂ° (s1 int);
drop table ÃÂÃÂ°;
create table ÃÂÃÂ°ÃÂÃÂ° (s1 int);
drop table ÃÂÃÂ°ÃÂÃÂ°;
create database mysql_TEST;
drop database mysql_TEST;
SELECT @@general_log;
SELECT @@lower_case_table_names;
