drop table if exists t1,t2,t3,t4,t5,t03,t04;
create table t1 (word varchar(20));
create table t2 (id int auto_increment not null primary key);
insert into t1 values ("abirvalg");
insert into t2 values ();
insert into t1 values ("Alas");
select "--- Local --" as "";
drop table t1,t2;
create table if not exists t5 (a int);
select * from t5  /* must be (1),(1) */;
drop table t5;
create table t5 (c1 int, c2 varchar(128) character set latin1 not null);
insert into t5 values (1, date_format('2001-01-01','%W'));
insert into t5 values (2, date_format('2001-01-01','%W'));
insert into t5 values (3, date_format('2001-01-01','%W'));
select * from t5 order by c1;
drop table t5;
drop procedure if exists p1;
create table t1 (a varchar(64) character set utf8mb3);
select hex(a) from t1;
drop table t1;
CREATE TABLE t1 (c1 CHAR(10));
INSERT INTO t1 VALUES ('0123456789');
DROP TABLE t1;
CREATE TABLE patch (a BLOB);
SELECT COUNT(*) AS `BUG#28293_expect_3` FROM patch WHERE a LIKE '%Query%';
DROP TABLE patch;
CREATE TABLE t1(a INT);
INSERT INTO t1 VALUES(connection_id());
DROP TABLE t1;
CREATE DATABASE mysqltest1;
CREATE TABLE t1 (a INT, b CHAR(64));
INSERT INTO t1 VALUES (1,USER());
INSERT INTO t1 VALUES (1,USER());
SELECT * FROM t1;
DROP DATABASE mysqltest1;
DROP TABLE t1;
CREATE TABLE t1 SELECT 1;
DROP TABLE t1;
CREATE DATABASE test1;
CREATE TABLE t1(id int);
DROP DATABASE test1;
CREATE DATABASE test1;
DROP TABLE t1;
DROP DATABASE test1;
CREATE TABLE t1 (a INT);
DROP TABLE t1;
