drop schema if exists mysqltest_1;
create schema mysqltest_1;
create table t1 (a int) partition by list (a) (partition p1 values in (1), partition p2 values in (2), partition p3 values in (3));
insert into t1 values (1),(2);
alter table t1 add b int;
alter table t1 drop partition p2;
alter table t1 drop partition p3;
drop table t1;
create table t1 (s1 int);
insert into t1 values (1);
drop table t1;
drop schema mysqltest_1;
