drop temporary table if exists t1;
drop table if exists t1, t2;
drop procedure if exists p_verify_reprepare_count;
drop procedure if exists p1;
drop function if exists f1;
drop view if exists t1;
drop schema if exists mysqltest;
select variable_value from
  performance_schema.session_status where
  variable_name='com_stmt_reprepare'
  into @reprepare_count;
select '' as "SUCCESS";
drop table if exists t1;
create table t1 (a int, b int);
prepare stmt from "select a from t1";
alter table t1 add column c int;
alter table t1 drop column b;
alter table t1 comment "My best table";
drop table t1;
deallocate prepare stmt;
create table t1 (a int);
prepare stmt1 from "truncate t1";
prepare stmt2 from "select 1 as my_column from t1";
prepare stmt3 from "select 1 as my_column from (select * from t1) as t2";
prepare stmt4 from
"select 1 as my_column from (select 1) as t2 where exists (select 1 from t1)";
prepare stmt5 from "select * from (select 1 as b) as t2, t1";
prepare stmt6 from "select * from t1 union all select 1.5";
prepare stmt7 from "select 1 as my_column union all select 1 from t1";
prepare stmt8 from "insert into t1 values(1),(2)";
prepare stmt9 from "update t1 set a = 3 where a = 2";
prepare stmt10 from "delete from t1 where a = 1";
drop table t1;
create table t1 (a int, b int);
insert into t1 values(1,1),(2,2),(3,3);
create table t2 like t1;
insert into t1 values(2,2);
prepare stmt1 from "select a,b from t1";
prepare stmt2 from "select a,b from (select * from t1) as t1";
prepare stmt3 from "select * from t1 where a = 2 and b = 2";
prepare stmt4 from "select * from t2 where (a,b) in (select * from t1)";
prepare stmt5 from "select * from t1 union select * from t2";
prepare stmt6 from "select * from t1 union all select * from t2";
prepare stmt7 from "insert into t1 set a = 4, b = 4";
prepare stmt8 from "insert into t1 select * from t2";
alter table t1 drop column b;
alter table t2 add column c int;
drop table t1;
drop table t2;
create table t1 (a int, b int, primary key(b),unique index t1_unq_idx(a));
insert into t1 set a = 0, b = 0;
insert into t1 select a + 1, b + 1 from t1;
insert into t1 select a + 2, b + 2 from t1;
insert into t1 select a + 4, b + 4 from t1;
insert into t1 select a + 8, b + 8 from t1;
prepare stmt from "select avg(a) from t1";
alter table t1 drop index t1_unq_idx;
alter table t1 add unique index t1_unq_idx(a);
deallocate prepare stmt;
drop table t1;
create table t1 (a int);
prepare stmt from "insert into t1 values(1)";
drop table t1;
create view t1 as select 1;
drop view t1;
create table t2 (a int);
create view t1 as select * from t2 with check option;
select * from t1;
deallocate prepare stmt;
drop view t1;
drop table t2;
create temporary table t1 as select 1 as a;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
create schema mysqltest;
drop schema mysqltest;
drop temporary table t1;
create temporary table t1 as select 1 as a;
drop temporary table t1;
drop temporary table if exists t1;
drop table if exists t1, t2;
drop procedure if exists p_verify_reprepare_count;
drop procedure if exists p1;
drop function if exists f1;
drop view if exists t1;
drop schema if exists mysqltest;
