SELECT * FROM performance_schema.persisted_variables ORDER BY variable_name ASC;
SELECT @@global.partial_revokes;
SELECT @@global.auto_increment_increment;
SELECT @@global.net_buffer_length;
SELECT @@global.back_log;
SELECT * FROM performance_schema.persisted_variables ORDER BY variable_name ASC;
SELECT @@global.partial_revokes;
SELECT @@global.auto_increment_increment;
SELECT @@global.net_buffer_length;
SELECT @@global.back_log;
