CREATE TABLE t1 (c1 int,c2 char(10));
INSERT INTO t1 VALUES (1,'aaaaaaaaaa');
INSERT INTO t1 VALUES (2,'bbbbbbbbbb');
SELECT * FROM t1 ORDER BY c1;
DROP TABLE t1;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
