DROP VIEW IF EXISTS v1;
DROP VIEW IF EXISTS v2;
DROP VIEW IF EXISTS v3;
DROP TABLE IF EXISTS t1;
DROP PROCEDURE IF EXISTS p1;
DROP PROCEDURE IF EXISTS p2;
DROP PROCEDURE IF EXISTS p3;
DROP FUNCTION IF EXISTS f1;
DROP FUNCTION IF EXISTS f2;
DROP FUNCTION IF EXISTS f3;
CREATE TABLE t1(c INT);
CREATE VIEW v1 AS SELECT * FROM t1;
CREATE PROCEDURE p1()
  SELECT 1;
DROP VIEW v1;
DROP TABLE t1;
DROP PROCEDURE p1;
select count(*) from information_schema.COLUMN_PRIVILEGES;
