drop table if exists t1, t2;
create table t1 (a integer, b integer,c1 CHAR(10));
insert into t1 (a) values (1),(2);
select count(*) from t1;
insert into t1 values(1,2,"test");
select count(*) from t1;
delete from t1;
select * from t1;
drop table t1;
create temporary table t1 (n int);
insert into t1 values (1),(2),(3);
select * from t1;
drop table t1;
create table t1 (a integer auto_increment primary key);
insert into t1 (a) values (NULL),(NULL);
insert into t1 (a) values (NULL),(NULL);
SELECT * from t1;
delete from t1;
insert into t1 (a) values (NULL),(NULL);
SELECT * from t1;
drop table t1;
create temporary table t1 (a integer auto_increment primary key);
insert into t1 (a) values (NULL),(NULL);
insert into t1 (a) values (NULL),(NULL);
SELECT * from t1;
delete from t1;
insert into t1 (a) values (NULL),(NULL);
SELECT * from t1;
drop table t1;
create table t1 (s1 int);
insert into t1 (s1) values (1), (2), (3), (4), (5);
create view v1 as select * from t1;
drop view v1;
drop table t1;
CREATE TABLE t1 (c1 INT);
LOCK TABLE t1 WRITE;
INSERT INTO t1 VALUES (1);
SELECT * FROM t1;
SELECT * FROM t1;
UNLOCK TABLES;
LOCK TABLE t1 READ;
UNLOCK TABLES;
CREATE TABLE t2 (c1 INT);
LOCK TABLE t2 WRITE;
UNLOCK TABLES;
CREATE VIEW v1 AS SELECT t1.c1 FROM t1,t2 WHERE t1.c1 = t2.c1;
INSERT INTO t1 VALUES (1), (2), (3);
INSERT INTO t2 VALUES (1), (3), (4);
SELECT * FROM v1;
SELECT * FROM v1;
LOCK TABLE t1 WRITE;
UNLOCK TABLES;
LOCK TABLE t1 WRITE, t2 WRITE;
UNLOCK TABLES;
LOCK TABLE v1 WRITE;
SELECT * FROM v1;
SELECT * FROM v1;
UNLOCK TABLES;
LOCK TABLE t1 WRITE, t2 WRITE, v1 WRITE;
SELECT * FROM v1;
SELECT * FROM v1;
UNLOCK TABLES;
DROP VIEW v1;
DROP TABLE t1, t2;
CREATE PROCEDURE p1() SET @a = 5;
DROP PROCEDURE p1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 AS SELECT 1 AS f1;
DROP TABLE t1;
CREATE TABLE t1(a INT);
CREATE SCHEMA s1;
UNLOCK TABLES;
DROP TABLE t1;
DROP SCHEMA s1;
