SELECT IS_USED_LOCK('test') IS NULL AS expect_1;
SELECT IS_FREE_LOCK('test') = 1 AS expect_1;
SELECT RELEASE_LOCK('test') IS NULL AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 0 AS expect_1;
SELECT GET_LOCK('test', 0) = 1 AS expect_1;
SELECT IS_USED_LOCK('test') = CONNECTION_ID() AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT IS_USED_LOCK('test') = @aux AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT GET_LOCK('test', 0) = 0 expect_1;
SELECT RELEASE_LOCK('test') = 0 AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 0 AS expect_1;
SELECT RELEASE_LOCK('test') = 1 AS expect_1;
SELECT GET_LOCK('test1',0);
SELECT IS_USED_LOCK('test1') = CONNECTION_ID()
   AND IS_USED_LOCK('test2') = CONNECTION_ID() AS expect_1;
SELECT RELEASE_LOCK('test1') = 1 AS expect_1;
SELECT IS_FREE_LOCK('test1') = 1 AS expect_1;
SELECT IS_FREE_LOCK('test2') = 0 AS expect_1;
SELECT RELEASE_LOCK('test2') = 1 AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT IS_FREE_LOCK('test1') AND IS_FREE_LOCK('test2') AS expect_1;
SELECT IS_USED_LOCK('test1') = CONNECTION_ID()
   AND IS_USED_LOCK('test2') = CONNECTION_ID() AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT IS_USED_LOCK('test1') = CONNECTION_ID()
   AND IS_USED_LOCK('test2') = CONNECTION_ID() AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT IS_USED_LOCK('test1') = CONNECTION_ID()
   AND IS_USED_LOCK('test2') = CONNECTION_ID() AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT IS_USED_LOCK('test') <> CONNECTION_ID() AS expect_1;
SELECT RELEASE_LOCK('test') = 1 AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT IS_USED_LOCK('test') = CONNECTION_ID() AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT RELEASE_LOCK('test') = 1 AS expect_1;
SELECT IS_FREE_LOCK('test1') = 0 AS expect_1;
SELECT IS_FREE_LOCK('test1') = 1 AS expect_1;
SELECT RELEASE_LOCK('test2') + RELEASE_LOCK('test1') = 2 AS expect_1;
CREATE TABLE t1 (id INT);
LOCK TABLE t1 WRITE;
UNLOCK TABLES;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
UNLOCK TABLES;
SELECT (RELEASE_LOCK('test1') = 1) AND (RELEASE_LOCK('test3') IS NULL)
   AND (RELEASE_LOCK('test2') = 1) AS expect_1;
DELETE FROM t1;
INSERT INTO t1 SET id = 1;
INSERT INTO t1 SET id = 2;
SELECT RELEASE_ALL_LOCKS() = 2 AS expect_1;
SELECT id FROM t1 ORDER BY id;
DELETE FROM t1;
INSERT INTO t1 VALUES (1);
SELECT COUNT(*) = 1 AS expect_1 FROM t1 WHERE id = 1;
LOCK TABLE t1 WRITE;
SELECT COUNT(*) FROM t1;
SELECT RELEASE_LOCK('test') = 1 AS expect_1;
UNLOCK TABLES;
DELETE FROM t1;
INSERT INTO t1 VALUES(1),(2),(3);
SELECT RELEASE_LOCK(1) = 1 AS expect_1;
SELECT RELEASE_LOCK(2) = 1 AS expect_1;
SELECT RELEASE_LOCK(2) = 1 AS expect_1;
SELECT RELEASE_LOCK(3) = 1 AS expect_1;
SELECT RELEASE_ALL_LOCKS() = 0 AS expect_1;
DELETE FROM t1;
SELECT RELEASE_ALL_LOCKS();
DELETE FROM t1;
INSERT INTO t1 VALUES(1),(2),(3);
DELETE FROM t1;
INSERT INTO t1 VALUES(1),(2),(3);
SELECT @aux;
CREATE TABLE t2 (col1 INT, col2 INT, PRIMARY KEY(col1));
DELETE FROM t1;
INSERT INTO t1 VALUES(1),(2),(1);
SELECT * FROM t2;
DELETE FROM t1;
DELETE FROM t2;
INSERT INTO t1 VALUES(1),(1),(2);
SELECT * FROM t2;
DROP TABLE t2;
SELECT RELEASE_ALL_LOCKS() = 0 AS expect_1;
DROP TABLE t1;
SELECT GET_LOCK('test', 0), RELEASE_LOCK('test');
SELECT IS_FREE_LOCK('test') = 1 AS expect_1;
SELECT IS_FREE_LOCK('test') = 0 AS expect_1;
SELECT RELEASE_LOCK('test') = 1 AS expect_1;
SELECT GET_LOCK('test', 0), GET_LOCK('test1', 0), RELEASE_ALL_LOCKS(),
       GET_LOCK('test', 0);
SELECT RELEASE_ALL_LOCKS() = 1 AS expect_1;
CREATE TABLE t1 AS SELECT GET_LOCK('test', 0) AS g, RELEASE_LOCK('test') AS r,
RELEASE_ALL_LOCKS() AS ra, IS_USED_LOCK('test') AS isu,
                       IS_FREE_LOCK('test') AS isf;
DROP TABLE t1;
SELECT GET_LOCK(REPEAT('a', 64), 0) = 1 AS expect_1;
SELECT IS_USED_LOCK(REPEAT('a', 64)) = CONNECTION_ID() AS expect_1;
SELECT IS_FREE_LOCK(REPEAT('a', 64)) = 0 AS expect_1;
SELECT RELEASE_LOCK(REPEAT('a', 64)) = 1 AS expect_1;
SELECT IS_USED_LOCK('a') = CONNECTION_ID();
SELECT IS_USED_LOCK(_koi8r 0xd4c5d3d4) = CONNECTION_ID();
SELECT GET_LOCK("test", NULL) = 0 AS expect_1;
CREATE TABLE t1 (conn CHAR(7), connection_id INT);
INSERT INTO t1 VALUES ('default', CONNECTION_ID());
INSERT INTO t1 VALUES ('con1', CONNECTION_ID());
SELECT IS_USED_LOCK('bug16501') = connection_id
FROM t1
WHERE conn = 'default';
SELECT IS_USED_LOCK('bug16501') = CONNECTION_ID();
SELECT IS_USED_LOCK('bug16501') = connection_id
FROM t1
WHERE conn = 'con1';
SELECT IS_USED_LOCK('bug16501') = CONNECTION_ID();
DROP TABLE t1;
select * from(SELECT MIN(GET_LOCK(0,0) / 1 ^ 0)) as a;
select * from(SELECT MAX(RELEASE_LOCK(0) / 1 ^ 0)) as a;
select * from(SELECT MAX(RELEASE_ALL_LOCKS() / 1 ^ 0)) as a;
