SELECT * FROM test ORDER BY a;
SELECT a, b FROM test WHERE a=11 ORDER BY b;
SELECT a, b FROM test WHERE a>11 ORDER BY b;
SELECT * FROM test ORDER BY a;
SELECT * FROM test ORDER BY a;
SELECT a, b FROM test WHERE a=11 ORDER BY b;
SELECT a, b FROM test WHERE a>11 ORDER BY b;
SELECT * FROM test ORDER BY a;
