CREATE DATABASE db1_charset;
CREATE TABLE t_latin1(c CHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE t_utf8(c CHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
CREATE TABLE t_koi8r (c1 VARBINARY(255), c2 VARBINARY(255));
