DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1
(a INTEGER,
 b INTEGER NOT NULL,
 KEY (b));
DROP TABLE IF EXISTS t1;
CREATE TABLE t2
(a INTEGER,
 b INTEGER NOT NULL,
 KEY (b));
DROP TABLE IF EXISTS t2;
CREATE TABLE t1 (a SERIAL) ENGINE = InnoDB
PARTITION BY KEY ALGORITHM = 1 () PARTITIONS 3;
INSERT INTO t1 VALUES (10);
INSERT INTO t1 VALUES (5);
