drop table if exists t1, t2;
CREATE TABLE t1 (fld1 INT PRIMARY KEY) ENGINE= INNODB PARTITION BY HASH(fld1)
PARTITIONS 5;
DROP TABLE t1;
CREATE TABLE t1
(a INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
 b VARCHAR(200),
 c TEXT)
ENGINE=InnoDB
PARTITION BY HASH(a) PARTITIONS 1;
DROP TABLE t1;
CREATE TABLE t1 (
  i INT
)
ENGINE=InnoDB
PARTITION BY RANGE (i)
(PARTITION p3 VALUES LESS THAN (3),
 PARTITION p5 VALUES LESS THAN (5),
 PARTITION pMax VALUES LESS THAN MAXVALUE);
INSERT INTO t1 VALUES (1), (2), (3), (4), (5), (6);
ALTER TABLE t1 CHECKSUM = 1;
DROP TABLE t1;
CREATE TABLE t1 (
  i INT
) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1), (2), (3), (4), (5), (6);
ALTER TABLE t1 CHECKSUM = 1;
DROP TABLE t1;
CREATE TABLE t1
(a INT,
 b varchar(64),
 PRIMARY KEY (a),
 KEY (b))
ENGINE = InnoDB
PARTITION BY RANGE (a)
SUBPARTITION BY HASH (a) SUBPARTITIONS 10
(PARTITION pNeg VALUES LESS THAN (0),
 PARTITION p0 VALUES LESS THAN (1000),
 PARTITION pMAX VALUES LESS THAN MAXVALUE);
INSERT INTO t1 VALUES (-1, 'Only negative pk value');
INSERT INTO t1 VALUES (0, 'Mod Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'),
(10, 'Zero'), (11, 'Mod One'), (12, 'Mod Two'), (13, 'Mod Three'),
(20, '0'), (21, '1'), (22, '2'), (23, '3'),
(4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9');
INSERT INTO t1 SELECT a + 30, b FROM t1 WHERE a >= 0;
DROP TABLE t1;
CREATE TABLE t1 (a INT, KEY(a))
ENGINE = InnoDB
PARTITION BY KEY (a) PARTITIONS 1;
