CREATE TABLE t1(a INT, b INT NOT NULL) ENGINE=MyISAM;
CREATE VIEW v1 AS SELECT * FROM t1;
CREATE TABLE t2(a INT, b INT NOT NULL, c INT NOT NULL, d INT NOT NULL) ENGINE=MyISAM;
CREATE VIEW v2 AS SELECT * FROM t2;
CREATE TABLE t1_data(a INT, b INT) ENGINE=MyISAM;
INSERT INTO t1_data VALUES
  (11, 12),
  (NULL, 22),
  (31, NULL),
  (NULL, NULL);
CREATE TABLE t2_data(a INT, b INT, c INT, d INT) ENGINE=MyISAM;
INSERT INTO t2_data VALUES
  (11, 12, 13, 14),
  (NULL, 22, 23, 24),
  (31, NULL, 33, 34),
  (41, 42, NULL, 44),
  (51, 52, 53, NULL),
  (NULL, NULL, NULL, NULL);
INSERT INTO t1 SELECT * FROM t1_data;
INSERT INTO v1 SELECT a * 10, b * 10 FROM t1_data;
