ATTACH DATABASE ':memory:' AS db1;
ATTACH DATABASE ':memory:' AS db2;
CREATE TABLE db1.table_in_db1(i int);
CREATE TABLE db2.table_in_db2(i int);
CREATE SCHEMA db2.test_schema;
CREATE TABLE db2.test_schema.table_in_db2_test_schema(i int);
USE DB1;
USE db1;
USE db2;
USE db2.test_schema;
USE DB2.TEST_sChEmA;
FROM table_in_db2;
FROM table_in_db2_test_schema;
SHOW TABLES;
SHOW TABLES;
SHOW TABLES;
SHOW TABLES;
SHOW TABLES;
SHOW TABLES;
