PRAGMA enable_verification;
ATTACH DATABASE ':memory:' AS new_database;;
CREATE SCHEMA new_database.s1;;
CREATE TABLE ${prefix}.integers(i INTEGER);
INSERT INTO ${prefix}.integers VALUES (42);;
ALTER TABLE ${prefix}.integers ADD COLUMN j VARCHAR;
INSERT INTO ${prefix}.integers VALUES (1, 'T100');;
ALTER TABLE ${prefix}.integers ALTER j TYPE INT USING REPLACE(j, 'T', '')::INT;
ALTER TABLE ${prefix}.integers DROP COLUMN j;
ALTER TABLE ${prefix}.integers RENAME COLUMN i TO k;
DROP TABLE ${prefix}.integers;
CREATE TABLE ${prefix}.t1(i INTEGER);
ALTER TABLE ${prefix}.t1 RENAME TO t2;
SELECT * FROM ${prefix}.t2;
DROP TABLE ${prefix}.t2;
SELECT * FROM ${prefix}.integers;
UPDATE ${prefix}.integers SET i=i+1;
SELECT * FROM ${prefix}.integers;
DELETE FROM ${prefix}.integers WHERE i=43;
SELECT COUNT(*) FROM ${prefix}.integers;
SELECT * FROM ${prefix}.integers;
SELECT * FROM ${prefix}.integers;
SELECT * FROM ${prefix}.integers;
SELECT k FROM ${prefix}.integers;
