PRAGMA enable_verification;
BEGIN TRANSACTION;
CREATE TABLE item(i_category VARCHAR, i_brand VARCHAR, i_price INTEGER);
INSERT INTO item VALUES ('toys', 'fisher-price', 100);
ROLLBACK;
BEGIN TRANSACTION;
CREATE TABLE item(i_category VARCHAR, i_brand VARCHAR, i_item_sk INTEGER);
CREATE TABLE store(s_store_name VARCHAR, s_company_name VARCHAR, s_store_sk INTEGER);
CREATE TABLE date_dim(d_year INTEGER, d_moy INTEGER, d_date_sk INTEGER);
CREATE TABLE store_sales(ss_sales_price DECIMAL, ss_item_sk INTEGER, ss_sold_date_sk INTEGER, ss_store_sk INTEGER);
INSERT INTO item VALUES ('Music', 'exportischolar', 1);
INSERT INTO store VALUES ('ought', 'Unknown', 1);
INSERT INTO date_dim VALUES (1999, 1, 1);
INSERT INTO store_sales VALUES (2.8, 1, 1, 1);
ROLLBACK;
