PRAGMA enable_verification;
CREATE SCHEMA "SCH""EMA";
CREATE TYPE "EN""UM" AS ENUM('ALL');
CREATE TABLE "SCH""EMA"."TA""BLE"("COL""UMN" "EN""UM");
INSERT INTO "SCH""EMA"."TA""BLE" VALUES ('ALL');
DROP TABLE "SCH""EMA"."TA""BLE";
CREATE TABLE "SCH""EMA"."TA""BLE"("COL""UMN" ROW("SO""ME" ROW("I""N" INTEGER)));
INSERT INTO "SCH""EMA"."TA""BLE" VALUES ({'so"me': {'i"n': 3}});
