SET default_null_order='nulls_first';;
SET immediate_transaction_mode=true;
PRAGMA enable_verification;
PRAGMA enable_verification;
PRAGMA enable_verification;
PRAGMA enable_verification;
PRAGMA enable_verification;
PRAGMA enable_verification;
CREATE TABLE test (a INTEGER);;
INSERT INTO test VALUES (1), (2), (3);
BEGIN TRANSACTION;
BEGIN TRANSACTION;
BEGIN TRANSACTION;
BEGIN TRANSACTION;
BEGIN TRANSACTION;
UPDATE test SET a=99 WHERE a=1;
UPDATE test SET a=99 WHERE a=2;
UPDATE test SET a=99 WHERE a=3;
UPDATE test SET a=99 WHERE a IS NULL;
UPDATE test SET a=NULL WHERE a=1;
UPDATE test SET a=NULL WHERE a=2;
UPDATE test SET a=NULL WHERE a=3;
SELECT COUNT(*) FROM test WHERE a IS NULL;
UPDATE test SET a=99 WHERE a IS NULL;
SELECT * FROM test ORDER BY a;
SELECT * FROM test ORDER BY a;
SELECT * FROM test ORDER BY a;
SELECT * FROM test ORDER BY a;
SELECT * FROM test ORDER BY a;
