CREATE TABLE test (a VARCHAR);
INSERT INTO test VALUES ('abcdefghijklmnopqrstuvwxyz');
INSERT INTO test SELECT a||a||a||a||a||a||a||a||a||a FROM test;
DELETE FROM test WHERE length(a) = (SELECT MIN(length(a)) FROM test);
INSERT INTO test SELECT a||a||a||a||a||a||a||a||a||a FROM test;
DELETE FROM test WHERE length(a) = (SELECT MIN(length(a)) FROM test);
INSERT INTO test SELECT a||a||a||a||a||a||a||a||a||a FROM test;
DELETE FROM test WHERE length(a) = (SELECT MIN(length(a)) FROM test);
INSERT INTO test SELECT a||a||a||a||a||a||a||a||a||a FROM test;
DELETE FROM test WHERE length(a) = (SELECT MIN(length(a)) FROM test);
INSERT INTO test SELECT a||a||a||a||a||a||a||a||a||a FROM test;
DELETE FROM test WHERE length(a) = (SELECT MIN(length(a)) FROM test);
BEGIN TRANSACTION;
UPDATE test SET a='a';
COMMIT;
SELECT LENGTH(a) FROM test;
SELECT LENGTH(a) FROM test;
SELECT LENGTH(a) FROM test;
SELECT LENGTH(a) FROM test;
SELECT LENGTH(a) FROM test;
