CREATE TABLE test AS SELECT i AS a FROM range (2048, 5000, 1) t1(i);
INSERT INTO test VALUES (1), (2), (3);
CREATE TABLE src(b INTEGER);
INSERT INTO src VALUES (3), (2), (1), (4);
BEGIN TRANSACTION;
UPDATE src SET b = 10000 WHERE src.rowid = 0 OR src.rowid = 1 OR src.rowid = 3;
BEGIN TRANSACTION;
UPDATE src SET b = 20000 FROM test WHERE src.b = test.a;;
SELECT src.rowid sr, b, test.rowid tr, a FROM src, test WHERE src.b = test.a ORDER BY a;;
SELECT b FROM src;
