PRAGMA enable_verification;
CREATE TABLE integers(i INTEGER PRIMARY KEY, j INTEGER);
INSERT INTO integers VALUES (1, 3);
BEGIN TRANSACTION;
ROLLBACK;
DELETE FROM integers;
INSERT INTO integers VALUES (1, 2);
