create table copydml_test (id serial, t text);
insert into copydml_test (t) values ('a');
insert into copydml_test (t) values ('b');
insert into copydml_test (t) values ('c');
insert into copydml_test (t) values ('d');
insert into copydml_test (t) values ('e');
create rule qqq as on insert to copydml_test do instead nothing;
drop rule qqq on copydml_test;
create rule qqq as on insert to copydml_test do also delete from copydml_test;
drop rule qqq on copydml_test;
create rule qqq as on insert to copydml_test where new.t <> 'f' do instead delete from copydml_test;
drop rule qqq on copydml_test;
create rule qqq as on update to copydml_test do instead nothing;
drop rule qqq on copydml_test;
create rule qqq as on update to copydml_test do also delete from copydml_test;
drop rule qqq on copydml_test;
create rule qqq as on update to copydml_test where new.t <> 'f' do instead delete from copydml_test;
drop rule qqq on copydml_test;
create rule qqq as on delete to copydml_test do instead nothing;
drop rule qqq on copydml_test;
create rule qqq as on delete to copydml_test do also insert into copydml_test default values;
drop rule qqq on copydml_test;
create rule qqq as on delete to copydml_test where old.t <> 'f' do instead insert into copydml_test default values;
drop rule qqq on copydml_test;
drop table copydml_test;
