REVOKE ALL PRIVILEGES ON tenant_table FROM PUBLIC;
DROP INDEX tenant_idx;
ALTER TABLE tenant_table ADD COLUMN t text;
DROP TABLE tenant_table;
DROP VIEW tenant_view;
SET createrole_self_grant = 'set, inherit';
CREATE TABLE tenant2_table (i integer);
REVOKE ALL PRIVILEGES ON tenant2_table FROM PUBLIC;
DROP TABLE tenant2_table;
RESET SESSION AUTHORIZATION;
