SELECT lo_create(42);
GRANT SELECT ON LARGE OBJECT 42 TO public;
COMMENT ON LARGE OBJECT 42 IS 'the ultimate answer';
RESET SESSION AUTHORIZATION;
CREATE TABLE lotest_stash_values (loid oid, fd integer);
INSERT INTO lotest_stash_values (loid) SELECT lo_creat(42);
BEGIN;
UPDATE lotest_stash_values SET fd = lo_open(loid, CAST(x'20000' | x'40000' AS integer));
END;
BEGIN;
UPDATE lotest_stash_values SET fd=lo_open(loid, CAST(x'20000' | x'40000' AS integer));
SELECT lo_lseek(fd, 104, 0) FROM lotest_stash_values;
SELECT lowrite(fd, 'n') FROM lotest_stash_values;
SELECT lo_tell(fd) FROM lotest_stash_values;
END;
BEGIN;
SELECT lo_open(loid, x'40000'::int) from lotest_stash_values;
ABORT;
BEGIN;
UPDATE lotest_stash_values SET fd=lo_open(loid, CAST(x'20000' | x'40000' AS integer));
SELECT lo_truncate(fd, 11) FROM lotest_stash_values;
SELECT lo_close(fd) FROM lotest_stash_values;
END;
BEGIN;
UPDATE lotest_stash_values SET fd = lo_open(loid, CAST(x'20000' | x'40000' AS integer));
SELECT lo_lseek64(fd, 4294967296, 0) FROM lotest_stash_values;
SELECT lo_tell64(fd) FROM lotest_stash_values;
SELECT lo_truncate64(fd, 5000000000) FROM lotest_stash_values;
END;
SELECT lo_unlink(loid) from lotest_stash_values;
TRUNCATE lotest_stash_values;
BEGIN;
UPDATE lotest_stash_values SET fd=lo_open(loid, CAST(x'20000' | x'40000' AS integer));
SELECT loread(fd, 36) FROM lotest_stash_values;
END;
TRUNCATE lotest_stash_values;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
START TRANSACTION READ ONLY;
ROLLBACK;
DROP TABLE lotest_stash_values;
