SELECT obj_description(s.oid, 'pg_subscription') FROM pg_subscription s;
SELECT subname, stats_reset IS NULL stats_reset_is_null FROM pg_stat_subscription_stats WHERE subname = 'regress_testsub';
SELECT subname, stats_reset IS NULL stats_reset_is_null FROM pg_stat_subscription_stats WHERE subname = 'regress_testsub';
BEGIN;
COMMIT;
RESET ROLE;
BEGIN;
COMMIT;
BEGIN;
COMMIT;
DROP SUBSCRIPTION IF EXISTS regress_testsub;
BEGIN;
END;
BEGIN;
END;
CREATE FUNCTION func() RETURNS VOID AS
$$ ALTER SUBSCRIPTION regress_testsub SET PUBLICATION mypub WITH (refresh = true) $$ LANGUAGE SQL;
DROP FUNCTION func;
RESET SESSION AUTHORIZATION;
RESET SESSION AUTHORIZATION;
RESET SESSION AUTHORIZATION;
RESET SESSION AUTHORIZATION;
RESET SESSION AUTHORIZATION;
RESET SESSION AUTHORIZATION;
