CREATE TABLE t1(a INTEGER PRIMARY KEY);
CREATE TABLE t2(b INTEGER PRIMARY KEY, c INTEGER);
CREATE TABLE t3(d INTEGER);
INSERT INTO t1 VALUES(1),(2),(3);
INSERT INTO t2 VALUES(3, 1);
INSERT INTO t2 VALUES(4, 2);
INSERT INTO t2 VALUES(5, 3);
INSERT INTO t3 VALUES(4),(3),(5);
