CREATE TABLE log(x, a, b);
CREATE TABLE tbl(a, b);
CREATE TABLE t1(a, b);
CREATE VIEW v1 AS SELECT * FROM tbl;
CREATE INDEX i1 ON tbl(a);
INSERT INTO tbl VALUES(1, 2);
UPDATE tbl SET b=a+b, a=a+1;
DELETE FROM tbl;
