PRAGMA foreign_keys = on;
PRAGMA foreign_keys = on;
CREATE TABLE t1(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t2(c REFERENCES t1(a)  , d);
CREATE TABLE t3(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t4(c REFERENCES t3 , d);
CREATE TABLE t7(a, b INT PRIMARY KEY) WITHOUT rowid;
CREATE TABLE t8(c REFERENCES t7 , d);
CREATE TABLE t9(a REFERENCES nosuchtable, b);
CREATE TABLE t10(a REFERENCES t9(c) , b);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t1 VALUES(1, 2);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t2 VALUES(1, 3);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t2 VALUES(NULL, 4);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=NULL WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t1 SET a = 1;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t3 VALUES(1, 2);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t4 VALUES(1, 3);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t7 VALUES(2, 1);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t8 VALUES(1, 3);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t8 VALUES(NULL, 4);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t8 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t8 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t8 SET c=NULL WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t7 SET b = 1;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t7 SET a = 10;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_keys = OFF;
DROP table "t1";
DROP table "t2";
DROP table "t3";
DROP table "t4";
DROP table "t7";
DROP table "t8";
DROP table "t9";
DROP table "t10";
PRAGMA foreign_keys = on;
CREATE TABLE t1(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t2(c REFERENCES t1(a) DEFERRABLE INITIALLY DEFERRED , d);
CREATE TABLE t3(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t4(c REFERENCES t3 DEFERRABLE INITIALLY DEFERRED, d);
CREATE TABLE t7(a, b INT PRIMARY KEY) WITHOUT rowid;
CREATE TABLE t8(c REFERENCES t7 DEFERRABLE INITIALLY DEFERRED, d);
CREATE TABLE t9(a REFERENCES nosuchtable, b);
CREATE TABLE t10(a REFERENCES t9(c) DEFERRABLE INITIALLY DEFERRED, b);
INSERT INTO t1 VALUES(1, 2);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
INSERT INTO t2 VALUES(1, 3);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=1 WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
UPDATE t2 SET c=NULL WHERE d=4;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
DROP table "t8";
DROP table "t9";
DROP table "t10";
PRAGMA foreign_keys = on;
CREATE TABLE t8(c REFERENCES t7 , d);
CREATE TABLE t9(a REFERENCES nosuchtable, b);
CREATE TABLE t10(a REFERENCES t9(c) , b);
PRAGMA count_changes = 1;
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA foreign_key_check(t1);
PRAGMA foreign_key_check(t2);
PRAGMA foreign_key_check(t3);
PRAGMA foreign_key_check(t4);
PRAGMA foreign_key_check(t7);
PRAGMA foreign_key_check(t8);
PRAGMA count_changes = 0;
PRAGMA foreign_keys = OFF;
DROP table "t1";
DROP table "t2";
DROP table "t3";
DROP table "t4";
DROP table "t7";
DROP table "t8";
DROP table "t9";
DROP table "t10";
PRAGMA foreign_keys = on;
CREATE TABLE t1(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t2(c REFERENCES t1(a)  , d);
CREATE TABLE t3(a PRIMARY KEY, b) WITHOUT rowid;
CREATE TABLE t4(c REFERENCES t3 , d);
CREATE TABLE t7(a, b INT PRIMARY KEY) WITHOUT rowid;
CREATE TABLE t8(c REFERENCES t7 , d);
CREATE TABLE t9(a REFERENCES nosuchtable, b);
CREATE TABLE t10(a REFERENCES t9(c) , b);
PRAGMA count_changes = 1;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
BEGIN;
PRAGMA count_changes = 0;
PRAGMA foreign_keys = OFF;
DROP table "t1";
DROP table "t2";
DROP table "t3";
DROP table "t4";
DROP table "t7";
DROP table "t8";
DROP table "t9";
DROP table "t10";
CREATE TABLE i(i INT PRIMARY KEY) WITHOUT rowid;
CREATE TABLE j(j REFERENCES i);
INSERT INTO i VALUES(35);
INSERT INTO j VALUES('35.0');
