pragma auto_vacuum;
pragma auto_vacuum = 'full';
pragma auto_vacuum;
pragma auto_vacuum = 'incremental';
pragma auto_vacuum;
pragma auto_vacuum = 'invalid';
pragma auto_vacuum;
pragma auto_vacuum = 1;
pragma auto_vacuum;
pragma auto_vacuum = '2';
pragma auto_vacuum;
pragma auto_vacuum = 5;
pragma auto_vacuum;
pragma auto_vacuum = 1;
CREATE TABLE abc(a, b, c);
pragma auto_vacuum = 'none';
pragma auto_vacuum;
pragma auto_vacuum;
pragma auto_vacuum = 'incremental';
pragma auto_vacuum;
pragma auto_vacuum = 'full';
pragma auto_vacuum;
pragma auto_vacuum;
PRAGMA auto_vacuum = 2;
BEGIN;
CREATE TABLE tbl2(str);
DROP TABLE abc;
DELETE FROM tbl2;
PRAGMA auto_vacuum = 1;
INSERT INTO tbl2 VALUES('hello world');
PRAGMA auto_vacuum = 2;
CREATE TABLE tbl1(a, b, c);
DELETE FROM tbl2;
DROP TABLE tbl1;
BEGIN;
DROP TABLE tbl2;
PRAGMA incremental_vacuum;
BEGIN;
CREATE TABLE tbl1(a);
PRAGMA incremental_vacuum;
BEGIN;
INSERT INTO tbl1 SELECT * FROM tbl1;
DELETE FROM tbl1 WHERE oid%2;
BEGIN;
PRAGMA incremental_vacuum;
CREATE TABLE tbl2(b);
INSERT INTO tbl2 VALUES('a nice string');
