PRAGMA journal_mode;
PRAGMA main.journal_mode;
PRAGMA temp.journal_mode;
PRAGMA journal_mode = persist;
PRAGMA journal_mode;
PRAGMA main.journal_mode;
PRAGMA temp.journal_mode;
PRAGMA journal_mode = off;
PRAGMA journal_mode = off;
PRAGMA journal_mode;
PRAGMA main.journal_mode;
PRAGMA temp.journal_mode;
PRAGMA journal_mode = delete;
PRAGMA journal_mode;
PRAGMA main.journal_mode;
PRAGMA Temp.journal_mode;
PRAGMA journal_mode = truncate;
PRAGMA journal_mode;
PRAGMA main.journal_mode;
PRAGMA temp.journal_mode;
PRAGMA journal_mode = off;
PRAGMA journal_mode = invalid;
PRAGMA journal_mode = PERSIST;
