CREATE TABLE t0(xyz INTEGER);
INSERT INTO t0(xyz) VALUES(456);
CREATE VIEW v2(a, B) AS 
        SELECT 'a', 'B' COLLATE NOCASE FROM t0;
CREATE TABLE t2(a, B COLLATE NOCASE);
INSERT INTO t2 VALUES('a', 'B');
CREATE VIEW v3(a, B) AS
        SELECT 'a' COLLATE BINARY, 'B' COLLATE NOCASE FROM t0;
CREATE VIEW v4(a, B) AS
        SELECT 'a', +CAST('B' COLLATE NOCASE AS TEXT) FROM t0;
CREATE VIEW v5(a, B) AS
        SELECT 'a', ('B' COLLATE NOCASE) || '' FROM t0;
