CREATE TABLE persons(person_id, name);
INSERT INTO persons VALUES(1,'fred');
INSERT INTO persons VALUES(2,'barney');
INSERT INTO persons VALUES(3,'wilma');
INSERT INTO persons VALUES(4,'pebbles');
INSERT INTO persons VALUES(5,'bambam');
CREATE TABLE directors(person_id);
INSERT INTO directors VALUES(5);
INSERT INTO directors VALUES(3);
CREATE TABLE writers(person_id);
INSERT INTO writers VALUES(2);
INSERT INTO writers VALUES(3);
INSERT INTO writers VALUES(4);
