SELECT * FROM integers WHERE TRUE ORDER BY 1;
SELECT * FROM integers WHERE FALSE ORDER BY 1;
SELECT * FROM integers WHERE NULL ORDER BY 1;
SELECT * FROM integers WHERE a=2 AND a=2;
SELECT * FROM integers WHERE a=2 AND a>0;
SELECT * FROM integers WHERE a>0 AND a=2;
SELECT * FROM integers WHERE a=2 AND a<4;
SELECT * FROM integers WHERE a<4 AND a=2;
SELECT * FROM integers WHERE a=2 AND a<=2;
SELECT * FROM integers WHERE a=2 AND a>=2;
SELECT * FROM integers WHERE a>2 AND a>4;
SELECT * FROM integers WHERE a>4 AND a>2;
SELECT * FROM integers WHERE a>4 AND a>=4;
SELECT * FROM integers WHERE a>=4 AND a>4;
SELECT * FROM integers WHERE a<2 AND a<4;
SELECT * FROM integers WHERE a<4 AND a<2;
SELECT * FROM integers WHERE a<2 AND a<=2;
SELECT * FROM integers WHERE a<=2 AND a<2;
SELECT * FROM integers WHERE a<2 AND a<>3;
SELECT * FROM integers WHERE a<=1 AND a<>3;
SELECT * FROM integers WHERE a>4 AND a<>2;
SELECT * FROM integers WHERE a>=5 AND a<>2;
SELECT * FROM integers WHERE a>=4 AND a<>4 AND a<>4;
SELECT * FROM integers WHERE a<3 AND a<4 AND a<5 AND a<10 AND a<2 AND a<20;
SELECT * FROM integers WHERE a=2 AND a=4;
SELECT * FROM integers WHERE a=2 AND a>4;
SELECT * FROM integers WHERE a>4 AND a=2;
SELECT * FROM integers WHERE a=2 AND a>2;
SELECT * FROM integers WHERE a>=4 AND a=2;
SELECT * FROM integers WHERE a=4 AND a<2;
SELECT * FROM integers WHERE a<2 AND a=4;
SELECT * FROM integers WHERE a=2 AND a<2;
SELECT * FROM integers WHERE a<=2 AND a=4;
SELECT * FROM integers WHERE a<2 AND a>4;
SELECT * FROM integers WHERE a=2 AND a<>2;
SELECT * FROM integers WHERE a<>2 AND a=2;
SELECT * FROM integers WHERE 0;
SELECT * FROM integers WHERE a<2 AND 0;
SELECT * FROM strings WHERE s='hello' AND s='hello';
SELECT * FROM strings WHERE s='hello' AND s='world';
SELECT * FROM strings WHERE s='hello' AND s<>'hello';
SELECT * FROM strings WHERE s='hello' AND s<>'world';
SELECT * FROM strings WHERE s='hello' AND s>'a';
SELECT * FROM strings WHERE s='hello' AND s>='hello';
SELECT * FROM strings WHERE s='hello' AND s<='hello';
SELECT * FROM strings WHERE s='hello' AND s<'z';
SELECT * FROM strings WHERE s='hello' AND s<='a';
SELECT * FROM strings WHERE s='hello' AND s<'hello';
SELECT * FROM strings WHERE s='hello' AND s>'hello';
SELECT * FROM strings WHERE s='hello' AND s>='z';
SELECT * FROM strings WHERE s<>'hello' AND s<='a';
SELECT * FROM strings WHERE s<>'hello' AND s<'hello';
SELECT * FROM strings WHERE s<>'hello' AND s>'hello';
SELECT * FROM strings WHERE s<>'world' AND s>='hello';
