SELECT * FROM vals1 WHERE i=5 AND j>=i;
SELECT * FROM vals1 WHERE i>9 AND j>=i;
SELECT * FROM vals1 WHERE i>=10 AND j>=i;
SELECT * FROM vals1 WHERE i<1 AND j>=i;
SELECT * FROM vals1 WHERE i<=0 AND j>=i;
SELECT * FROM vals1 WHERE i=5 AND j<=i;
SELECT * FROM vals1 WHERE i>9 AND j<=i;
SELECT * FROM vals1 WHERE i>=10 AND j<=i;
SELECT * FROM vals1 WHERE i<1 AND j<=i;
SELECT * FROM vals1 WHERE i<=0 AND j<=i;
SELECT * FROM vals1 WHERE i=5 AND j>i;
SELECT * FROM vals1 WHERE i>9 AND j>i;
SELECT * FROM vals1 WHERE i>=10 AND j>i;
SELECT * FROM vals1 WHERE i<1 AND j>i;
SELECT * FROM vals1 WHERE i<=0 AND j>i;
SELECT * FROM vals1 WHERE i=5 AND j<i;
SELECT * FROM vals1 WHERE i>9 AND j<i;
SELECT * FROM vals1 WHERE i>=10 AND j<i;
SELECT * FROM vals1 WHERE i<1 AND j<i;
SELECT * FROM vals1 WHERE i<=0 AND j<i;
SELECT * FROM vals1 WHERE j>=i AND i=5;
SELECT * FROM vals1 WHERE j>=i AND i>9;
SELECT * FROM vals1 WHERE j>=i AND i>=10;
SELECT * FROM vals1 WHERE j>=i AND i<1;
SELECT * FROM vals1 WHERE j>=i AND i<=0;
SELECT * FROM vals1 WHERE j<=i AND i=5;
SELECT * FROM vals1 WHERE j<=i AND i>9;
SELECT * FROM vals1 WHERE j<=i AND i>=10;
SELECT * FROM vals1 WHERE j<=i AND i<1;
SELECT * FROM vals1 WHERE j<=i AND i<=0;
SELECT * FROM vals1 WHERE j>i AND i=5;
SELECT * FROM vals1 WHERE j>i AND i>9;
SELECT * FROM vals1 WHERE j>i AND i>=10;
SELECT * FROM vals1 WHERE j>i AND i<1;
SELECT * FROM vals1 WHERE j>i AND i<=0;
SELECT * FROM vals1 WHERE j<i AND i=5;
SELECT * FROM vals1 WHERE j<i AND i>9;
SELECT * FROM vals1 WHERE j<i AND i>=10;
SELECT * FROM vals1 WHERE j<i AND i<1;
SELECT * FROM vals1 WHERE j<i AND i<=0;
SELECT * FROM vals1, vals2 WHERE i>9 AND j<=l AND k>=i AND l<11
ORDER BY 2 DESC, 4 DESC;
SELECT * FROM vals1, vals2 WHERE i>9 AND j>=i AND k>=j ORDER by l;
SELECT * FROM vals1, vals2 WHERE i>9 AND k>=j AND j>=i AND l>=k;
SELECT * FROM vals1, vals2 WHERE i<1 AND k<=j AND j<=i AND l<=k;
