CREATE TABLE test (a INTEGER, b INTEGER);
INSERT INTO test VALUES (11, 22), (13, 22);
CREATE INDEX i_index ON test using art(a);
INSERT INTO test VALUES (11, 24);
DELETE FROM test WHERE a=11 AND b=24;
INSERT INTO test VALUES (11, 24);
DELETE FROM test WHERE a=11 AND b=22;
UPDATE test SET b=22 WHERE a=11;
