PREPARE s1 AS SELECT CAST(? AS INTEGER), CAST(? AS STRING);
DEALLOCATE s1;
PREPARE s1 AS SELECT CAST(?1 AS INTEGER), CAST(?2 AS STRING);
DEALLOCATE s1;
PREPARE s1 AS SELECT CAST(?2 AS INTEGER), CAST(?1 AS STRING);
DEALLOCATE s1;
EXECUTE s1(42, 'dpfkg');
EXECUTE s1(42, 'dpfkg');
EXECUTE s1('dpfkg', 42);
