SET replication_alter_partitions_sync = 2;
SET insert_keeper_fault_injection_probability=0;
SELECT '*** Not partitioned ***';
DROP TABLE IF EXISTS not_partitioned_replica1_00502 SYNC;
DROP TABLE IF EXISTS not_partitioned_replica2_00502 SYNC;
SELECT 'Parts before OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'not_partitioned_replica1_00502' AND active ORDER BY name;
SELECT 'Parts after OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'not_partitioned_replica2_00502' AND active ORDER BY name;
SELECT 'Sum before DETACH PARTITION:';
SELECT 'Sum after DETACH PARTITION:';
SELECT '*** Partitioned by week ***';
DROP TABLE IF EXISTS partitioned_by_week_replica1 SYNC;
DROP TABLE IF EXISTS partitioned_by_week_replica2 SYNC;
SELECT 'Parts before OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_week_replica1' AND active ORDER BY name;
SELECT 'Parts after OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_week_replica2' AND active ORDER BY name;
SELECT 'Sum before DROP PARTITION:';
SELECT 'Sum after DROP PARTITION:';
SELECT '*** Partitioned by a (Date, UInt8) tuple ***';
DROP TABLE IF EXISTS partitioned_by_tuple_replica1_00502 SYNC;
DROP TABLE IF EXISTS partitioned_by_tuple_replica2_00502 SYNC;
SELECT 'Parts before OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_tuple_replica1_00502' AND active ORDER BY name;
SELECT 'Parts after OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_tuple_replica2_00502' AND active ORDER BY name;
SELECT 'Sum before DETACH PARTITION:';
SELECT 'Sum after DETACH PARTITION:';
SELECT '*** Partitioned by String ***';
DROP TABLE IF EXISTS partitioned_by_string_replica1 SYNC;
DROP TABLE IF EXISTS partitioned_by_string_replica2 SYNC;
SELECT 'Parts before OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_string_replica1' AND active ORDER BY name;
SELECT 'Parts after OPTIMIZE:';
SELECT partition, name FROM system.parts WHERE database = currentDatabase() AND table = 'partitioned_by_string_replica2' AND active ORDER BY name;
SELECT 'Sum before DROP PARTITION:';
SELECT 'Sum after DROP PARTITION:';
SELECT '*** Table without columns with fixed size ***';
DROP TABLE IF EXISTS without_fixed_size_columns_replica1 SYNC;
DROP TABLE IF EXISTS without_fixed_size_columns_replica2 SYNC;
SELECT 'Parts:';
SELECT partition, name, rows FROM system.parts WHERE database = currentDatabase() AND table = 'without_fixed_size_columns_replica2' AND active ORDER BY name;
SELECT 'Before DROP PARTITION:';
SELECT 'After DROP PARTITION:';
