select '----HORIZONTAL MERGE TESTS----';
DROP TABLE IF EXISTS zero_rows_per_granule1;
DROP TABLE IF EXISTS zero_rows_per_granule2;
SELECT 'Replica synced';
SELECT distinct(marks) from system.parts WHERE table = 'zero_rows_per_granule1' and database=currentDatabase() and active=1;
SELECT 'Parts optimized';
SELECT 'Replica synced';
DROP TABLE IF EXISTS zero_rows_per_granule1;
DROP TABLE IF EXISTS zero_rows_per_granule2;
SELECT '-----';
DROP TABLE IF EXISTS four_rows_per_granule1;
DROP TABLE IF EXISTS four_rows_per_granule2;
SELECT 'Replica synced';
SELECT 'Table attached';
SELECT 'Parts optimized';
SELECT 'Replica synced';
DROP TABLE IF EXISTS four_rows_per_granule1;
DROP TABLE IF EXISTS four_rows_per_granule2;
SELECT '-----';
DROP TABLE IF EXISTS adaptive_granularity_alter1;
DROP TABLE IF EXISTS adaptive_granularity_alter2;
SELECT 'Replica synced';
SELECT 'Replica synced';
SELECT 'Parts optimized';
SELECT sum(marks) from system.parts WHERE table = 'adaptive_granularity_alter1' and database=currentDatabase() and active=1;
SELECT 'Replica synced';
DROP TABLE IF EXISTS adaptive_granularity_alter1;
DROP TABLE IF EXISTS adaptive_granularity_alter2;
