select 'Zero offset';
select 'Nullable values';
select 'Result with different type';
select 'Offset > block';
select 'Abs(Offset) > block';
select 'Positive offset';
select 'Negative offset';
select 'Positive offset with defaults';
select 'Negative offset with defaults';
select 'Positive offset with const defaults';
select 'Negative offset with const defaults';
select 'Dynamic column and offset, out of bounds';
select 'Dynamic column and offset, negative';
select 'Dynamic column and offset, without defaults';
select 'Constant column';
