DROP TABLE IF EXISTS r1;
DROP TABLE IF EXISTS r2;
SYSTEM STOP REPLICATED SENDS r1;
SYSTEM STOP REPLICATED SENDS r2;
SELECT '---';
SYSTEM START REPLICATED SENDS r1;
SYSTEM START REPLICATED SENDS r2;
SELECT '---';
