set short_circuit_function_evaluation = 'enable';
set convert_query_to_cnf = 0;
select if(number > 0, intDiv(number + 100, number), throwIf(number)) from numbers(10);
select multiIf(number == 0, 0, number == 1, intDiv(1, number), number == 2, intDiv(1, number - 1), number == 3, intDiv(1, number - 2), intDiv(1, number - 3)) from numbers(10);
select number != 0 and intDiv(1, number) == 0 and number != 2 and intDiv(1, number - 2) == 0 from numbers(10);
select count() from (select if(number >= 0, number, sleep(1)) from numbers(10000000));
select number > 0 and 5 and intDiv(100, number) from numbers(5);
select sum(number) FROM numbers(10) WHERE number != 0 and 3 % number and number != 1 and intDiv(1, number - 1) > 0;
select toTypeName(toString(number)) from numbers(5);
select toColumnTypeName(toString(number)) from numbers(5);
select Null or isNull(intDiv(number, 1)) from numbers(5);
set compile_expressions = 1;
select if(isNull(x), Null, 42 / x) from (select CAST(materialize(Null), 'Nullable(Decimal32(2))') as x);
select number % 2 and toLowCardinality(number) from numbers(5);
