SELECT 'IPv4 functions';
SELECT IPv4StringToNumOrDefault('test');
SELECT IPv4StringToNumOrNull('test');
SELECT IPv4StringToNum('127.0.0.1');
SELECT '--';
SELECT toIPv4OrDefault('test');
SELECT toIPv4OrNull('test');
SELECT toIPv4('127.0.0.1');
SELECT '--';
SELECT '--';
SELECT cast('127.0.0.1' , 'IPv4');
SELECT '--';
SET cast_ipv4_ipv6_default_on_conversion_error = 1;
SET cast_ipv4_ipv6_default_on_conversion_error = 0;
SELECT 'IPv6 functions';
SELECT IPv6StringToNumOrDefault('test');
SELECT IPv6StringToNumOrNull('test');
SELECT IPv6StringToNum('::ffff:127.0.0.1');
SELECT '--';
SELECT toIPv6OrDefault('test');
SELECT toIPv6OrNull('test');
SELECT toIPv6('::ffff:127.0.0.1');
SELECT count() FROM numbers_mt(100000000) WHERE NOT ignore(toIPv6OrZero(randomString(8)));
SELECT '--';
SELECT '--';
SET cast_ipv4_ipv6_default_on_conversion_error = 1;
SELECT '--';
SET cast_ipv4_ipv6_default_on_conversion_error = 0;
SELECT toFixedString('::1', 5) as value, cast(value, 'IPv6'), toIPv6(value);
