SET allow_experimental_inverted_index = 1;
SET log_queries = 1;
SET merge_tree_read_split_ranges_into_intersecting_and_non_intersecting_injection_probability = 0.0;
SELECT 'Test inverted(2)';
DROP TABLE IF EXISTS tab;
SELECT name, type FROM system.data_skipping_indices WHERE table =='tab' AND database = currentDatabase() LIMIT 1;
SELECT 'Test inverted()';
DROP TABLE IF EXISTS tab_x;
SELECT name, type FROM system.data_skipping_indices WHERE table == 'tab_x' AND database = currentDatabase() LIMIT 1;
SELECT 'Test on array columns';
DROP TABLE IF EXISTS tab;
SELECT name, type FROM system.data_skipping_indices WHERE table == 'tab' AND database = currentDatabase() LIMIT 1;
SELECT 'Test on map columns';
DROP TABLE IF EXISTS tab;
SELECT name, type FROM system.data_skipping_indices WHERE table == 'tab' AND database = currentDatabase() LIMIT 1;
SELECT 'Test inverted(2) on a column with two parts';
DROP TABLE IF EXISTS tab;
SELECT name, type FROM system.data_skipping_indices WHERE table == 'tab' AND database = currentDatabase() LIMIT 1;
SELECT 'Test inverted(2) on UTF-8 data';
DROP TABLE IF EXISTS tab;
SELECT name, type FROM system.data_skipping_indices WHERE table == 'tab' AND database = currentDatabase() LIMIT 1;
SELECT 'AST Fuzzer crash, issue #54541';
DROP TABLE IF EXISTS tab;
SELECT 'Test max_rows_per_postings_list';
DROP TABLE IF EXISTS tab;
DROP TABLE IF EXISTS tab;
