DROP TABLE IF EXISTS replicated_table_r1 SYNC;
DROP TABLE IF EXISTS replicated_table_r2 SYNC;
SET mutations_sync = 0;
DROP TABLE IF EXISTS replicated_table_r1 SYNC;
DROP TABLE IF EXISTS replicated_table_r2 SYNC;
DROP TABLE IF EXISTS t_light_r1 SYNC;
DROP TABLE IF EXISTS t_light_r2 SYNC;
SELECT '-----Check that select and merge with lightweight delete.-----';
DROP TABLE IF EXISTS t_light_r1 SYNC;
DROP TABLE IF EXISTS t_light_r2 SYNC;
SELECT '-----Check fetch part with lightweight delete-----';
DROP TABLE IF EXISTS t_light_sync_r1 SYNC;
DROP TABLE IF EXISTS t_light_sync_r2 SYNC;
