SET allow_experimental_analyzer = 1;
SELECT number FROM numbers(untuple(tuple(1)));
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
SELECT '--';
