SYSTEM DROP QUERY CACHE;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 0;
SELECT COUNT(*) FROM system.query_cache;
SELECT '---';
SYSTEM DROP QUERY CACHE;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 1;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 1;
SELECT '---';
SYSTEM DROP QUERY CACHE;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 2;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 2;
SELECT 1 SETTINGS use_query_cache = true, query_cache_min_query_runs = 2;
SYSTEM DROP QUERY CACHE;
