SELECT transform(number, [2, 4, 6], ['google', 'yandex', 'yahoo'], 'other') as x FROM numbers(10) GROUP BY x ORDER BY x;
SELECT '#1';
SELECT '#2';
SELECT '#3';
SELECT '#4';
SELECT '#5';
SELECT '----';
SELECT '#1';
SELECT '#3';
SELECT '#4';
SELECT '----';
SELECT '#1';
SELECT '----';
