SELECT '------numbers_0-argument-----';
SELECT number FROM numbers() LIMIT 10;
SELECT '------system.numbers---------';
SELECT number FROM system.numbers LIMIT 10;
SELECT '------numbers_1-argument-----';
SELECT '------numbers_2-arguments----';
SELECT '------numbers_3-arguments----';
SELECT '------numbers_mt_0-argument-----';
SELECT number FROM numbers_mt() LIMIT 10;
SELECT '------numbers_mt_1-argument-----';
SELECT '------numbers_mt_2-arguments----';
SELECT '------numbers_mt_3-arguments----';
SELECT '------zeros_0-argument-------';
SELECT zero FROM zeros() LIMIT 10;
SELECT '------system.zeros-----------';
SELECT zero FROM system.zeros LIMIT 10;
SELECT '------zeros_1-argument-------';
SELECT '------zeros_mt_0-argument-------';
SELECT zero FROM zeros_mt() LIMIT 10;
SELECT '------zeros_mt_1-argument-------';
