SELECT 'a' AS c1 ORDER BY 1 COLLATE NOCASE;
SELECT 'a' ORDER BY 1 COLLATE NOCASE;
SELECT 'A', 'B' ORDER BY 2 COLLATE NOCASE;
SELECT 999::VARCHAR ORDER BY 1 COLLATE NOCASE;
SELECT CASE WHEN s[1]='a' THEN s ELSE NULL END FROM collate_test ORDER BY 1 COLLATE NOCASE;
