CREATE TABLE strings(s VARCHAR);;
INSERT INTO strings VALUES ('Gabel'), ('Göbel'), ('Goethe'), ('Goldmann'), ('Göthe'), ('Götz');;
SELECT * FROM strings WHERE 'goethe' > s COLLATE NOACCENT.de ORDER BY 1;
DELETE FROM strings;
INSERT INTO strings VALUES ('賃貸人側連絡先 (Lessor side contact)'), ('賃借人側連絡先 (Lessee side contact)'), ('解約連絡先 (Termination contacts)'), ('更新連絡先 (Update contact)');
select icu_sort_key('Ş', 'ro');;
SELECT icu_sort_key('goose', 'DUCK_DUCK_ENUM');;
SELECT * FROM strings ORDER BY s COLLATE de;;
SELECT * FROM strings WHERE 'Goethe' > s COLLATE de ORDER BY 1;
SELECT * FROM strings WHERE 'Goethe' > s ORDER BY 1;
SELECT * FROM strings WHERE 'goethe' > s COLLATE de.NOCASE ORDER BY 1;
SELECT * FROM strings WHERE 'goethe' > s COLLATE NOCASE.de ORDER BY 1;
SELECT * FROM strings ORDER BY s;
SELECT * FROM strings ORDER BY s COLLATE ja.NOCASE;
select chr(2*16*256+1*256+2*16+11) collate da  =chr(12*16+5) collate da;;
select icu_sort_key(chr(2*16*256+1*256+2*16+11),'da')=icu_sort_key(chr(12*16+5),'da');;
select chr(2*16*256+1*256+2*16+11) collate da > chr(12*16+5) collate da;;
select chr(2*16*256+1*256+2*16+11) collate da > chr(12*16+5) collate da;;
select count(*) from (select chr(2*16*256+1*256+2*16+11) union select chr(12*16+5)) as t(s) group by s collate da;;
select nfc_normalize(chr(2*16*256+1*256+2*16+11))=nfc_normalize(chr(12*16+5));;
select count(*) from (select chr(2*16*256+1*256+2*16+11) union select chr(12*16+5)) as t(s) group by s collate nfc;;
