SET default_null_order='nulls_first';
PRAGMA enable_verification;
CREATE TABLE INTEGERS(I INTEGER);
INSERT INTO integers (i) VALUES (1), (2), (3), (NULL);
ALTER TABLE integers ADD COLUMN J INTEGER;
ALTER TABLE integers DROP COLUMN i;
DROP TABLE integers;
CREATE TABLE STRUCTS(S ROW(I ROW(K INTEGER)));
INSERT INTO structs VALUES ({'i': {'k': 42}});
DROP TABLE structs;
PRAGMA preserve_identifier_case=false;
