ATTACH '__TEST_DIR__/comment_on_extended_1.db' AS db1;
ATTACH '__TEST_DIR__/comment_on_extended_2.db' AS db2;
COMMENT ON TABLE db1.s1.t1 IS 'very gezellige table 1';
USE db2.s2;
COMMENT ON TABLE t2 IS 'very gezellige table 2';
COMMENT ON TABLE db2.t2 IS 'another very gezellige table 2';
COMMENT ON TABLE s2.t2 IS 'yet another very gezellige table 2';
COMMENT ON INDEX db1.s1.test_index IS 'very gezellige index 1';
COMMENT ON INDEX db2.test_index IS 'very gezellige index 2';
COMMENT ON COLUMN db1.s1.t1.c1 IS 'very gezellige column 1';
COMMENT ON COLUMN db2.t2.c2 IS 'very gezellige column 2';
COMMENT ON COLUMN s2.t2.c2 IS 'another very gezellige column 2';
COMMENT ON COLUMN t2.c2 IS 'yet another very gezellige column 2';
SELECT count(*) from duckdb_tables() where comment IS NOT NULL;
SELECT count(*) from duckdb_columns() where comment IS NOT NULL;
select comment from duckdb_tables() where table_name='t1';
select comment from duckdb_tables() where table_name='t2';
select comment from duckdb_tables() where table_name='t2';
select comment from duckdb_tables() where table_name='t2';
select comment from duckdb_indexes() where index_name='test_index' and database_name='db1';
select database_name, schema_name, comment from duckdb_indexes() where index_name='test_index' order by comment;
select database_name, schema_name, table_name, comment from duckdb_columns() where column_name='c1' order by comment;
select database_name, schema_name, table_name, comment from duckdb_columns() where column_name='c2' order by comment;
select database_name, schema_name, table_name, comment from duckdb_columns() where column_name='c2' order by comment;
select database_name, schema_name, table_name, comment from duckdb_columns() where column_name='c2' order by comment;
