SELECT l FROM tbl ORDER BY l NULLS FIRST LIMIT 5;
SELECT l FROM tbl ORDER BY l NULLS LAST LIMIT 5;
SELECT l FROM tbl ORDER BY l DESC NULLS FIRST LIMIT 5;
SELECT l FROM tbl ORDER BY l DESC NULLS LAST LIMIT 5;
