SELECT * FROM integers ORDER BY i NULLS FIRST LIMIT 2;
SELECT * FROM integers ORDER BY i NULLS LAST LIMIT 2;
SELECT * FROM integers ORDER BY i DESC NULLS FIRST LIMIT 2;
SELECT * FROM integers ORDER BY i DESC NULLS LAST LIMIT 2;
