DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS j;
CREATE TABLE a(`id` UInt32, `val` UInt32) ENGINE = Memory;
CREATE TABLE j(`id` UInt32, `val` UInt8) ENGINE = Join(ANY, LEFT, id);
INSERT INTO a VALUES (1,1)(2,2)(3,3);
INSERT INTO j VALUES (2,2)(4,4);
