SET default_null_order='nulls_first';;
PRAGMA enable_verification;
CREATE TABLE t1 (x INT, y INT);;
INSERT INTO t1 VALUES (3, 3), (3, 3), (1, 1);;
CREATE TABLE t2 (y INT, z INT);;
INSERT INTO t2 VALUES (2, 2), (4, 4);;
SELECT x AS a FROM t1 UNION BY NAME SELECT x AS b FROM t1 ORDER BY t1.x;;
SELECT x, y FROM t1 UNION BY NAME SELECT y, z FROM t2 ORDER BY 4;;
select {'a': 'hello'} as c union all by name select {'b': 'hello'} as c;;
select {'a': 'hello'} as c union all by name select {'a': 'hello', 'b': 'world'} as c;;
SELECT t1.x FROM t1 UNION BY NAME SELECT x FROM t1 ORDER BY t1.x;;
SELECT x FROM t1 UNION BY NAME SELECT x FROM t1 ORDER BY t1.x;;
(SELECT x FROM t1 UNION ALL SELECT x FROM t1) UNION BY NAME SELECT 5 ORDER BY t1.x;;
(SELECT x FROM t1 UNION ALL SELECT y FROM t1) UNION BY NAME SELECT 5 ORDER BY y;;
(SELECT x FROM t1 UNION ALL SELECT y FROM t1) UNION BY NAME (SELECT z FROM t2 UNION ALL SELECT y FROM t2) ORDER BY y, z;;
SELECT 1 UNION BY NAME SELECT * FROM range(2, 100) UNION BY NAME SELECT 999 ORDER BY #2, #1 LIMIT 5;;
SELECT x, y FROM t1 UNION BY NAME SELECT y, z FROM t2 ORDER BY y;;
SELECT x, y FROM t1 UNION BY NAME SELECT y, z FROM t2 ORDER BY 3, 1;;
(SELECT 1 UNION BY NAME SELECT x, y FROM t1) UNION BY NAME SELECT y, z FROM t2 ORDER BY ALL;;
SELECT x, y FROM t1 UNION BY NAME (SELECT y, z FROM t2 INTERSECT SELECT 2, 2 FROM t1 ORDER BY #1) ORDER BY #1;;
(SELECT x, y FROM t1 UNION BY NAME SELECT y, z FROM t2 ORDER BY #1) EXCEPT SELECT NULL, 2, 2 FROM t1 ORDER BY #1;;
SELECT x, x as a FROM t1 UNION BY NAME SELECT y FROM t2 ORDER BY #1, #3;;
SELECT x as a FROM t1 UNION BY NAME SELECT x FROM t1 ORDER BY #1, #2;;
select '0' as c union all select 0 as c;;
select '0' as c union all by name select 0 as c;;
select {'a': '0'} as c union all by name select {'a': 0} as c;
