CREATE TABLE bigdata AS SELECT i AS col_a, i AS col_b FROM range(0,10000) tbl(i);
set threads=1;
INSERT INTO bigdata SELECT bigdata.* FROM bigdata, range(9);
PRAGMA verify_parallelism;
pragma threads=4;
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv1/*.csv');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_csv1/*.csv');
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv2/*.csv');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_csv2/*.csv');
SELECT COUNT(*) FROM read_json_auto('__TEST_DIR__/file_size_bytes_json/*.json');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_json/*.json');
SELECT COUNT(*) FROM read_parquet('__TEST_DIR__/file_size_bytes_parquet/*.parquet');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_parquet/*.parquet');
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv3/*.csv');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_csv3/*.csv');
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv4/*.csv');
SELECT count(*) BETWEEN 3 AND 5 FROM glob('__TEST_DIR__/file_size_bytes_csv4/*.csv');
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv5/*.csv');
SELECT count(*) FROM glob('__TEST_DIR__/file_size_bytes_csv5/*.csv');
SELECT COUNT(*) FROM read_csv_auto('__TEST_DIR__/file_size_bytes_csv6/*.csv');
SELECT count(*) BETWEEN 6 AND 10 FROM glob('__TEST_DIR__/file_size_bytes_csv6/*.csv');
