PRAGMA enable_verification;
copy 'data/csv/hive-partitioning/hive_types/himym.csv' to '__TEST_DIR__/partition' (format parquet, partition_by(season,director,aired));;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=0, hive_types={'season':smallint}) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types={'season':date}) limit 1;;
from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types={'seasons':smallint});;
from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types=true);;
from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types={season:-42});;
copy (select 1 AS a, 1 AS b, '123' AS partition UNION ALL SELECT 2, 2, '1992-01-01' UNION ALL SELECT 3, 3, 'abc') TO '__TEST_DIR__/partition_types' (FORMAT PARQUET, PARTITION_BY(partition));;
select * from read_parquet('__TEST_DIR__/partition_types/**/*.parquet', hive_types={'partition':smallint});
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=1, hive_types={'season':'smallint','director':'varchar','aired':'date'}) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types={'season':smallint,'director':varchar,'aired':date}) limit 1;;
select typeof(season) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types={season:smallint}) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=0) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=1, hive_types_autocast=0) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=1, hive_types_autocast=1) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_partitioning=1) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet', hive_types_autocast=0) limit 1;;
select typeof(season),typeof(director),typeof(aired) from read_parquet('__TEST_DIR__/partition/**/*.parquet') limit 1;;
SELECT * FROM '__TEST_DIR__/partition_types/**/*.parquet' ORDER BY 1;
explain from parquet_scan('__TEST_DIR__/partition/**/*.parquet', HIVE_PARTITIONING=0, HIVE_TYPES_AUTOCAST=0) where aired < '2006-1-1';;
explain from parquet_scan('__TEST_DIR__/partition/**/*.parquet', HIVE_PARTITIONING=1, HIVE_TYPES_AUTOCAST=0) where aired < '2006-1-1';;
