select count(*) = 1 from information_schema.processlist
    where state = "Waiting for table metadata lock" and
          info = "insert into t1 values ()";
select * from t1;
select count(*) = 1 from information_schema.processlist
    where state = "Waiting for table metadata lock" and
          info = "rename table t1 to t2";
select count(*) = 1 from information_schema.processlist
    where state = "Waiting for table metadata lock" and
           info = "insert into t2 values()";
create temporary table t1 (i int) engine=innodb;
alter table t1 add index (i);
LOCK TABLES t1 WRITE;
ALTER TABLE t1 RENAME TO t2;
SELECT * FROM t2;
SELECT * FROM t2;
UNLOCK TABLES;
LOCK TABLES t1 READ, t2 WRITE;
ALTER TABLE t2 RENAME TO t3;
SELECT * FROM t1;
INSERT INTO t3 values (1);
UNLOCK TABLES;
ALTER TABLE t3 RENAME TO t4;
INSERT INTO t4 VALUES (2);
UNLOCK TABLES;
DROP TABLES t1, t4;
CREATE TABLE t1 (i INT);
CREATE DATABASE mysqltest;
LOCK TABLES t1 WRITE;
SELECT * FROM t1;
UNLOCK TABLES;
DROP DATABASE mysqltest;
LOCK TABLES t1 WRITE;
ALTER TABLE t1 ADD COLUMN j INT, RENAME TO t2, ALGORITHM=INPLACE;
SELECT * FROM t2;
SELECT * FROM t2;
UNLOCK TABLES;
CREATE TABLE t1 (i INT);
LOCK TABLES t1 READ, t2 WRITE;
ALTER TABLE t2 ADD COLUMN k INT, RENAME TO t3, ALGORITHM=INPLACE;
SELECT * FROM t1;
INSERT INTO t3 values (1, 2, 3);
UNLOCK TABLES;
LOCK TABLES t1 READ, t3 WRITE, t3 AS a WRITE, t3 AS b READ;
ALTER TABLE t3 ADD COLUMN l INT, RENAME TO t4, ALGORITHM=INPLACE;
SELECT * FROM t4 AS a, t4 AS b;
INSERT INTO t4 VALUES (2, 3, 4, 5);
DELETE a FROM t4 AS a, t4 AS b;
UNLOCK TABLES;
DROP TABLES t1, t4;
CREATE TABLE t1 (i INT);
CREATE DATABASE mysqltest;
LOCK TABLES t1 WRITE;
SELECT * FROM t1;
UNLOCK TABLES;
DROP DATABASE mysqltest;
LOCK TABLES t1 WRITE;
ALTER TABLE t1 ADD COLUMN j INT, RENAME TO t2, ALGORITHM=COPY;
SELECT * FROM t2;
SELECT * FROM t2;
UNLOCK TABLES;
CREATE TABLE t1 (i INT);
LOCK TABLES t1 READ, t2 WRITE;
ALTER TABLE t2 ADD COLUMN k INT, RENAME TO t3, ALGORITHM=COPY;
SELECT * FROM t1;
INSERT INTO t3 values (1, 2, 3);
UNLOCK TABLES;
LOCK TABLES t1 READ, t3 WRITE, t3 AS a WRITE, t3 AS b READ;
ALTER TABLE t3 ADD COLUMN l INT, RENAME TO t4, ALGORITHM=COPY;
SELECT * FROM t4 AS a, t4 AS b;
INSERT INTO t4 VALUES (2, 3, 4, 5);
DELETE a FROM t4 AS a, t4 AS b;
UNLOCK TABLES;
DROP TABLES t1, t4;
CREATE TABLE t1 (i INT);
CREATE DATABASE mysqltest;
LOCK TABLES t1 WRITE;
SELECT * FROM t1;
UNLOCK TABLES;
DROP DATABASE mysqltest;
