CREATE TABLE t1 (c1 INT PRIMARY KEY) ENGINE=INNODB;
INSERT INTO t1 VALUES (1);
CREATE TABLE t2 (c2 INT PRIMARY KEY) ENGINE=INNODB
PARTITION BY HASH (c2)
PARTITIONS 4;
INSERT INTO t2 VALUES (2);
SELECT c1 FROM t1;
SELECT c2 FROM t2;
DROP TABLE t1, t2;
