SELECT @@global.protocol_compression_algorithms;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
select * from performance_schema.session_status where variable_name like 'COMPRESSION%' order by 1;
CREATE DATABASE wl12475;
CREATE TABLE t1(a LONGTEXT);
INSERT INTO t1 VALUES (REPEAT('1',200));
INSERT INTO t1 VALUES (REPEAT('2', 1800));
DROP TABLE t1;
SELECT @@global.protocol_compression_algorithms;
DROP DATABASE wl12475;
CREATE DATABASE wl13292;
CREATE TABLE wl13292.t1(a INT);
DROP DATABASE wl13292;
