SELECT *
FROM t1 JOIN t2 ON t1.i1=t2.i1
WHERE t2.i2 > 3
ORDER BY t1.i1 LIMIT 20;
DROP TABLE t0, t1, t2;
CREATE TABLE t1(a INT);
CREATE TABLE t2(a INT);
INSERT INTO t1 VALUES (1),(2),(3),(4);
INSERT INTO t2 VALUES (1),(2);
SELECT t1.a, t2.a FROM t1 JOIN t2
  ON t1.a+t2.a = (SELECT COUNT(*) FROM t1);
SELECT a + (SELECT SUM(a) + (SELECT COUNT(a) FROM t1) FROM t1) AS cnt
  FROM t2;
SELECT TRACE NOT RLIKE '"final_filtering_effect": 1' AS OK
  FROM INFORMATION_SCHEMA.OPTIMIZER_TRACE;
DROP TABLE t1, t2;
