select distinct n1 from t1;
select count(distinct n1) from t1;
select distinct n2 from t1;
select distinct s from t1;
select distinct vs from t1;
select distinct t from t1;
select distinct n1,n2 from t1;
select distinct n1,s from t1;
select distinct s,n1,vs from t1;
select distinct s,t from t1;
drop table t1;
create table t1 (n int default NULL);
drop table t1;
create table t1 (s text);
drop table t1;
