SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (a CHAR(4) CHARACTER SET utf8mb3, KEY key_a(a(3)));
ALTER TABLE t1 CHANGE a a CHAR(4);
ALTER TABLE t1 CHANGE a a CHAR(4) CHARACTER SET utf8mb3;
DROP TABLE t1;
