SELECT HEX(CONVERT(code USING utf8mb4)),
HEX(UPPER(CONVERT(code USING utf8mb4))),
HEX(LOWER(CONVERT(code USING utf8mb4))),
code,
UPPER(CONVERT(code USING utf8mb4)),
LOWER(CONVERT(code USING utf8mb4))
FROM fulltable
WHERE (code <= 0x0000D7FF OR code >= 0x0000E000) AND
(HEX(CONVERT(code USING utf8mb4)) <> HEX(UPPER(CONVERT(code USING utf8mb4)))
OR HEX(CONVERT(code USING utf8mb4)) <> HEX(LOWER(CONVERT(code USING utf8mb4))))
ORDER BY HEX(CONVERT(code USING utf8mb4));
DROP TABLE fulltable;
