SELECT CREATE_OPTIONS FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_NAME='t1' OR TABLE_NAME='t2';
DROP TABLE t1;
DROP TABLE t2;
CREATE TEMPORARY TABLE t1 (
  a INTEGER NOT NULL DEFAULT 1,
  b INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  c INTEGER,
  d INTEGER GENERATED ALWAYS AS (a * 2) STORED,
  e POINT NOT NULL SRID 0,
  f CHAR(30),
  g INT,
  h TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY(g), SPATIAL KEY(e), FULLTEXT(f)) engine=myisam;
CREATE INDEX b_index USING btree ON t1( b );
CREATE INDEX h_index USING hash ON t1( c );
CREATE INDEX g_index ON t1( f(4) ) COMMENT 'ABC';
CREATE INDEX r_index USING rtree ON t1( a ) USING btree;
DROP TEMPORARY TABLE t1;
DROP DATABASE test1;
