CREATE DATABASE db1;
USE db1;

CREATE TABLE t1 (c1 INT);
CREATE FUNCTION f1() RETURNS INT RETURN 1;
CREATE FUNCTION f2() RETURNS INT RETURN 2;
CREATE VIEW v1 AS SELECT f1() AS f1;
CREATE VIEW v2 AS SELECT f1, f2() AS f2  FROM v1;
CREATE VIEW v3 AS SELECT c1, f2 FROM t1, v2;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
ALTER TABLE t1 RENAME COLUMN c1 TO c2;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' AND VIEW_NAME='v3';
ALTER TABLE t1 RENAME COLUMN c2 TO c1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' AND VIEW_NAME='v3';
DROP FUNCTION f1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1' AND TABLE_NAME='v1';
CREATE FUNCTION f1() RETURNS INT return 1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1' AND TABLE_NAME='v1';

CREATE USER 'testuser'@'localhost';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP USER 'testuser'@'localhost';
DROP FUNCTION f1;
DROP FUNCTION f2;
DROP VIEW v1, v2, v3;
DROP TABLE t1;
CREATE TABLE t1 (c1 INT);
CREATE VIEW v1 AS SELECT c1 FROM t1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP TABLE t1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
   WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP VIEW v1;
CREATE USER testuser1@localhost;

CREATE USER testuser2@localhost;
CREATE TABLE t1(c1 INT);
CREATE VIEW v1 AS SELECT c1 FROM t1;
CREATE FUNCTION f1() RETURNS INT RETURN 1;
CREATE VIEW v2 AS SELECT f1();
CREATE TABLE t2(c1 INT);
CREATE VIEW v3 AS SELECT c1 FROM t2;
CREATE FUNCTION f2() RETURNS INT RETURN 1;
CREATE VIEW v4 AS SELECT f2();
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
DROP VIEW v1,v2;
DROP FUNCTION f1;
DROP TABLE t1;
DROP VIEW v3,v4;
DROP FUNCTION f2;
DROP TABLE t2;
DROP USER testuser1@localhost;
DROP USER testuser2@localhost;
CREATE USER testuser1@localhost;
CREATE TABLE t1(c1 INT);
CREATE VIEW v1 AS SELECT c1 FROM t1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP USER testuser1@localhost;
DROP VIEW v1;
DROP TABLE t1;


DROP DATABASE db1;
