CREATE DATABASE db1;
CREATE TABLE t1 (c1 INT);
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
ALTER TABLE t1 RENAME COLUMN c1 TO c2;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' AND VIEW_NAME='v3';
ALTER TABLE t1 RENAME COLUMN c2 TO c1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' AND VIEW_NAME='v3';
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1' AND TABLE_NAME='v1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1' AND TABLE_NAME='v1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP TABLE t1;
CREATE TABLE t1 (c1 INT);
CREATE VIEW v1 AS SELECT c1 FROM t1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP TABLE t1;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
   WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP VIEW v1;
CREATE TABLE t1(c1 INT);
CREATE VIEW v1 AS SELECT c1 FROM t1;
CREATE TABLE t2(c1 INT);
CREATE VIEW v3 AS SELECT c1 FROM t2;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_ROUTINE_USAGE
  WHERE TABLE_SCHEMA='db1';
DROP TABLE t1;
DROP TABLE t2;
CREATE TABLE t1(c1 INT);
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE
  WHERE VIEW_SCHEMA='db1' ORDER BY VIEW_NAME, TABLE_NAME;
DROP VIEW v1;
DROP TABLE t1;
DROP DATABASE db1;
