SELECT table_name, cardinality  FROM INFORMATION_SCHEMA.STATISTICS
  WHERE cardinality > 0 and table_schema='test';
DROP TABLE t1;
CREATE TABLE t1(i INT);
DROP TABLE t1;
CREATE TABLE t1(f1 INT, s VARCHAR(10));
SELECT TABLE_NAME, CREATE_OPTIONS FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_NAME='t1';
SELECT TABLE_NAME, CREATE_OPTIONS FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_NAME='t1';
DROP TABLE t1;
CREATE TABLE t1 (f1 INT );
PREPARE stmt FROM 'show events';
LOCK TABLE t1 READ;
UNLOCK TABLES;
DROP TABLE t1;
DROP PREPARE stmt;
CREATE SCHEMA s;
SELECT SCHEMA_NAME, OPTIONS FROM INFORMATION_SCHEMA.SCHEMATA_EXTENSIONS
  WHERE SCHEMA_NAME = 's';
SELECT SCHEMA_NAME, OPTIONS FROM INFORMATION_SCHEMA.SCHEMATA_EXTENSIONS
  WHERE SCHEMA_NAME = 's';
DROP SCHEMA s;
