SELECT * FROM t1 ORDER BY 1;
INSERT INTO t1 VALUES (3),(4);
SELECT * FROM t1 ORDER BY 1;
SELECT "session state sent as part of above SELECT" AS col_heading;
INSERT INTO t1 VALUES (5),(6);
SELECT "no session state exists" AS col_heading;
SELECT MIN(a) FROM t2;
SELECT MAX(2) FROM t1;
SELECT "session state sent for SELECT inside t1_sel()" AS col_heading;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT @a,@b,@c,@d,@e,@f,@g,@h,@i,@j;
DROP TEMPORARY TABLE IF EXISTS t3;
CREATE TEMPORARY TABLE t3 (id INT);
INSERT INTO t3 VALUES (1), (2), (3);
SELECT "session state sent as part of above SELECT" AS col_heading;
DROP DATABASE wl7766;
CREATE DATABASE bug19550875;
INSERT INTO t1 VALUES (1), (2);
SELECT * FROM t1;
SELECT * FROM t1;
PREPARE x FROM 'SELECT 1';
SELECT * FROM t1;
SELECT * FROM t1;
SELECT * FROM t1 ORDER BY 1;
DROP DATABASE bug19550875;
