drop table if exists t1;
drop database if exists mysqltest;
drop database if exists client_test_db;
create table t1(n int);
insert into t1 values(1);
create temporary table t1( n int);
insert into t1 values(2);
drop table t1;
select * from t1;
create database mysqltest;
drop database if exists mysqltest;
create database mysqltest;
create table mysqltest.mysqltest (n int);
drop database if exists mysqltest;
create database mysqltest;
drop database mysqltest;
create database mysqltest;
unlock tables;
select schema_name from information_schema.schemata order by schema_name;
drop database mysqltest;
unlock tables;
select schema_name from information_schema.schemata order by schema_name;
drop table t1;
create table t1(n int);
unlock tables;
drop table t1;
drop database if exists mysqltest;
drop table if exists t1;
create table t1 (i int);
create database mysqltest;
lock tables t1 read;
select 1;
unlock tables;
drop table if exists t1,t2;
create table t1 (a int);
create table t2 (a int);
lock table t1 read;
unlock tables;
drop table t1,t2;
create table t1 (i int);
create table t2 (i int);
lock tables t1 read;
lock tables t2 read;
unlock tables;
drop table t1,t2;
create database mysqltestbug26703;
create table `#mysql50#abc``def` ( id int );
create table `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
create table `#mysql50#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa` (a int);
drop database mysqltestbug26703;
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT);
LOCK TABLE t1 WRITE;
UNLOCK TABLES;
DROP TABLE t1;
DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table1,table2;
DROP VIEW IF EXISTS view1,view2,view3,view4;
CREATE TABLE table1(a int);
CREATE TABLE table2(b int);
INSERT INTO table1 VALUES (1);
DROP TABLE table1,table2;
CREATE DATABASE bug19573998;
CREATE TABLE t1(i int);
SELECT COUNT(*) = 1 FROM information_schema.processlist
  WHERE state = "Waiting for schema metadata lock" AND
        info = "DROP DATABASE bug19573998";
UNLOCK TABLES;
DROP DATABASE bug19573998;
