SELECT MAX(a) FROM t1 GROUP BY a,b;
DROP TABLE t1;
CREATE TABLE t1 (a INT(100) NOT NULL);
INSERT INTO t1 VALUES (1), (0), (2);
ALTER TABLE t1 ADD INDEX a(a);
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1(a BLOB);
INSERT INTO t1 VALUES("");
DROP TABLE t1;
CREATE TABLE t1 (a INT);
INSERT INTO t1 VALUES (0), (1), (2), (3), (4), (5), (6), (7), (8), (9);
CREATE TABLE t2 (a INT, b INT, filler CHAR(100), KEY(a), KEY(b));
INSERT INTO t2 SELECT 1000, 1000, 'filler' FROM t1 A, t1 B, t1 C;
INSERT INTO t2 VALUES (1, 1, 'data');
SELECT * FROM t1 LEFT JOIN t2 ON ( t2.a < 10 OR t2.b < 10 );
SELECT * FROM t1 LEFT JOIN t2 ON ( t2.a < 10 OR t2.b < 10 );
DROP TABLE t1, t2;
create table t1(a int);
insert into t1 values(1),(2),(3);
select * from t1 order by a;
drop table t1;
