SELECT COUNT(*) FROM INFORMATION_SCHEMA.EVENTS;
DROP DATABASE events_conn1_test2;
CREATE DATABASE events_conn1_test2;
DROP DATABASE events_conn1_test2;
CREATE DATABASE events_conn1_test3;
CREATE DATABASE events_conn1_test4;
CREATE DATABASE events_conn1_test2;
DROP DATABASE events_conn2_db;
DROP DATABASE events_conn3_db;
DROP DATABASE events_conn1_test2;
DROP DATABASE events_conn1_test3;
DROP DATABASE events_conn1_test4;
DROP DATABASE events_test;
