SELECT 1 + 1 AS x FROM t GROUP BY x WITH ROLLUP HAVING x = 1;
SELECT JSON_UNQUOTE(JSON_EXTRACT(@var, '$.query')) AS query;
DROP TABLE t;
CREATE TABLE t1 (a INT NOT NULL, b INT NOT NULL);
SELECT * FROM t1 x1 JOIN t1 x2 ON x2.a=
  (SELECT MIN(x3.a) FROM t1 x3 WHERE x1.a=x3.a);
SELECT * FROM t1 x1 JOIN t1 x2 ON x2.a<
  (SELECT MIN(x3.a) FROM t1 x3 WHERE x1.a=x3.a);
DROP TABLE t1;
CREATE TABLE t1 (a INT PRIMARY KEY, b INT);
SELECT LAST_VALUE((SELECT x1.a FROM t1))
OVER (PARTITION BY b) FROM t1 x1;
DROP TABLE t1;
CREATE TABLE t (i INT);
INSERT INTO t VALUES (1), (2), (3);
DROP TABLE t;
