drop table if exists t1,t2;
drop database if exists mysqltest;
create temporary table t1(n int not null primary key);
create table t2(n int);
insert into t2 values(3);
select * from t1;
drop table t2;
unlock tables;
create database mysqltest;
create table mysqltest.t1(n int);
unlock tables;
create table t1 (n int);
insert into t1 values (345);
select * from t1;
drop table t1;
lock table t1 write;
lock table t1 read;
unlock tables;
lock table t1 write;
lock table t1 read;
lock table t1 write;
unlock tables;
create table t2 (c1 int);
create table t3 (c1 int);
lock table t1 read, t2 read, t3 write;
lock table t1 read, t2 read, t3 read;
unlock tables;
drop table t1, t2, t3;
create table t1 (c1 int);
create table t2 (c1 int);
lock table t1 write;
unlock tables;
drop table t1, t2;
drop table if exists t1, t2;
create table t1 (a int);
create table t2 (b int);
lock tables t1 write;
unlock tables;
lock tables t1 read, t2 write;
unlock tables;
lock tables t1 read;
unlock tables;
drop table t1, t2;
unlock tables;
unlock tables;
unlock tables;
drop tables if exists t1, t2;
create table t1 (i int);
create temporary table t2 (j int);
lock table t2 read;
unlock tables;
drop tables t1, t2;
drop table if exists t1, t2, t3;
create table t1 (a int);
create table t2 (a int);
create table t3 (a int);
lock table t1 read, t2 read;
unlock tables;
select * from t1;
select * from t2;
select * from t3;
insert into t1 (a) values (1);
insert into t2 (a) values (1);
insert into t3 (a) values (1);
insert into t2 (a) values (1);
unlock tables;
insert into t1 (a) values (1);
insert into t2 (a) values (1);
select * from t1;
select * from t2;
select * from t3;
insert into t1 (a) values (2);
insert into t2 (a) values (2);
insert into t3 (a) values (2);
insert into t3 (a) values (2);
select * from t1;
select * from t2;
insert into t2 (a) values (3);
unlock tables;
select * from t1;
unlock tables;
unlock tables;
unlock tables;
unlock tables;
unlock tables;
lock table t1 read, t2 read;
unlock tables;
unlock tables;
drop table t1, t2, t3;
drop view if exists v1, v2, v3;
drop table if exists t1, v1;
create table t1 (a int);
create view v1 as select 1;
create view v2 as select * from t1;
create view v3 as select * from v2;
create temporary table v1 (a int);
drop view v1;
create table v1 (a int);
drop temporary table v1;
unlock tables;
drop view v2, v3;
drop table t1, v1;
drop table if exists t1;
create table t1 (a int, key a (a));
insert into t1 (a) values (1), (2), (3);
unlock tables;
drop table t1;
drop table if exists t1;
create table t1 (a int);
select * from t1;
lock table t1 read;
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table flush"
  and info = "flush table t1";
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table flush"
  and info = "select * from t1";
select * from t1;
unlock tables;
select * from t1;
lock table t1 read;
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table flush"
  and info = "flush tables";
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table flush"
  and info = "select * from t1";
select * from t1;
unlock tables;
drop table t1;
drop table if exists t1, t2;
create table t1 (i int);
create table t2 (i int);
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for table flush"
  and info = "flush tables with read lock";
select count(*) = 1 from information_schema.processlist
  where state = "Waiting for global read lock"
  and info = "insert into t2 values (1)";
unlock tables;
drop tables t1, t2;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT);
ALTER TABLE t1 COMMENT 'test';
UNLOCK TABLES;
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id INT PRIMARY KEY, value INT);
INSERT INTO t1 VALUES (1, 1);
UPDATE t1 SET value= value + 1 WHERE id = 1;
UNLOCK TABLES;
DROP TABLE t1;
