CREATE TEMPORARY TABLE t1 (f1 INT PRIMARY KEY, f2 INT);
DROP TABLE t1;
CREATE TABLE t1 (f1 INT, f2 INT PRIMARY KEY) PARTITION BY RANGE (f2)
                   (PARTITION p0 VALUES LESS THAN (2011),
                    PARTITION p1 VALUES LESS THAN (2022));
DROP TABLE t1;
CREATE TABLE t1 (f1 INT, f2 INT) ENGINE = MyISAM;
DROP TABLE t1;
CREATE TABLE t1 (my_row_id INT, f2 INT);
DROP TABLE t1;
CREATE TEMPORARY TABLE t1(f1 INT);
DROP TABLE t1;
CREATE TABLE t1(f1 INT NOT NULL UNIQUE);
DROP TABLE t1;
CREATE TEMPORARY TABLE t1 (f1 INT NOT NULL UNIQUE);
DROP TABLE t1;
CREATE TABLE t1(f1 INT);
CREATE TABLE IF NOT EXISTS t1 (f1 INT, f2 INT);
DROP TABLE t1;
CREATE TEMPORARY TABLE t2 (f1 INT);
CREATE TEMPORARY TABLE IF NOT EXISTS t2 (f1 INT, f2 INT);
DROP TABLE t2;
CREATE VIEW t1 AS SELECT 1;
CREATE TABLE IF NOT EXISTS t1 (f1 INT);
DROP VIEW t1;
CREATE TABLE t1(f1 INT);
CREATE TABLE t2 LIKE t1;
CREATE TABLE t3 LIKE t1;
DROP TABLE t1, t2;
CREATE TABLE t1 (f1 INT);
CREATE TABLE t2 AS SELECT * FROM t1;
DROP TABLE t2;
CREATE TABLE t2 (f1 INT NOT NULL UNIQUE) AS SELECT * FROM t1;
DROP TABLE t2;
CREATE TABLE t2 (f1 INT, PRIMARY KEY(f1)) AS SELECT * FROM t1;
DROP TABLE t2;
CREATE TABLE t2 (f1 INT, f2 INT);
DROP TABLE t1;
DROP TABLE t2;
CREATE TABLE t1 (f1 INT);
CREATE TABLE t2 (f1 INT);
CREATE TEMPORARY TABLE t4 (f1 INT);
DROP TABLE t1;
DROP TABLE t2;
DROP TABLE t3;
DROP TABLE t4;
CREATE TABLE t1 (f1 INT);
CREATE TEMPORARY TABLE t2 (f1 INT);
ALTER TABLE t1 ADD PRIMARY KEY(f1);
ALTER TABLE t2 ADD PRIMARY KEY(f1);
ALTER TABLE t1 ADD UNIQUE KEY(f1);
DROP TABLE t1;
ALTER TABLE t2 ADD UNIQUE KEY(f1);
DROP TABLE t2;
CREATE TABLE t1 (f1 INT, f2 INT);
CREATE TEMPORARY TABLE t2 (f1 INT, f2 INT);
DROP TABLE t1, t2;
CREATE TABLE t1 (f1 INT);
ALTER TABLE t1 ENGINE='MyISAM';
ALTER TABLE t1 ENGINE='InnoDB';
ALTER TABLE t1 ENGINE='MYISAM',
               ADD COLUMN my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE FIRST,
               ADD PRIMARY KEY(my_row_id);
ALTER TABLE t1 DROP COLUMN my_row_id;
DROP TABLE t1;
CREATE TEMPORARY TABLE t1 (f1 INT);
ALTER TABLE t1 ENGINE='MyISAM';
ALTER TABLE t1 ENGINE='InnoDB';
ALTER TABLE t1 ENGINE='MYISAM',
               ADD COLUMN my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE FIRST,
               ADD PRIMARY KEY(my_row_id);
ALTER TABLE t1 DROP COLUMN my_row_id;
DROP TABLE t1;
CREATE TABLE t1(my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE,
                f1 INT, primary key(my_row_id)) ENGINE = 'MyISAM';
ALTER TABLE t1 ENGINE='InnoDB';
ALTER TABLE t1 DROP COLUMN my_row_id;
DROP TABLE t1;
CREATE TEMPORARY TABLE t1(my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE,
                f1 INT, primary key(my_row_id)) ENGINE = 'MyISAM';
ALTER TABLE t1 ENGINE='InnoDB';
ALTER TABLE t1 DROP COLUMN my_row_id;
DROP TABLE t1;
CREATE TABLE t1 (f2 INT, f3 INT);
CREATE TEMPORARY TABLE t2 (f2 INT, f3 INT);
ALTER TABLE t1 ADD COLUMN f1 INT FIRST;
ALTER TABLE t2 ADD COLUMN f1 INT FIRST;
ALTER TABLE t1 ADD COLUMN f0 INT FIRST;
ALTER TABLE t1 ADD COLUMN f INT FIRST;
DROP TABLE t1;
ALTER TABLE t2 ADD COLUMN f0 INT FIRST;
ALTER TABLE t2 ADD COLUMN f INT FIRST;
DROP TABLE t2;
CREATE TABLE t1(f2 INT);
DROP TABLE t1;
CREATE TEMPORARY TABLE t1(f2 INT);
DROP TABLE t1;
CREATE TABLE t1(f2 INT);
ALTER TABLE t1 ADD COLUMN my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE FIRST,
               ADD PRIMARY KEY(my_row_id);
ALTER TABLE t1 ADD COLUMN f1 INT FIRST;
ALTER TABLE t1 ADD COLUMN f0 INT FIRST;
DROP TABLE t1;
CREATE TABLE t1 (f1 INT);
DROP TABLE t1;
CREATE TABLE t1 (f1 INT) PARTITION BY RANGE(f1) (PARTITION p1 VALUES LESS THAN (1991));
ALTER TABLE t1 REMOVE PARTITIONING;
ALTER TABLE t1 ADD COLUMN my_row_id bigint unsigned NOT NULL AUTO_INCREMENT INVISIBLE FIRST,
               ADD PRIMARY KEY(my_row_id);
DROP TABLE t1;
CREATE TABLE t2 (f1 INT);
CREATE TABLE t3 AS SELECT * FROM t2;
CREATE TABLE t(f1 INT);
PREPARE stmt1 FROM 'CREATE TABLE t1(f1 INT, f2 INT)';
PREPARE stmt2 FROM 'CREATE TABLE t2 AS SELECT * FROM t';
DROP PREPARE stmt1;
DROP PREPARE stmt2;
SELECT TABLE_NAME, AUTO_INCREMENT FROM INFORMATION_SCHEMA.TABLES
         WHERE TABLE_NAME='t1';
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, EXTRA
         FROM INFORMATION_SCHEMA.COLUMNS
         WHERE TABLE_NAME='t1' ORDER BY ORDINAL_POSITION;
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS_EXTENSIONS
         WHERE TABLE_NAME='t1' ORDER BY COLUMN_NAME;
SELECT INDEX_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.STATISTICS
         WHERE TABLE_NAME='t1' ORDER BY INDEX_NAME, COLUMN_NAME;
SELECT CONSTRAINT_NAME, COLUMN_NAME
         FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME='t1'
         ORDER BY CONSTRAINT_NAME, COLUMN_NAME;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, ENFORCED
         FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME='t1'
         ORDER BY CONSTRAINT_NAME;
SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS_EXTENSIONS
         WHERE TABLE_NAME='t1' ORDER BY CONSTRAINT_NAME;
CREATE TABLE t1 (f1 INT);
INSERT INTO t1 VALUES (1), (3), (7), (4), (8);
DROP TABLE t1;
