       FLUSH_OPTIMIZER_COSTS ON *.* FROM root@localhost;
SELECT GRANTEE, PRIVILEGE_TYPE, IS_GRANTABLE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
  WHERE PRIVILEGE_TYPE LIKE 'FLUSH_%' ORDER BY 1,2,3;

CREATE USER wl14303@localhost, wl14303_no_reload@localhost;
SELECT GRANTEE, PRIVILEGE_TYPE, IS_GRANTABLE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
  WHERE PRIVILEGE_TYPE = 'RELOAD' ORDER BY 1,2,3;
SELECT GRANTEE, PRIVILEGE_TYPE, IS_GRANTABLE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
  WHERE PRIVILEGE_TYPE LIKE 'FLUSH_%' ORDER BY 1,2,3;
DROP USER wl14303@localhost, wl14303_no_reload@localhost;
