CREATE VIEW v1 AS SELECT 1 as 'a';
DROP VIEW v1;
CREATE TABLE t1(a INT);
CREATE EVENT wl15874_ev1
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 HOUR
DO SET @sum = @sum + 1;
DROP EVENT wl15874_ev1;
CREATE DEFINER=CURRENT_USER PROCEDURE p1() SELECT 1;
DROP PROCEDURE p1;
DROP TABLE t1;
CREATE VIEW v1 AS SELECT 1 as 'a';
DROP VIEW v1;
CREATE TABLE t1(a INT);
DROP TABLE t1;
CREATE TABLE t1(a INT);
DROP TABLE t1;
CREATE VIEW v1 as SELECT 3 as 'a';
DROP VIEW v1;
CREATE EVENT wl15874_ev1
  ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 HOUR
  DO SET @sum = @sum + 1;
DROP EVENT wl15874_ev1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_USER_ID' AND GRANTEE LIKE '%wl15874_2%' ORDER BY 1;
DROP DATABASE wl15874;
