select current_user();
create database mysqltest_1;
drop database mysqltest_1;
create database mysqltest;
create table t1 (id int primary key, data varchar(255));
insert into t1 values (1, 'I can''t change it!');
update t1 set data='I can change it!' where id = 1;
insert into t1 values (1, 'XXX') on duplicate key update data= 'I can change it!';
select * from t1;
drop table t1;
create table t1 (a int, b int);
drop table t1;
drop database mysqltest;
create database mysqltest_1;
drop database mysqltest_1;
drop table if exists t1, t2;
create table t1(c1 int);
create table t2(c1 int, c2 int);
drop table t1, t2;
create database mysqltest_1;
create table mysqltest_1.t1 (i int);
drop table mysqltest_1.t1;
drop database mysqltest_1;
unlock tables;
unlock tables;
create database TESTDB;
create table t2(a int);
drop database TESTDB;
INSERT INTO t2 VALUES (1);
DROP FUNCTION IF EXISTS f2;
DROP TABLE t2;
drop database if exists mysqltest_1;
drop database if exists mysqltest_2;
create database mysqltest_1;
create database mysqltest_2;
create table t1 (i int);
drop database mysqltest_1;
drop database mysqltest_2;
create database mysqltest_1;
create database mysqltest_3;
create table t2(f1 int);
select * from t1;
drop database mysqltest_1;
CREATE DATABASE db1;
SELECT * FROM t2;
DROP DATABASE db1;
SELECT LEFT(CURRENT_USER(),INSTR(CURRENT_USER(),'@')-1) INTO @u;
SELECT MID(CURRENT_USER(),INSTR(CURRENT_USER(),'@')+1)  INTO @h;
DROP DATABASE IF EXISTS mysqltest_db1;
DROP DATABASE IF EXISTS mysqltest_db2;
CREATE DATABASE mysqltest_db1;
CREATE DATABASE mysqltest_db2;
CREATE TABLE mysqltest_db2.t2_1(a INT);
CREATE TEMPORARY TABLE t1(a INT) engine=myisam;
CREATE TEMPORARY TABLE t2 LIKE t1;
CREATE TEMPORARY TABLE t3(a INT, b INT, PRIMARY KEY (a)) engine=myisam;
CREATE TEMPORARY TABLE t4 SELECT * FROM t1;
CREATE TEMPORARY TABLE t5(a INT) ENGINE = MyISAM;
CREATE TEMPORARY TABLE t6(a INT) ENGINE = MERGE UNION = (t5);
INSERT INTO t1 VALUES (1), (2), (3);
SELECT * FROM t1 ORDER BY a;
CREATE INDEX idx1 ON t3(b);
DROP INDEX idx1 ON t3;
ALTER TABLE t4 ADD COLUMN b INT;
ALTER TABLE t6 UNION = ();
ALTER TABLE t6 UNION = (t5);
INSERT INTO t1 VALUES (4);
INSERT INTO t2 SELECT a FROM t1;
SELECT * FROM t1 ORDER BY a;
SELECT * FROM t2 ORDER BY a;
UPDATE t1 SET a = a * 10;
UPDATE t1 SET a = 100 WHERE a = 10;
UPDATE t1, t2 SET t1.a = 200 WHERE t1.a = t2.a * 10 AND t1.a = 20;
SELECT * FROM t1 ORDER BY a;
DELETE FROM t1 WHERE a = 100;
DELETE t1 FROM t1, t2 WHERE t1.a = t2.a * 100 AND t1.a = 200;
SELECT * FROM t1 ORDER BY a;
SELECT * FROM t1 ORDER BY a;
INSERT INTO t1 VALUES (1), (2), (3);
SELECT * FROM t1 ORDER BY a;
SELECT @a;
LOCK TABLES t1 READ;
UNLOCK TABLES;
INSERT INTO t3 VALUES (1, 111), (2, 222), (3, 333);
SELECT * FROM t2 ORDER BY a;
SELECT * FROM t3 ORDER BY a;
DELETE FROM t1;
PREPARE stmt1 FROM 'SELECT * FROM t1 ORDER BY a';
PREPARE stmt2 FROM 'SELECT * FROM t2 ORDER BY a';
DEALLOCATE PREPARE stmt1;
DEALLOCATE PREPARE stmt2;
DROP TABLE t1;
CREATE TEMPORARY TABLE t1(a INT);
DROP TEMPORARY TABLE t1;
DROP TEMPORARY TABLE t4;
CREATE TEMPORARY TABLE t7(a INT) engine=myisam;
CREATE TEMPORARY TABLE t8(a INT) engine=myisam;
CREATE TEMPORARY TABLE t9(a INT) engine=myisam;
CREATE TEMPORARY TABLE t10(a INT) ENGINE = MERGE UNION = (t7, t8);
ALTER TABLE t10 UNION = (t9);
DROP TEMPORARY TABLE t10;
DROP TEMPORARY TABLE t7;
DROP TEMPORARY TABLE t8;
DROP TEMPORARY TABLE t9;
DROP DATABASE mysqltest_db1;
DROP DATABASE mysqltest_db2;
