SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_USER_ID' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_ANY_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'ALLOW_NONEXISTENT_DEFINER' ORDER BY 1;
CREATE USER wl15874@localhost;
select COUNT(*) FROM performance_schema.error_log
  WHERE PRIO='Warning' AND DATA REGEXP 'SET_USER_ID.*deprecated';
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_USER_ID' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_ANY_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'ALLOW_NONEXISTENT_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_USER_ID' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_ANY_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'ALLOW_NONEXISTENT_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SUPER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_USER_ID' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'SET_ANY_DEFINER' ORDER BY 1;
SELECT GRANTEE FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE PRIVILEGE_TYPE = 'ALLOW_NONEXISTENT_DEFINER' ORDER BY 1;
DROP USER wl15874@localhost;
