SELECT IF (COUNT(*) > 0, "YES", "NO") AS "IMPLICIT COMMIT" FROM trans;
DELETE FROM trans;
select 1 as res from t1 where (1) in (select * from t1);
create table t2 like t1;
drop table t2;
create temporary table t2 as select * from t1;
drop temporary table t2;
create table t2 as select * from t1;
update t2 set a=a+1 where (1) in (select * from t1);
insert into t2 set a=((1) in (select * from t1));
insert into t2 select * from t1;
delete from t2 where (1) in (select * from t1);
delete t2, t3 from t2, t3 where (1) in (select * from t1);
select * from t2;
update t2, t3 set t3.a=t2.a, t2.a=null where (1) in (select * from t1);
create table t4 (a varchar(100));
drop table t4;
create procedure p1(a int) begin end;
drop procedure p1;
create view v1 as select * from t1;
alter view v1 as select 2;
drop view v1;
create index idx1 on t1(a);
drop index idx1 on t1;
alter table t1 add column b int;
alter table t1 change b c int;
alter table t1 drop column c;
create temporary table t4 (a int);
alter table t1 add column b int;
alter table t1 change b c int;
alter table t1 drop column c;
drop table t4;
insert into t2 select * from t1;
insert into t2 select * from t1;
create temporary table t4 as select * from t1;
drop temporary table t4;
lock tables t1 write, trans write;
unlock tables;
create database db2;
create table db2.t1 (a int);
drop database db2;
create procedure p1(a int) begin end;
alter procedure p1 comment 'foobar';
drop procedure p1;
prepare stmt1 from "insert into t1 values (5)";
deallocate prepare stmt1;
CREATE TABLESPACE ts1 ADD DATAFILE './ts1.ibd' ENGINE=INNODB;
DROP TABLESPACE ts1  ENGINE=INNODB;
create event ev1 on schedule every 1 second do insert into t1 values (6);
alter event ev1 rename to ev2 disable;
drop event ev2;
DROP TABLE t1;
DROP TABLE t2;
DROP TABLE t3;
DROP DATABASE db1;
