select hex(@a);
select @a, @b;
select @a;
select @a;
select @a;
create table t1 (x int);
insert into t1 values (3), (5), (7);
create table t2 (y int);
select count(*) from t1;
select * from t1;
select @x;
select @x;
select @sum;
select * from t1;
select @x;
select * from t1;
drop table t1, t2;
SELECT @a;
SELECT @a;
SELECT @a;
