SELECT * FROM mytable;
SELECT * FROM FOO;
SELECT * FROM mytable_ref;
DELETE FROM mytable WHERE id =10;
SELECT * FROM FOO;
SELECT * FROM mytable_ref;
DROP TABLE mytable_ref,FOO;
DROP TABLE mytable;
DROP DATABASE MYDB;
