CREATE TABLE t1 (a int) COMMENT 'tabÃÂ°ÃÂÃÂÃÂ¬';
CREATE TABLE t2 (a int COMMENT 'colÃÂ°ÃÂÃÂÃÂ¬');
CREATE TABLE t3 (a int, INDEX idx1(a) COMMENT 'idxÃÂ°ÃÂÃÂÃÂ¬');
CREATE TABLE t4 (a int) PARTITION BY RANGE (a) (PARTITION p1 VALUES LESS THAN (0) COMMENT 'partÃÂ°ÃÂÃÂÃÂ¬');
CREATE TABLE t5 (a int) PARTITION BY RANGE (a) SUBPARTITION BY HASH(a) SUBPARTITIONS 1 (PARTITION p1 VALUES LESS THAN (0)(SUBPARTITION sp1 COMMENT 'subpartÃÂ°ÃÂÃÂÃÂ¬'));
CREATE VIEW v1 AS SELECT 'viewÃÂ°ÃÂÃÂÃÂ¬';
CREATE PROCEDURE sp1() COMMENT 'procÃÂ°ÃÂÃÂÃÂ¬' BEGIN END;
CREATE EVENT evt1 ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 HOUR COMMENT 'evtÃÂ°ÃÂÃÂÃÂ¬' DO SELECT 0;
ALTER TABLE t1 COMMENT 'tabÃÂ°ÃÂÃÂÃÂ¬';
ALTER TABLE t1 MODIFY a int COMMENT 'colÃÂ°ÃÂÃÂÃÂ¬';
ALTER TABLE t1 ADD b int COMMENT 'colÃÂ°ÃÂÃÂÃÂ¬';
ALTER TABLE t1 ADD INDEX idx1(a) COMMENT 'idxÃÂ°ÃÂÃÂÃÂ¬';
ALTER TABLE t1 PARTITION BY RANGE (a) (PARTITION p1 VALUES LESS THAN (0) COMMENT 'partÃÂ°ÃÂÃÂÃÂ¬');
ALTER TABLE t1 PARTITION BY RANGE (a) SUBPARTITION BY HASH(a) SUBPARTITIONS 1 (PARTITION p1 VALUES LESS THAN (0)(SUBPARTITION sp1 COMMENT 'subpartÃÂ°ÃÂÃÂÃÂ¬'));
DROP TABLE t1;
ALTER VIEW v1 AS SELECT 'viewÃÂ°ÃÂÃÂÃÂ¬';
DROP VIEW v1;
ALTER PROCEDURE sp1 COMMENT 'procÃÂ°ÃÂÃÂÃÂ¬';
DROP PROCEDURE sp1;
ALTER EVENT evt1 COMMENT 'evtÃÂ°ÃÂÃÂÃÂ¬';
DROP EVENT evt1;
CREATE TABLESPACE ts1 ADD DATAFILE 'df1.ibd' COMMENT 'tsÃÂ°ÃÂÃÂÃÂ¬';
CREATE PROCEDURE p1() BEGIN /* 'SP body comment: ÃÂ°ÃÂÃÂÃÂ¬' */ END;
