SELECT * FROM t1;
SELECT T1.id from T1 LIMIT 1;
SELECT T2.id from t1 as T2 LIMIT 1;
SELECT T2.id from t1 as t2 LIMIT 1;
select count(*) from T1;
drop table t1;
create database mysqltest;
create table t1 (a int);
alter table t1 rename to T1;
drop database mysqltest;
create table t2 (a int);
delete p1.*,P2.* from t1 as p1, t2 as p2 where p1.a=P2.a;
delete P1.*,p2.* from t1 as P1, t2 as P2 where P1.a=p2.a;
update t1 as p1, t2 as p2 SET p1.a=1,P2.a=1 where p1.a=P2.a;
update t1 as P1, t2 as P2 SET P1.a=1,p2.a=1 where P1.a=p2.a;
drop table t1,t2;
create table t1 (a int);
create table t2 (a int);
drop table t1, t2;
create table t1 (a int);
create table t2 like T1;
drop table t1, t2;
create database mysql_TEST;
drop database mysql_TEST;
SELECT @@general_log;
SELECT @@lower_case_table_names;
