create database d1;
select database();
create database d2;
drop database if exists d1;
CREATE DATABASE d1;
CREATE TABLE T1(f1 INT);
select * from t1;
select * from T1;
select * from information_schema.table_privileges;
DROP DATABASE d1;
CREATE PROCEDURE p1() BEGIN END;
DROP PROCEDURE p1;
DROP DATABASE db1;
ALTER TABLE T1 RENAME t1;
DROP TABLE t1;
