DROP DATABASE XY;
CREATE DATABASE XY;
DROP DATABASE XY;
DROP TABLE IF EXISTS `Table2`;
DROP TABLE IF EXISTS `Table1`;
CREATE TABLE `Table1`(c1 INT PRIMARY KEY) ENGINE=InnoDB;
CREATE TABLE `Table2`(c1 INT PRIMARY KEY, c2 INT) ENGINE=InnoDB;
ALTER TABLE `Table2` ADD CONSTRAINT fk1 FOREIGN KEY(c2) REFERENCES `Table1`(c1);
DROP TABLE `Table2`;
DROP TABLE `Table1`;
DROP TABLE IF EXISTS Product_Order;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Customer;
CREATE TABLE Product (Category INT NOT NULL, Id INT NOT NULL,
	Price DECIMAL, PRIMARY KEY(Category, Id)) ENGINE=InnoDB;
CREATE TABLE Customer (Id INT NOT NULL, PRIMARY KEY (Id)) ENGINE=InnoDB;
CREATE TABLE Product_Order (No INT NOT NULL AUTO_INCREMENT,
	Product_Category INT NOT NULL,
	Product_Id INT NOT NULL,
	Customer_Id INT NOT NULL,
	PRIMARY KEY(No),
	INDEX (Product_Category, Product_Id),
	FOREIGN KEY (Product_Category, Product_Id)
		REFERENCES Product(Category, Id) ON UPDATE CASCADE ON DELETE RESTRICT,
	INDEX (Customer_Id),
	FOREIGN KEY (Customer_Id)
		REFERENCES Customer(Id)
	) ENGINE=INNODB;
DROP TABLE Product_Order;
DROP TABLE Product;
DROP TABLE Customer;
CREATE DATABASE my_db;
CREATE TABLE UPPERCASE_MYISAM (a INT) ENGINE=MYISAM;
CREATE TABLE lowercase_myisam (a INT) ENGINE=MYISAM;
CREATE TABLE UPPERCASE_INNODB (a INT) ENGINE=InnoDB;
CREATE TABLE lowercase_innodb (a INT) ENGINE=InnoDB;
DROP DATABASE my_db;
