SELECT COUNT(*) = 1 FROM INFORMATION_SCHEMA.PROCESSLIST
  WHERE STATE = "wait_in_enable_indexes" AND 
  INFO = "INSERT INTO t1(id) SELECT id  FROM t2";
SELECT ID FROM INFORMATION_SCHEMA.PROCESSLIST
WHERE STATE = 'wait_in_enable_indexes' AND 
INFO = "INSERT INTO t1(id) SELECT id  FROM t2" 
INTO @thread_id;
DROP TABLE t1,t2;
