
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

CREATE DATABASE db2_extended;
USE db2_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));
DROP DATABASE db2_extended;
DROP DATABASE db1_extended;
DROP DATABASE db2_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));
CREATE EVENT ev1 ON SCHEDULE AT '2030-01-01 00:00:00' DO SET @a=5;
CREATE EVENT ev2 ON SCHEDULE EVERY 5 HOUR DO SELECT 1;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT EVENT_NAME FROM INFORMATION_SCHEMA.EVENTS
       WHERE EVENT_SCHEMA='db1_extended' ORDER BY EVENT_NAME;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

CREATE PROCEDURE p1 () SELECT * FROM t1;
CREATE PROCEDURE p2 () SELECT * FROM t2;
CREATE PROCEDURE p3 () SELECT * FROM t1,t2;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
       WHERE ROUTINE_SCHEMA='db1_extended' AND ROUTINE_TYPE= 'PROCEDURE'
       ORDER BY ROUTINE_NAME;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));
CREATE TABLE t3 (a VARCHAR(10));
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

CREATE TRIGGER trig1 BEFORE INSERT ON t1 FOR EACH ROW SET NEW.a = 1;
CREATE TRIGGER trig2 BEFORE UPDATE ON t1 FOR EACH ROW SET NEW.a = 999;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT TRIGGER_NAME FROM INFORMATION_SCHEMA.TRIGGERS
       WHERE TRIGGER_SCHEMA='db1_extended' ORDER BY TRIGGER_NAME;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));
CREATE EVENT ev1 ON SCHEDULE AT '2030-01-01 00:00:00' DO SET @a=5;
CREATE EVENT ev2 ON SCHEDULE EVERY 5 HOUR DO SELECT 1;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT EVENT_NAME FROM INFORMATION_SCHEMA.EVENTS
       WHERE EVENT_SCHEMA='db1_extended' ORDER BY EVENT_NAME;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

CREATE PROCEDURE p1 () SELECT * FROM t1;
CREATE PROCEDURE p2 () SELECT * FROM t2;
CREATE PROCEDURE p3 () SELECT * FROM t1,t2;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
       WHERE ROUTINE_SCHEMA='db1_extended' AND ROUTINE_TYPE= 'PROCEDURE'
       ORDER BY ROUTINE_NAME;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));
CREATE TABLE t3 (a VARCHAR(10));
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

CREATE TRIGGER trig1 BEFORE INSERT ON t1 FOR EACH ROW SET NEW.a = 1;
CREATE TRIGGER trig2 BEFORE UPDATE ON t1 FOR EACH ROW SET NEW.a = 999;
DROP DATABASE db1_extended;
CREATE DATABASE db1_extended;
USE db1_extended;

SELECT TRIGGER_NAME FROM INFORMATION_SCHEMA.TRIGGERS
       WHERE TRIGGER_SCHEMA='db1_extended' ORDER BY TRIGGER_NAME;
DROP DATABASE db1_extended;

CREATE DATABASE db1_extended;
CREATE DATABASE db2_extended;
CREATE DATABASE db3_extended;
CREATE DATABASE db4_extended;

USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

USE db2_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

USE db3_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

USE db4_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

DROP DATABASE db1_extended;
DROP DATABASE db2_extended;
DROP DATABASE db3_extended;
DROP DATABASE db4_extended;
DROP DATABASE db2_extended;
DROP DATABASE db4_extended;

CREATE DATABASE db1_extended;
USE db1_extended;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

INSERT INTO t1 VALUES (1),(2),(21),(12),(41),(22),(51),(24);
INSERT INTO t2 VALUES (1,'abc'),(2,'abc'),(21,'abc'),(12,'abc');

SELECT COUNT(*) FROM t1;
SELECT COUNT(*) FROM t2;
DROP DATABASE db1_extended;

USE db1_extended;
SELECT COUNT(*) FROM t1;
SELECT COUNT(*) FROM t2;
DROP DATABASE db1_extended;

CREATE USER u1@localhost IDENTIFIED BY 'abc';
CREATE USER u2;
DROP USER u1@localhost,u2;

SELECT user FROM mysql.user WHERE user like 'u%';
DROP USER u1@localhost,u2;

CREATE USER u1@localhost IDENTIFIED BY 'abc';
CREATE USER u1@120.0.0.1;
CREATE USER u2;
CREATE USER u3@120.0.0.1;
DROP USER u1@localhost,u3@120.0.0.1,u1@120.0.0.1,u2;

-- report u1,u2 user rows
SELECT user FROM mysql.user WHERE user like 'u%';
DROP USER u1@120.0.0.1,u2;

CREATE USER u1@localhost IDENTIFIED BY 'abc';
CREATE USER u1@120.0.0.1;
CREATE USER u2;
CREATE USER u3@120.0.0.1;
DROP USER u1@localhost,u3@120.0.0.1,u1@120.0.0.1,u2;

-- report u1,u3 user rows
SELECT user FROM mysql.user WHERE user like 'u%';
DROP USER u1@localhost,u3@120.0.0.1;

CREATE USER u1@localhost IDENTIFIED BY 'abc';
DROP USER u1@localhost;

CREATE DATABASE db1_extended;
USE db1_extended;
CREATE USER u1@localhost;
CREATE TABLE t1 (a INT);
CREATE TABLE t2 (a INT, b VARCHAR(10), primary key(a));

INSERT INTO t1 VALUES (289), (298), (234), (456), (789);
INSERT INTO t2 VALUES (1, "on"), (2, "off"), (10, "pol"), (12, "meg");

CREATE DEFINER = u1@localhost VIEW v1 AS SELECT * FROM t2;
CREATE DEFINER = u1@localhost VIEW v2 AS SELECT t1.a as X, t2.* FROM t1,t2 ORDER BY X;
CREATE DEFINER = u1@localhost VIEW definer_name_view AS SELECT * FROM t1 union SELECT a FROM t2;

DROP DATABASE db1_extended;

DROP DATABASE db1_extended;
DROP DATABASE db1_extended;
DROP USER u1@localhost;

CREATE DATABASE db1_extended;
USE db1_extended;
CREATE USER u1@localhost;
CREATE TABLE t1 (a INT);

INSERT INTO t1 VALUES (289), (298), (234), (456), (789);
CREATE DEFINER = u1@localhost PROCEDURE p1()
BEGIN
  SET @A= 20;
  SELECT 1;
  SELECT 2, 3 UNION SELECT 4, 5;
  SELECT 6, 7, 8;
END ;

CREATE DEFINER = u1@localhost FUNCTION f1 () RETURNS int
BEGIN
SET NAMES 'big5';
END ;

CREATE DEFINER = u1@localhost FUNCTION f2() RETURNS int
BEGIN
  DECLARE n int;
  SET n:= (SELECT min(a) FROM t1);
  SET m:= (SELECT max(a) FROM t1);
END ;

CREATE DEFINER = u1@localhost PROCEDURE p2(x int)
  INSERT INTO t1 VALUES (x) ;

DROP DATABASE db1_extended;

DROP DATABASE db1_extended;
DROP DATABASE db1_extended;
DROP USER u1@localhost;
