SELECT * FROM t1
WHERE i1 IN (SELECT i1 FROM t1);
SELECT * FROM t1
WHERE i1 IN (SELECT i1 FROM t1);
SELECT * FROM t1
WHERE c1 IN (SELECT c1 FROM t1);
SELECT * FROM t1
WHERE c1 IN (SELECT c1 FROM t1);
DROP TABLE t0,t1;
