ALTER TABLE t1 ANALYZE PARTITION p1;
ALTER TABLE t1 CHECK PARTITION p1;
ALTER TABLE t1 OPTIMIZE PARTITION p1;
ALTER TABLE t1 REPAIR PARTITION p1;
DROP TABLE t1;
CREATE TABLE t1 (a int)
PARTITION BY KEY (a)
(PARTITION x0, PARTITION x1);
ALTER TABLE t1 COALESCE PARTITION 1;
DROP TABLE t1;
CREATE TABLE t1 (a int)
PARTITION BY RANGE (a)
(PARTITION x0 VALUES LESS THAN (4),
 PARTITION x1 VALUES LESS THAN (8));
ALTER TABLE t1 DROP PARTITION x1;
DROP TABLE t1;
CREATE TABLE t1 ( id INT NOT NULL,
                  fname VARCHAR(50) NOT NULL,
                  lname VARCHAR(50) NOT NULL,
                  hired DATE NOT NULL )
PARTITION BY RANGE(YEAR(hired)) (
  PARTITION p1 VALUES LESS THAN (1991),
  PARTITION p2 VALUES LESS THAN (1996),
  PARTITION p3 VALUES LESS THAN (2001),
  PARTITION p4 VALUES LESS THAN (2005));
ALTER TABLE t1 ADD PARTITION (
  PARTITION p5 VALUES LESS THAN (2010),
  PARTITION p6 VALUES LESS THAN MAXVALUE);
DROP TABLE t1;
CREATE TABLE t1 (a INT);
ALTER TABLE t1 PARTITION BY KEY(a) PARTITIONS 2;
DROP TABLE t1;
CREATE TABLE t1 (a INT) PARTITION BY HASH(a);
ALTER TABLE t1 ADD PARTITION PARTITIONS 4;
DROP TABLE t1;
create table t1 (a int) engine=innodb;
alter table t1 check partition a;
drop table t1;
