SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

CREATE TABLE t1
(
  id SMALLINT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=innodb
PARTITION BY RANGE (id)
(
  PARTITION p1 VALUES LESS THAN (2),
  PARTITION p2 VALUES LESS THAN (4),
  PARTITION p3 VALUES LESS THAN (10)
);

INSERT INTO t1 VALUES (1),(2),(3);
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM t1;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
INSERT INTO t1 VALUES(7);
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT * FROM t1;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
INSERT INTO t1 VALUES(9);
DROP TABLE t1;
