SELECT @@global.server_id;
SELECT @@global.general_log;
SELECT @@global.concurrent_insert;
SELECT * FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
SELECT COUNT(*) FROM performance_schema.persisted_variables;
SELECT * FROM performance_schema.persisted_variables;
