SELECT PLUGIN_NAME, PLUGIN_STATUS, LOAD_OPTION from INFORMATION_SCHEMA.PLUGINS
  WHERE PLUGIN_NAME like 'pfs_example%';
SELECT PLUGIN_NAME, PLUGIN_STATUS, LOAD_OPTION from INFORMATION_SCHEMA.PLUGINS
  WHERE PLUGIN_NAME like 'pfs_example%';
SELECT PLUGIN_NAME, PLUGIN_STATUS, LOAD_OPTION from INFORMATION_SCHEMA.PLUGINS
  WHERE PLUGIN_NAME like 'pfs_example%';
SELECT PLUGIN_NAME, PLUGIN_STATUS, LOAD_OPTION from INFORMATION_SCHEMA.PLUGINS
  WHERE PLUGIN_NAME like 'pfs_example%';
SELECT PLUGIN_NAME, PLUGIN_STATUS, LOAD_OPTION from INFORMATION_SCHEMA.PLUGINS
  WHERE PLUGIN_NAME like 'pfs_example%';
