select USER(),CURRENT_USER();
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
SELECT @@proxy_user;
DROP DATABASE test_user_db;
