DROP TABLE IF EXISTS t1,t2,t3;
create table t1 (a int);
insert into t1 values(1);
create table t2 select * from t1;
create table t3 (a int);
drop table t3;
select @@global.read_only;
create table t3 (a int);
insert into t1 values(1);
update t1 set a=1 where 1=0;
update t1,t2 set t1.a=t2.a+1 where t1.a=t2.a;
delete t1,t2 from t1,t2 where t1.a=t2.a;
create temporary table t3 (a int);
create temporary table t4 (a int) select * from t3;
insert into t3 values(1);
insert into t4 select * from t3;
update t1,t3 set t1.a=t3.a+1 where t1.a=t3.a;
update t1,t3 set t3.a=t1.a+1 where t1.a=t3.a;
update t4,t3 set t4.a=t3.a+1 where t4.a=t3.a;
delete t1 from t1,t3 where t1.a=t3.a;
delete t3 from t1,t3 where t1.a=t3.a;
delete t4 from t3,t4 where t4.a=t3.a;
create temporary table t1 (a int);
insert into t1 values(1);
update t1,t3 set t1.a=t3.a+1 where t1.a=t3.a;
delete t1 from t1,t3 where t1.a=t3.a;
drop table t1;
insert into t1 values(1);
lock table t1 write;
lock table t2 write;
unlock tables;
select @@global.read_only;
unlock tables;
select @@global.read_only;
lock table t1 read;
lock table t2 read;
unlock tables;
select @@global.read_only;
select @@global.read_only;
unlock tables;
select @@global.read_only;
unlock tables;
select @@global.read_only;
unlock tables;
drop temporary table if exists ttt;
drop table t1,t2;
drop database if exists mysqltest_db1;
drop database if exists mysqltest_db2;
create database mysqltest_db1;
create database mysqltest_db2;
drop database mysqltest_db1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(a INT);
INSERT INTO t1 VALUES (1), (2);
INSERT INTO t1 VALUES (3);
UPDATE t1 SET a= 1;
DELETE FROM t1;
DROP TABLE t1;
CREATE TABLE t1(f1 INT);
CREATE TEMPORARY TABLE t1(a1 INT);
DROP TABLE t1;
DROP TABLE t1;
DROP TABLE t3;
CREATE DATABASE new;
DROP DATABASE new;
CREATE TABLE t1(fld1 INT);
ALTER TABLE t1 RENAME COLUMN fld1 TO fld1;
CREATE INDEX idx1 ON t1 (fld1) USING BTREE;
DROP INDEX idx1 ON t1;
CREATE TABLE t2(fld1 INT) ENGINE=MYISAM;
UNLOCK TABLES;
DROP TABLE t2;
CREATE VIEW v1 AS SELECT * FROM t1;
DROP VIEW v1;
DROP TABLE t1;
CREATE TABLESPACE ts1 ADD DATAFILE 'ts1.ibd' ENGINE=INNODB;
DROP TABLESPACE ts1;
CREATE PROCEDURE p1() select 1;
DROP PROCEDURE p1;
CREATE EVENT event1 ON SCHEDULE EVERY 10 HOUR DO SELECT 1;
DROP EVENT event1;
CREATE TABLE t1(fld1 INT);
UNLOCK TABLES;
UNLOCK TABLES;
DROP TABLE t1;
