
let $MYSQLD_DATADIR = `select @@datadir`;

CREATE TABLE t1(i INT) ENGINE MYISAM;

DROP TABLE t1;
SET @old_lock_wait_timeout= @@lock_wait_timeout;
SET @old_lock_wait_timeout= @@lock_wait_timeout;
CREATE TABLE t0 (m INT) ENGINE=MyISAM;
CREATE TABLE t1 (i INT) ENGINE=InnoDB;
CREATE TABLE t2 (j INT) ENGINE=InnoDB;
CREATE TABLE t3 (k INT) ENGINE=InnoDB;
CREATE TABLE t4 (l INT) ENGINE=InnoDB;
SELECT * FROM t0;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
SELECT * FROM t00;
SELECT * FROM t01;
SELECT * FROM t4;
SET @@lock_wait_timeout= 1;
SELECT * FROM t0;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM t3;
SET @@lock_wait_timeout= @old_lock_wait_timeout;
SELECT * FROM t00;
SELECT * FROM t01;
SELECT * FROM t4;
DROP TABLES t0, t1, t2, t3, t4;
CREATE TABLE t1 (i INT);
CREATE DATABASE mysqltest;
INSERT INTO mysqltest.t1 VALUES (1);
SELECT * FROM t1;
SET @@lock_wait_timeout= 1;
SELECT * FROM mysqltest.t1;
SET @@lock_wait_timeout= @old_lock_wait_timeout;
SELECT * FROM test.t1;
SET @@lock_wait_timeout= 1;
ALTER DATABASE mysqltest CHARACTER SET latin1;
SET @@lock_wait_timeout= @old_lock_wait_timeout;
DROP TABLE mysqltest.t1;
CREATE TABLE t1 (i INT) ENGINE=InnoDB;
CREATE TABLE t2 (j INT) ENGINE=InnoDB;
CREATE TABLE t3 (k INT);
CREATE TABLE t4 (l INT) ENGINE=MyISAM;
SELECT * FROM t1;
SELECT * FROM t2;
SELECT * FROM mysqltest.t1;
SELECT * FROM t3;
SET @@lock_wait_timeout= 1;
SELECT * FROM t1;
SELECT * FROM t2;
SET @@lock_wait_timeout= @old_lock_wait_timeout;
SELECT * FROM mysqltest.t1;
SELECT * FROM t3;
ALTER DATABASE mysqltest CHARACTER SET latin1;
SELECT * FROM t4;
SELECT * FROM t1;
SELECT * FROM mysqltest.t4;
SELECT * FROM t3;
SET @@lock_wait_timeout= 1;
SELECT * FROM t4;
SELECT * FROM t1;
SET @@lock_wait_timeout= @old_lock_wait_timeout;
SELECT * FROM mysqltest.t4;
SELECT * FROM t3;
ALTER DATABASE mysqltest CHARACTER SET latin1;
DROP TABLES t1, t2, t3, t4;
DROP DATABASE mysqltest;
