CREATE RESOURCE GROUP test TYPE=USER VCPU=1-3 THREAD_PRIORITY=5;
ALTER RESOURCE GROUP test VCPU=0;
DROP RESOURCE GROUP test;
SET RESOURCE GROUP test FOR 4;
SET RESOURCE GROUP test FOR 4,5;
SET RESOURCE GROUP test;

-- INFORMATION_SCHEMA.RESOURCE_GROUPS shall return empty set.
SELECT * FROM INFORMATION_SCHEMA.RESOURCE_GROUPS;
