CREATE SCHEMA src;
CREATE TABLE src_t1(c1 INT);
INSERT INTO src_t1 VALUES (0), (1), (2);
CREATE TABLE src_t2 (c1 INT)
PARTITION BY LIST (c1)
SUBPARTITION BY HASH (c1) SUBPARTITIONS 3
(PARTITION p0 VALUES IN (0, 2, 4, 6, 8),
 PARTITION p1 VALUES IN (1, 3, 5, 7, 9));
INSERT INTO src_t2 VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9);
SELECT c1 FROM src_t2 ORDER BY c1;
CREATE SCHEMA dst;
CREATE TABLE dst_t1(c1 INT);
CREATE TABLE dst_t2 (c1 INT)
PARTITION BY LIST (c1)
SUBPARTITION BY HASH (c1) SUBPARTITIONS 3
(PARTITION p0 VALUES IN (1, 3, 5, 7, 9),
 PARTITION p1 VALUES IN (0, 2, 4, 6, 8));
INSERT INTO dst_t2 VALUES (1), (2), (3);
INSERT INTO dst_t2 VALUES (7), (8), (9);
SELECT c1 FROM dst_t2 ORDER BY c1;
ALTER TABLE pt1 EXCHANGE PARTITION p1 WITH TABLE t1;
ALTER TABLE pt1 EXCHANGE PARTITION p2 with TABLE t2;
UNLOCK TABLES;
UNLOCK TABLES;
LOCK TABLES dst_t1 WRITE;
ALTER TABLE dst_t1 DISCARD TABLESPACE;
UNLOCK TABLES;
LOCK TABLES dst_t2 WRITE;
ALTER TABLE dst_t2 DISCARD PARTITION p1sp0 TABLESPACE;
UNLOCK TABLES;
ALTER TABLE dst_t2 DISCARD PARTITION p0 TABLESPACE;
UNLOCK TABLES;
DROP TABLE src_t1;
DROP TABLE src_t2;
DROP TABLE dst_t1;
DROP TABLE dst_t2;
DROP SCHEMA src;
DROP SCHEMA dst;
DROP TABLE pt1;
DROP TABLE t1;
DROP TABLE t2;
