SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT @user_count;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
SELECT COUNT(USER) FROM INFORMATION_SCHEMA.PROCESSLIST;
