-- 
-- Each server has a UUID generated by server itself. It is stored in auto.cnf
-- in @@DATADIR directory. 
--
-- @@SERVER_UUID is a readonly system variable, it is initialized as the
-- server's UUID when starting. Users can get the server's UUID from
-- @@SERVER_UUID.
--
-- This test case tests whether the server's UUID can be generated, stored,
-- initialized correctly.
--#############################################################################

CALL mtr.add_suppression("Source's UUID has changed, its old UUID is");
SET GLOBAL SERVER_UUID= UUID();
