select "Caught by SQLSTATE";
select "Caught by number";
select "Caught by SQLWARNING";
select "Caught by SQLSTATE";
select "Caught by number";
select "Caught by NOT FOUND";
select "Caught by SQLSTATE";
select "Caught by number";
select "Caught by SQLEXCEPTION";
select "caught 03000";
select "caught cursor is not open";
select "Before open";
select "Before fetch";
select "Before close";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
select "handler called";
select "before RESIGNAL";
select "after RESIGNAL";
select "before RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
select "after RESIGNAL";
SELECT '2';
SELECT '1';
SELECT '3';
drop table t_warn;
drop table t_cursor;
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
SELECT 10 + 'a';
