SELECT DATABASE();
DROP DATABASE db1;
DROP DATABASE db2;
DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;
DROP DATABASE testdb;
SELECT specific_name FROM INFORMATION_SCHEMA.ROUTINES WHERE specific_name LIKE 'testf_bug11763507';
SELECT specific_name FROM INFORMATION_SCHEMA.ROUTINES WHERE specific_name LIKE 'TESTF_bug11763507';
SELECT specific_name FROM INFORMATION_SCHEMA.ROUTINES WHERE specific_name='testf_bug11763507';
SELECT specific_name FROM INFORMATION_SCHEMA.ROUTINES WHERE specific_name='TESTF_bug11763507';
SELECT SUBTIME('2006-07-16' , '05:05:02.040778');
SELECT abs('1bcd');
DROP TABLE t1;
SELECT 1/0;
SELECT 1/0;
CREATE TABLE t1 (
  id bigint(20) UNSIGNED NOT NULL
);
ALTER TABLE t1 ADD INDEX idx (id);
DROP TABLE t1;
CREATE TABLE t1(a INTEGER, b INTEGER);
INSERT INTO t1 VALUES (1,10);
DROP TABLE t1;
CREATE PROCEDURE cafe() BEGIN END;
PREPARE stmt FROM 'SELECT CONCAT(UNIX_TIMESTAMP(?))';
DEALLOCATE PREPARE stmt;
