select * from t1;
drop table t1;
create table t1 (s1 int, s2 int, s3 int);
select * from t1;
select * from t1;
drop table t1;
drop procedure if exists bug9486;
drop table if exists t1, t2;
create table t1 (id1 int, val int);
create table t2 (id2 int);
create procedure bug9486()
  update t1, t2 set val= 1 where id1=id2;
lock tables t2 write;
unlock tables;
drop procedure bug9486;
drop table t1, t2;
drop procedure if exists bug11158;
create procedure bug11158() delete t1 from t1, t2 where t1.id = t2.id;
create table t1 (id int, j int);
insert into t1 values (1, 1), (2, 2);
create table t2 (id int);
insert into t2 values (1);
select * from t1;
lock tables t2 read;
unlock tables;
drop procedure bug11158;
drop table t1, t2;
drop function if exists bug11554;
drop view if exists v1;
create table t1 (i int);
drop table t1;
drop procedure if exists p1;
drop procedure if exists p2;
create procedure p1() select * from t1;
unlock tables;
drop procedure p1;
