DROP TABLE IF EXISTS t1,t2;
CREATE TABLE t1 (c1 INT);
CREATE TABLE t2 (c1 INT);
CREATE EVENT ev1 ON SCHEDULE EVERY 1 SECOND
  DO INSERT INTO t1 VALUES(1);
SELECT 1;
SELECT 1;
INSERT INTO t1 VALUES (1);
DROP EVENT ev1;
DROP TABLE t1,t2;
