CREATE FUNCTION testQuestion() RETURNS INTEGER
BEGIN
  DECLARE foo INTEGER;
  SET foo=1;
  SET bar=2;
END $$
CREATE PROCEDURE testQuestion2()
BEGIN
  SELECT 1;
END $$
DELIMITER ;
DROP TABLE IF EXISTS t1,t2;
CREATE TABLE t1 (c1 INT);
CREATE TABLE t2 (c1 INT);
CREATE EVENT ev1 ON SCHEDULE EVERY 1 SECOND
  DO INSERT INTO t1 VALUES(1);
SELECT testQuestion();
SELECT 1;
SELECT 1;
CREATE TRIGGER trigg1 AFTER INSERT ON t1
  FOR EACH ROW BEGIN
   INSERT INTO t2 VALUES (1);
INSERT INTO t1 VALUES (1);
DROP PROCEDURE testQuestion2;
DROP TRIGGER trigg1;
DROP FUNCTION testQuestion;
DROP EVENT ev1;
DROP TABLE t1,t2;
