SELECT 1 FROM dual
WHERE EXISTS (SELECT * FROM t1 AS it);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT 1 FROM dual);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT 1 FROM dual WHERE FALSE);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.pk = 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.uk = 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ukn = 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ik = 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.d = 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.pk = ot.pk);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.uk = ot.uk);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ukn = ot.ukn);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ik = ot.ik);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.d = ot.d);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.pk > ot.pk);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.uk > ot.uk);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ukn > ot.ukn);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ik > ot.ik);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.d > ot.d);
SELECT * FROM t2 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ik = ot.pk);
SELECT * FROM t2 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.pk = ot.pk);
SELECT * FROM t2 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.uk = ot.pk);
SELECT * FROM t2 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.ukn = ot.pk);
SELECT * FROM t2 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it WHERE it.d = ot.pk);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t2 AS it WHERE ot.d = it.pk - 1);
SELECT * FROM t1 AS ot
WHERE EXISTS (SELECT * FROM t1 AS it1 JOIN t2 AS it2 ON it1.pk > it2.pk
              WHERE ot.d = it2.pk);
DROP TABLE t1, t2;
CREATE TABLE t1 (a INTEGER);
SELECT * FROM t1 WHERE EXISTS (SELECT * FROM t1 WHERE 127 = 55);
SELECT * FROM t1
WHERE EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1);
SELECT * FROM t1
WHERE EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1) AND
      EXISTS (SELECT * FROM t1);
DROP TABLE t1;
