
--
-- Check that the table options for TABLESPACE and STORAGE
-- are printed in SHOW CREATE TABLE
--

-- TABLESPACE only
CREATE TABLE t1(a int) TABLESPACE ts ENGINE=MyISAM;
DROP TABLE t1;

-- TABLESPACE + STORAGE DISK
CREATE TABLE t1(a int) TABLESPACE ts STORAGE DISK ENGINE=MyISAM;
DROP TABLE t1;

-- TABLESPACE + STORAGE MEMORY
CREATE TABLE t1(a int) TABLESPACE ts STORAGE MEMORY ENGINE=MyISAM;
DROP TABLE t1;

-- STORAGE MEMORY only
CREATE TABLE t1(a int) STORAGE MEMORY ENGINE=MyISAM;
DROP TABLE t1;

-- STORAGE DISK only
CREATE TABLE t1(a int) STORAGE DISK ENGINE=MyISAM;
DROP TABLE t1;

--
-- Check that the table options for TABLESPACE and STORAGE
-- are kept in an ALTER
--

-- TABLESPACE only
CREATE TABLE t1(a int) TABLESPACE ts ENGINE=MyISAM;
ALTER TABLE t1 ADD COLUMN b int;
DROP TABLE t1;

-- TABLESPACE and STORAGE DISK
CREATE TABLE t1(a int) TABLESPACE ts STORAGE DISK ENGINE=MyISAM;
ALTER TABLE t1 ADD COLUMN b int;
DROP TABLE t1;

--
-- Check that the table options for TABLESPACE and STORAGE
-- can be changed with an ALTER
--

-- TABLESPACE only
CREATE TABLE t1(a int) ENGINE=MyISAM;

ALTER TABLE t1 TABLESPACE ts;

ALTER TABLE t1 TABLESPACE ts2;

DROP TABLE t1;

-- STORAGE only
CREATE TABLE t1(a int) ENGINE=MyISAM;

ALTER TABLE t1 STORAGE MEMORY;

ALTER TABLE t1 STORAGE DISK;

DROP TABLE t1;

-- TABLESPACE and STORAGE
CREATE TABLE t1(a int) ENGINE=MyISAM;

ALTER TABLE t1 STORAGE MEMORY TABLESPACE ts;

ALTER TABLE t1 STORAGE DISK TABLESPACE ts2;

DROP TABLE t1;
CREATE TABLE t1 (i INTEGER) TABLESPACE innodb_file_per_table ENGINE InnoDB;
CREATE TABLE t2 (i INTEGER) TABLESPACE innodb_system ENGINE InnoDB;
ALTER TABLE t2 TABLESPACE `innodb_file_per_table.2`;
ALTER TABLE t2 TABLESPACE `innodb_file_per_table.2` ENGINE MyISAM;
ALTER TABLE t1 ENGINE MyISAM;
ALTER TABLE t2 ENGINE InnoDB;
ALTER TABLE t1 ENGINE InnoDB;
ALTER TABLE t1 TABLESPACE innodb_system ENGINE InnoDB;
ALTER TABLE t2 TABLESPACE innodb_file_per_table ENGINE InnoDB;
ALTER TABLE t1 ADD COLUMN (j INTEGER);
CREATE TABLESPACE ts ADD DATAFILE 'f.ibd' ENGINE InnoDB;
ALTER TABLE t1 TABLESPACE ts;
ALTER TABLE t1 ENGINE MyISAM;
ALTER TABLE t1 ENGINE InnoDB;

DROP TABLE t1;
DROP TABLE t2;
DROP TABLESPACE ts;
CREATE TABLESPACE ts1 ADD DATAFILE 'df1.ibd' ENGINE=InnoDB;
ALTER TABLESPACE ts1 ADD DATAFILE 'df2.ibd';
ALTER TABLESPACE ts1 ADD DATAFILE 'df2.ibd' ENGINE=INNODB;
ALTER TABLESPACE ts1 ADD DATAFILE 'df2.ibd' ENGINE=MYISAM;

DROP TABLESPACE ts1;
