select * from t1 group by d;
drop table t1;
DROP TABLE IF EXISTS t1;
CREATE TEMPORARY TABLE t1(a INT) ENGINE=MyISAM;
INSERT INTO t1 VALUES (1), (2), (3);
INSERT INTO t1 VALUES (1), (2), (3);
DROP TABLES t1;
