
CREATE TABLE th1(a TEXT,FULLTEXT INDEX(a)) ENGINE=MyISAM;
CREATE TABLE th2(a TEXT,FULLTEXT INDEX(a)) ENGINE=MyISAM;
CREATE TRIGGER trg_bi BEFORE INSERT ON th1
FOR EACH ROW
BEGIN
  INSERT IGNORE INTO th2 SELECT 1 FROM th1
  WHERE MATCH(a) AGAINST ( 'test'   IN BOOLEAN MODE);
END $
DELIMITER ;
SET @@debug='+d,simulate_bug18831513';
INSERT INTO th1 VALUES(1);
SET @@debug='-d,simulate_bug18831513';
INSERT INTO th1 VALUES(1);
DROP TRIGGER trg_bi;
DROP TABLE th1;
DROP TABLE th2;

CREATE TABLE t1(a INT);
SET @@debug= "+d,create_trigger_fail";
CREATE TRIGGER trig1 BEFORE INSERT ON t1 FOR EACH ROW BEGIN END;
INSERT INTO t1 VALUES(0);

SET @@debug= "-d,create_trigger_fail";
DROP TABLE t1;
