
CREATE TABLE t2(a INT, b INT, c INT);

CREATE TABLE t1(a INT NOT NULL, b INT, c INT);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW SET NEW.a = 1;

INSERT INTO t2 VALUES (1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1 VALUES (NULL, 2, 3);
INSERT INTO t1(a, b, c) VALUES (NULL, 20, 30);
INSERT INTO t1(b, c) VALUES (200, 300);
INSERT INTO t1(a) VALUES (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 VALUES (-1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(a, b, c) VALUES (-2, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(b, c) VALUES (2, 3), (20, 30), (200, 300);
INSERT INTO t1(a) VALUES (-3), (NULL), (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1(a, b, c) SELECT * FROM t2;
INSERT INTO t1(b, c) SELECT b, c FROM t2;
INSERT INTO t1(a) SELECT a FROM t2;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
DELETE FROM t2;

DROP TRIGGER t1_bi;

CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW SET NEW.a = NULL;

INSERT INTO t2 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
INSERT INTO t1 VALUES (1, 2, 3);
INSERT INTO t1(a, b, c) VALUES (1, 2, 3);
INSERT INTO t1(b, c) VALUES (2, 3);
INSERT INTO t1(a) VALUES (1);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
INSERT INTO t1(a, b, c) VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
INSERT INTO t1(b, c) VALUES (2, 3), (20, 30), (200, 300);
INSERT INTO t1(a) VALUES (1), (10), (100);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1(a, b, c) SELECT * FROM t2;
INSERT INTO t1(b, c) SELECT b, c FROM t2;
INSERT INTO t1(a) SELECT a FROM t2;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;

DROP TRIGGER t1_bi;

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW SET NEW.a = 999;
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
UPDATE t1 SET a = NULL WHERE a = 1;
UPDATE t1 SET a = NULL, c = NULL WHERE a = 100;
SELECT * FROM t1;

DELETE FROM t1;
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
CREATE TABLE t3(a INT, b INT);
INSERT INTO t3 VALUES (10, -10);

UPDATE t1, t3 SET t1.a = NULL, t3.a = -20 WHERE t1.a = t3.a AND t3.a = 10;
SELECT * FROM t1;
SELECT * FROM t3;

DROP TRIGGER t1_bu;
DROP TABLE t3;
DELETE FROM t1;

CREATE TABLE t3(a INT NOT NULL, b INT);
CREATE TRIGGER t3_bu BEFORE UPDATE ON t3 FOR EACH ROW SET NEW.a = 999;
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
INSERT INTO t3 VALUES (10, -10);

UPDATE t1, t3 SET t1.a = -20, t3.a = NULL WHERE t1.a = t3.a AND t3.a = 10;
SELECT * FROM t1;
SELECT * FROM t3;
DROP TRIGGER t3_bu;
DROP TABLE t3;

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW SET NEW.a = NULL;
DELETE FROM t1;
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
UPDATE t1 SET a = 99 WHERE a = 1;
UPDATE t1 SET a = 99, b = 99 WHERE a = 1;
SELECT * FROM t1;
CREATE TABLE t3(a INT, b INT);
INSERT INTO t3 VALUES (10, -10);
UPDATE t1, t3 SET t1.a = 99, t3.a = -10 WHERE t1.a = t3.a AND t3.a = 10;
SELECT * FROM t1;
SELECT * FROM t3;

DELETE FROM t1;
DELETE FROM t2;
DROP TABLE t3;

DROP TRIGGER t1_bu;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  SET NEW.b = NEW.a;
  SET NEW.a = 1;

INSERT INTO t2 VALUES (1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1 VALUES (NULL, 2, 3);
INSERT INTO t1(a, b, c) VALUES (NULL, 20, 30);
INSERT INTO t1(b, c) VALUES (200, 300);
INSERT INTO t1(a) VALUES (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 VALUES (-1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(a, b, c) VALUES (-2, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(b, c) VALUES (2, 3), (20, 30), (200, 300);
INSERT INTO t1(a) VALUES (-3), (NULL), (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1(a, b, c) SELECT * FROM t2;
INSERT INTO t1(b, c) SELECT b, c FROM t2;
INSERT INTO t1(a) SELECT a FROM t2;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;

DROP TRIGGER t1_bi;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  SET NEW.a = 99;
  SET NEW.b = NEW.a;
INSERT INTO t1 VALUES (NULL, 2, 3);
INSERT INTO t1(a, b, c) VALUES (NULL, 20, 30);
INSERT INTO t1(b, c) VALUES (200, 300);
INSERT INTO t1(a) VALUES (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 VALUES (-1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(a, b, c) VALUES (-2, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(b, c) VALUES (2, 3), (20, 30), (200, 300);
INSERT INTO t1(a) VALUES (-3), (NULL), (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 SELECT * FROM t2;
INSERT INTO t1(a, b, c) SELECT * FROM t2;
INSERT INTO t1(b, c) SELECT b, c FROM t2;
INSERT INTO t1(a) SELECT a FROM t2;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
DELETE FROM t2;

DROP TRIGGER t1_bi;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  SET NEW.a = NULL;
  SET NEW.b = NEW.a;
  SET NEW.a = 99;

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW
BEGIN
  SET NEW.a = NULL;
  SET NEW.b = NEW.a;
  SET NEW.a = 199;
INSERT INTO t1 VALUES (1, 2, 3);
INSERT INTO t1 VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
SELECT * FROM t1;
UPDATE t1 SET b = 999 WHERE c = 300;
SELECT * FROM t1;
DROP TRIGGER t1_bi;
DROP TRIGGER t1_bu;
DELETE FROM t1;

ALTER TABLE t1 ADD COLUMN a_new_is_null BOOLEAN DEFAULT NULL;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  SET NEW.a_new_is_null = NEW.a IS NULL;
  SET NEW.a = 99;

INSERT INTO t2 VALUES (1, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1 VALUES (NULL, 2, 3, NULL);
INSERT INTO t1(a, b, c) VALUES (NULL, 20, 30);
INSERT INTO t1(b, c) VALUES (200, 300);
INSERT INTO t1(a) VALUES (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 VALUES
  (-1, 2, 3, NULL), (NULL, 20, 30, NULL), (NULL, 200, 300, NULL);
INSERT INTO t1(a, b, c) VALUES (-2, 2, 3), (NULL, 20, 30), (NULL, 200, 300);
INSERT INTO t1(b, c) VALUES (2, 3), (20, 30), (200, 300);
INSERT INTO t1(a) VALUES (-3), (NULL), (NULL);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t1 SELECT t2.*, NULL FROM t2;
INSERT INTO t1(a, b, c) SELECT * FROM t2;
INSERT INTO t1(b, c) SELECT b, c FROM t2;
INSERT INTO t1(a) SELECT a FROM t2;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;

DROP TRIGGER t1_bi;

ALTER TABLE t1 ADD COLUMN a_old_is_null BOOLEAN DEFAULT NULL;
ALTER TABLE t1 ADD COLUMN b_new_is_null BOOLEAN DEFAULT NULL;
ALTER TABLE t1 ADD COLUMN b_old_is_null BOOLEAN DEFAULT NULL;
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW
BEGIN
  SET NEW.a_new_is_null = NEW.a IS NULL;
  SET NEW.a_old_is_null = OLD.a IS NULL;

  SET NEW.b_new_is_null = NEW.b IS NULL;
  SET NEW.b_old_is_null = OLD.b IS NULL;

  SET NEW.a = 99;

INSERT INTO t1(a, b, c) VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
UPDATE t1 SET a = NULL WHERE a = 1;
UPDATE t1 SET a = NULL, c = NULL WHERE a = 10;
UPDATE t1 SET b = NULL WHERE a = 100;
SELECT * FROM t1;

DELETE FROM t1;
INSERT INTO t1(a, b, c) VALUES (1, 2, 3), (10, 20, 30), (100, 200, 300);
CREATE TABLE t3(a INT, b INT);
INSERT INTO t3 VALUES (10, -10);

UPDATE t1, t3 SET t1.a = NULL, t3.a = -20 WHERE t1.a = t3.a AND t3.a = 10;
SELECT * FROM t1;
SELECT * FROM t3;

DROP TABLE t3;

DROP TRIGGER t1_bu;

DROP TABLE t1;
DROP TABLE t2;

CREATE TABLE t1(a INT, b INT NOT NULL);

CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
  SET NEW.b = NULL;
INSERT INTO t1(a) VALUES (1);
SELECT * FROM t1;
DELETE FROM t1;

DROP TRIGGER t1_bi;
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  SET NEW.b = NEW.a;
  IF NEW.b IS NULL THEN
    SET NEW.b = 1;
  END IF;
INSERT INTO t1(a) VALUES (NULL);
SELECT * FROM t1;
DELETE FROM t1;

DROP TRIGGER t1_bi;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  IF (MOD(NEW.a, 2) = 0) THEN
    SET NEW.b = NEW.a - 1;
  END IF;
INSERT INTO t1(a) VALUES (1), (2), (3), (4), (5), (6);
SELECT * FROM t1;

DROP TABLE t1;
SET sql_mode = default;

CREATE TABLE t1(a INT NOT NULL);

CREATE TABLE t2(a INT);
INSERT INTO t2 VALUES (NULL);

CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
  SET NEW.a = 1;
INSERT INTO t1 SELECT * FROM t2;
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1,t2;

CREATE TABLE t1(a INT NOT NULL);
INSERT INTO t1 VALUES (1);

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1 FOR EACH ROW
  SET NEW.a = 2;

CREATE TABLE t2(a INT);
INSERT INTO t2 VALUES (NULL);
UPDATE t1, t2 SET t1.a = t2.a;
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1,t2;

CREATE TABLE t1 (a INT NOT NULL, b VARCHAR(10) NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1 FOR EACH ROW
BEGIN
  IF NEW.b IS NULL THEN
    SET NEW.b = '123';
  END IF;
END |
delimiter ;

SELECT * FROM t1;
DROP TRIGGER t1_bi;
DROP TABLE t1;

-- A table with one NOT NULL column.
CREATE TABLE t1(a INT, b INT NOT NULL);
CREATE VIEW v1 AS SELECT * FROM t1;

-- A table with a few NOT NULL columns.
CREATE TABLE t2(a INT, b INT NOT NULL, c INT NOT NULL, d INT NOT NULL);
CREATE VIEW v2 AS SELECT * FROM t2;

-- Aux table with data for t1.
CREATE TABLE t1_data(a INT, b INT);
INSERT INTO t1_data VALUES
  (11, 12),
  (NULL, 22),
  (31, NULL),
  (NULL, NULL);

-- Aux table with data for t2.
CREATE TABLE t2_data(a INT, b INT, c INT, d INT);
INSERT INTO t2_data VALUES
  (11, 12, 13, 14),
  (NULL, 22, 23, 24),
  (31, NULL, 33, 34),
  (41, 42, NULL, 44),
  (51, 52, 53, NULL),
  (NULL, NULL, NULL, NULL);


SET @sql_mode_saved = @@sql_mode;

SET sql_mode = '';
INSERT INTO t1 VALUES (1, NULL);
INSERT INTO v1 VALUES (1, NULL);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t2 VALUES (1, 2, NULL, 4);
INSERT INTO v2 VALUES (1, 2, NULL, 4);
SELECT * FROM t2;
SELECT * FROM t2;
INSERT INTO v1(a, b) VALUES (1, NULL);
INSERT INTO t1(a, b) VALUES (1, NULL);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t2(a, b, c, d) VALUES (1, 2, NULL, 4);
INSERT INTO v2(a, b, c, d) VALUES (1, 2, NULL, 4);
SELECT * FROM t2;
SELECT * FROM t2;
INSERT INTO t1(a) VALUES (1);
INSERT INTO t1(a) VALUES (2), (3), (4);
INSERT INTO v1(a) VALUES (5);
INSERT INTO v1(a) VALUES (6), (7), (8);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a) VALUES (1);
INSERT INTO t2(a) VALUES (2), (3), (4);
INSERT INTO v2(a) VALUES (5);
INSERT INTO v2(a) VALUES (6), (7), (8);
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
INSERT INTO t1 SELECT * FROM t1_data;
INSERT INTO v1 SELECT a * 10, b * 10 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2 SELECT * FROM t2_data;
INSERT INTO v2 SELECT a * 10, b * 10, c * 10, d * 10 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
INSERT INTO t1(a, b) SELECT * FROM t1_data;
INSERT INTO v1(a, b) SELECT a * 10, b * 10 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a, b, c, d) SELECT * FROM t2_data;
INSERT INTO v2(a, b, c, d) SELECT a * 10, b * 10, c * 10, d * 10 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
INSERT INTO t1(a) SELECT a FROM t1_data;
INSERT INTO v1(a) SELECT a * 100 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a) SELECT a FROM t2_data;
INSERT INTO v2(a) SELECT a * 100 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;

SET sql_mode = 'traditional';
INSERT INTO t1 VALUES (1, NULL);
INSERT INTO v1 VALUES (1, NULL);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t2 VALUES (1, 2, NULL, 4);
INSERT INTO v2 VALUES (1, 2, NULL, 4);
SELECT * FROM t2;
SELECT * FROM t2;
INSERT INTO v1(a, b) VALUES (1, NULL);
INSERT INTO t1(a, b) VALUES (1, NULL);
SELECT * FROM t1;
SELECT * FROM t1;
INSERT INTO t2(a, b, c, d) VALUES (1, 2, NULL, 4);
INSERT INTO v2(a, b, c, d) VALUES (1, 2, NULL, 4);
SELECT * FROM t2;
SELECT * FROM t2;
INSERT INTO t1(a) VALUES (1);
INSERT INTO t1(a) VALUES (2), (3), (4);
INSERT INTO v1(a) VALUES (5);
INSERT INTO v1(a) VALUES (6), (7), (8);
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a) VALUES (1);
INSERT INTO t2(a) VALUES (2), (3), (4);
INSERT INTO v2(a) VALUES (5);
INSERT INTO v2(a) VALUES (6), (7), (8);
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;

-- Clean up
DROP TABLE t1;
DROP TABLE t2;
DROP TABLE t1_data;
DROP TABLE t2_data;
DROP VIEW v1;
DROP VIEW v2;

-- A table with one NOT NULL column.
CREATE TABLE t1(a INT, b INT NOT NULL) ;
CREATE VIEW v1 AS SELECT * FROM t1;

-- A table with a few NOT NULL columns.
CREATE TABLE t2(a INT, b INT NOT NULL, c INT NOT NULL, d INT NOT NULL) ;
CREATE VIEW v2 AS SELECT * FROM t2;

-- Aux table with data for t1.
CREATE TABLE t1_data(a INT, b INT) ;
INSERT INTO t1_data VALUES
  (11, 12),
  (NULL, 22),
  (31, NULL),
  (NULL, NULL);

-- Aux table with data for t2.
CREATE TABLE t2_data(a INT, b INT, c INT, d INT) ;
INSERT INTO t2_data VALUES
  (11, 12, 13, 14),
  (NULL, 22, 23, 24),
  (31, NULL, 33, 34),
  (41, 42, NULL, 44),
  (51, 52, 53, NULL),
  (NULL, NULL, NULL, NULL);
INSERT INTO t1(a) SELECT a FROM t1_data;
INSERT INTO v1(a) SELECT a * 100 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a) SELECT a FROM t2_data;
INSERT INTO v2(a) SELECT a * 100 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
SET sql_mode = @sql_mode_saved;
SELECT * FROM t2;
SET sql_mode = @sql_mode_saved;

-- Following scenario is to test the functionality of InnoDB

--echo
--echo --   - No column list (all columns) + NULL-value for NOT NULL column.

--echo
--error ER_BAD_NULL_ERROR
INSERT INTO t1 SELECT * FROM t1_data;
INSERT INTO v1 SELECT a * 10, b * 10 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2 SELECT * FROM t2_data;
INSERT INTO v2 SELECT a * 10, b * 10, c * 10, d * 10 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;
INSERT INTO t1(a, b) SELECT * FROM t1_data;
INSERT INTO v1(a, b) SELECT a * 10, b * 10 FROM t1_data;
SELECT * FROM t1;
DELETE FROM t1;
SELECT * FROM t1;
DELETE FROM t1;
INSERT INTO t2(a, b, c, d) SELECT * FROM t2_data;
INSERT INTO v2(a, b, c, d) SELECT a * 10, b * 10, c * 10, d * 10 FROM t2_data;
SELECT * FROM t2;
DELETE FROM t2;
SELECT * FROM t2;
DELETE FROM t2;

DROP TABLE t1;
DROP TABLE t2;
DROP TABLE t1_data;
DROP TABLE t2_data;
DROP VIEW v1;
DROP VIEW v2;
CREATE TABLE t1(a1 INT NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
UPDATE t1 SET a1 = 1 WHERE a1 IS NULL;
INSERT INTO t1 VALUES (NULL);

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
UPDATE t1 SET a1 = 1;
INSERT INTO t1 VALUES (NULL);

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, 2);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
BEGIN
  SET NEW.a1 = IFNULL(NEW.a1, 10);
  SET NEW.a2 = IFNULL(NEW.a2, 20);
INSERT INTO t1 VALUES (NULL, 1);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
BEGIN
 SET NEW.a1 = COALESCE(NEW.a1, 5);
 SET NEW.a2 = COALESCE(NEW.a2, 7);
INSERT INTO t1 VALUES (NULL, 3);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1 (a1 INT PRIMARY KEY);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = 2;
INSERT INTO t1 VALUES (NULL);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1 (a1 INT PRIMARY KEY);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = 1;

INSERT INTO t1 VALUES (NULL);
SELECT * FROM t1;
INSERT INTO t1 VALUES (NULL);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT UNIQUE);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = 1;

INSERT INTO t1 VALUES (NULL);
SELECT * FROM t1;
INSERT INTO t1 VALUES (NULL);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 DATE NOT NULL, a2 TIMESTAMP NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = '2012-03-03', NEW.a2 = '2001-01-01 09:01:00';
INSERT INTO t1 VALUES (NULL, NULL);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 CHAR(10) NOT NULL, a2 VARCHAR(255) NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = 'MySQL' , NEW.a2 = 'Includes testing of MySQL';
INSERT INTO t1 VALUES (NULL, NULL);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 BINARY(10) NOT NULL, a2 VARBINARY(255) NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = '0x41', NEW.a2 = '0x42';

INSERT INTO t1 VALUES (NULL, NULL);
SELECT HEX(a1), HEX(a2) FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT UNIQUE, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = 1;
INSERT INTO t1 VALUES (NULL, 2);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT NOT NULL, a2 INT);
CREATE TABLE t2(a1 INT NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, NULL);
INSERT INTO t2 VALUES (1, NULL);

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = 2;

UPDATE t1 SET a1 = (SELECT a2 FROM t2);
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1, t2;
CREATE TABLE t1(a1 INT PRIMARY KEY, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = 2;
UPDATE t1 SET a1 =  NULL;
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1;
CREATE TABLE t1(a1 INT UNIQUE NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = 2;
UPDATE t1 SET a1 =  NULL;
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1;
CREATE TABLE t1(a1 INT PRIMARY KEY, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = NULL;
INSERT INTO t1 VALUES (2, 2);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT UNIQUE NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = NULL;
INSERT INTO t1 VALUES (2, 2),(3,3);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
SET sql_mode = 'NO_ENGINE_SUBSTITUTION';
CREATE TABLE t1(a1 DATE NOT NULL, a2 TIMESTAMP NOT NULL, a3 TIMESTAMP NOT NULL);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = NULL , NEW.a2 = NULL , NEW.a3 = NULL;
INSERT INTO t1 VALUES ('2012-12-12','2012-12-12 12:12:12','1980-01-01 01:01:01');

DROP TRIGGER t1_bi;
DROP TABLE t1;
SET sql_mode = default;
CREATE TABLE t1(a1 CHAR(10) NOT NULL, a2 VARCHAR(255) NOT NULL, a3 INT);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = NULL , NEW.a2 = NULL;
INSERT INTO t1 VALUES ('MySQL','MySQL Testing', 1);

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 BINARY(10) NOT NULL, a2 VARBINARY(255) NOT NULL, a3 INT);
CREATE TRIGGER t1_bi BEFORE INSERT ON t1
FOR EACH ROW
SET NEW.a1 = NULL , NEW.a2 = NULL;
INSERT INTO t1 VALUES ('0x101','0x101', 1);
SELECT * FROM t1;

DROP TRIGGER t1_bi;
DROP TABLE t1;
CREATE TABLE t1(a1 INT NOT NULL, a2 INT) ;
CREATE TABLE t2(a1 INT NOT NULL, a2 INT) ;
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t2 VALUES (1, 1);

CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = NULL;
UPDATE t1 SET a1 = (SELECT MAX(a2) FROM t2);
SELECT * FROM t1;
SELECT * FROM t2;

DROP TRIGGER t1_bu;
DROP TABLE t1, t2;
CREATE TABLE t1(a1 INT PRIMARY KEY, a2 INT);
INSERT INTO t1 VALUES (1, 1);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = NULL;
UPDATE t1 SET a1 = 2;
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1;
CREATE TABLE t1(a1 INT UNIQUE NOT NULL, a2 INT);
INSERT INTO t1 VALUES (1, 1),(2, 2);
CREATE TRIGGER t1_bu BEFORE UPDATE ON t1
FOR EACH ROW
SET NEW.a1 = NULL;
UPDATE t1 SET a1 = 3;
SELECT * FROM t1;

DROP TRIGGER t1_bu;
DROP TABLE t1;

--
-- Bug#19182009 - 5.7 TRIGGERS HANDLE NOT NULL DIFFERENTLY TO OLDER VERSIONS;
--

SET @sql_mode_saved = @@sql_mode;
SET sql_mode='';

CREATE TABLE t1(a INT, b INT NOT NULL);
INSERT INTO t1(a) VALUES (1);
CREATE TRIGGER t1_trg_after_del AFTER DELETE ON t1 FOR EACH ROW SET @a := 1;
INSERT INTO t1(a) VALUES (1);

SET sql_mode = @sql_mode_saved;
DROP TABLE t1;

--
-- BUG#22202665 - ADDING A TRIGGER TO A TABLE CHANGES THE BEHAVIOUR OF NULL DETECTION
--

--disable_warnings
SET @sql_mode_saved = @@sql_mode;
SET sql_mode='';
CREATE TABLE t1(a INT NOT NULL, b INT NOT NULL);
INSERT INTO t1(a) VALUES (1);
CREATE TRIGGER t1_trg_before_ins BEFORE INSERT ON t1 FOR EACH ROW SET NEW.a=2;
INSERT INTO t1(a) VALUES (1);
SET sql_mode = @sql_mode_saved;
DROP TABLE t1;
