drop table if exists t1;
create table t1 (i int);
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
delete from t1;
delete from t1;
delete from t1;
select * from t1;
delete from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select * from t1;
select @@session.max_user_connections, @@global.max_user_connections;
select @@session.max_user_connections, @@global.max_user_connections;
select @@session.max_user_connections, @@global.max_user_connections;
select * from t1;
select @@session.max_user_connections, @@global.max_user_connections;
drop table t1;
