select * from t1;
select * from v1;
delete from t1;
select * from t1 order by a,b;
select * from v1 order by a,b;
drop view v1;
drop table t1;
create table t1 (a int, primary key (a), b int) engine=myisam;
create table t2 (a int, primary key (a), b int) engine=myisam;
insert into t2 values (1000, 2000);
create view v3 (a,b) as select t1.a as a, t2.a as b from t1, t2;
insert into v3(a) values (1);
insert into v3(b) values (10);
insert into v3(a) select a from t2;
insert into v3(b) select b from t2;
insert into v3(a) values (1) on duplicate key update a=a+10000+VALUES(a);
select * from t1;
select * from t2;
delete from t1;
select * from v3;
drop view v3;
drop tables t1,t2;
DROP TABLE IF EXISTS t1, t2, t3, table_broken;
DROP VIEW IF EXISTS view_broken;
CREATE TABLE t1(a INT) ENGINE=MyISAM;
CREATE TABLE t2(b INT);
CREATE TABLE t3(c INT);
CREATE TABLE t4(d INT);
CREATE VIEW v1 AS SELECT * FROM t2;
