SELECT * FROM t2 tmp1, t2 tmp2 WHERE tmp1.a<>tmp2.a;
DELETE FROM t2;
SELECT * FROM t2 tmp1, t2 tmp2 WHERE tmp1.a<>tmp2.a;
DROP TABLE t1,t2;
create table t1(a int);
insert into t1 values(2),(3);
insert into t1 with t1 as (select 36 as col from t1) select * from t1;
select * from t1;
create table t2 with t1 as (select 72 as col from t1) select * from t1;
select * from t1;
select * from t2;
drop table t1,t2;
CREATE TABLE t1(a INTEGER);
DROP TABLE t1;
CREATE TABLE t1 (f1 TEXT);
INSERT INTO t1 VALUES ('x');
DROP TABLE t1;
