insert t1 values (10);
select * from t1;
insert t1 values (20);
select * from t1;
insert t1 values (30);
create table t2 (a int);
insert t1 values (40);
select * from t1;
drop table t1;
drop table if exists t1;
create table t1(a int, b int, c varchar(20), primary key(a)) engine = innodb;
insert into t1 values(1, 1, 'a');
insert into t1 values(2, 2, 'b');
update t1 set c = 'aa' where a = 1;
update t1 set c = 'bb' where a = 2;
update t1 set c = 'aa' where a = 1;
select count(*) from t1;
drop table t1;
CREATE TABLE t1(a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES(1);
SELECT @@autocommit;
INSERT INTO t1 VALUES(1);
DROP TABLE t1;
CREATE TABLE t1(a INT, KEY(a)) ENGINE=InnoDB;
INSERT INTO t1 VALUES(1),(2);
UPDATE t1 SET a=3 WHERE a=1;
UPDATE t1 SET a=4 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=1;
UPDATE t1 SET a=3 WHERE a=1;
UPDATE t1 SET a=4 WHERE a=2;
UPDATE t1 SET a=5 WHERE a=1;
DROP TABLE t1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1(a INT, b INT, PRIMARY KEY(a)) engine=InnoDB;
INSERT INTO t1 VALUES (1, 1), (2, 2);
UPDATE t1 SET b= 3 WHERE a=1;
UPDATE t1 SET b=4 WHERE a=2;
UPDATE t1 SET b=6 WHERE a=2;
DROP TABLE t1;
CREATE TABLE t1 (a INT) engine=InnoDB;
INSERT INTO t1 VALUES (1);
SELECT * FROM t1;
INSERT INTO t1 VALUES (2);
SELECT * FROM t1;
INSERT INTO t1 VALUES (2);
UPDATE t1 SET a=1 WHERE a=2;
SELECT * FROM t1;
DROP TABLE t1;
CREATE TABLE t1 (a INT) ENGINE=InnoDB;
INSERT INTO t1 VALUES (1);
INSERT INTO t2 VALUES (1);
DELETE FROM t1;
SELECT a FROM t2 WHERE a=1 FOR SHARE;
SELECT COUNT(*) = 1 FROM information_schema.innodb_trx
  WHERE trx_query = 'SELECT a FROM t1 WHERE a=1 FOR UPDATE' AND
  trx_operation_state = 'starting index read' AND
  trx_state = 'LOCK WAIT';
SELECT a FROM t2 WHERE a=1 FOR UPDATE;
DROP TABLE t1;
DROP TABLE t2;
CREATE TABLE t1 (a INT) ENGINE=INNODB;
INSERT INTO t1 VALUES (1);
SELECT * FROM t1;
DROP TABLE t1;
create table asd (a int);
insert into asd values(1);
unlock tables;
insert into asd values(1);
unlock tables;
drop table asd;
CREATE TABLE t1 (a INT) ENGINE=INNODB;
INSERT INTO t1 VALUES (1);
DROP TABLE t1;
